import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'losM5',
    created: 1736998940920,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ακεραιότητα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zbotC',
    created: 1736998942541,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σταθερότητα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9VwQR',
    created: 1736998944290,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'κατώφλι',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cNQ9N',
    created: 1736998945739,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ενεργώ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6JtRZ',
    created: 1736998947442,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αντανάκλαση',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xtm2z',
    created: 1736998949094,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αποτέλεσμα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CERyq',
    created: 1736998951304,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'καθίσταμαι, σταθερός',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GhzMP',
    created: 1736998952775,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'θεωρώ, λαμβάνω υπόψη',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7Kt-0',
    created: 1736998954214,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'καρέκλα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hOJju',
    created: 1736998955739,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'δικαιολόγησε',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rA_Vk',
    created: 1736998957266,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'παραμέλησε',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6-4nd',
    created: 1736998960008,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'πειθώ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kKIvV',
    created: 1736998970159,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σταδιακά',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wRQbi',
    created: 1736998980211,
    data: {
      language: 'ar',
      source: 'ضمنا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'συμπεριλαμβανομένου',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-JJ7H',
    created: 1736998989771,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ιδιαίτερα',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NmQlf',
    created: 1736998999962,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αμέσως',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gwPuW',
    created: 1736999009592,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'περίπου',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_JHVv',
    created: 1736999019717,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αρκετά',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WDRN0',
    created: 1736999038999,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'επίμονος',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nHDZ_',
    created: 1736999988164,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'συμπεριληπτικός',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'N3OIo',
    created: 1736999990348,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'διασκεδαστικός',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'X5cGl',
    created: 1736999992004,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'προσοχή',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'N2ne_',
    created: 1736999992831,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'τεμπέλης',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '60lu4',
    created: 1736999994201,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: '',
      example: '',
      definition: '',
      translation: 'εμφανής',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
