import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'O2_9Q',
    created: 1736991592930,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridad, honestidad',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'A2x9D',
    created: 1736991594199,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resistencia, firmeza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sWdX-',
    created: 1736991597735,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umbral',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zto7t',
    created: 1736991599183,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: '',
      example: '',
      definition: '',
      translation: 'actuar, comportarse',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 't6FLp',
    created: 1736991600690,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reflejo, reflexión',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BjW_E',
    created: 1736991602025,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, saldo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_qU0e',
    created: 1736991604041,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'quedarse, permanecer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PdQfF',
    created: 1736991606247,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar, tomar en cuenta',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'A4FgI',
    created: 1736991607553,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'silla',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Cchwm',
    created: 1736991609162,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificó',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6SOVg',
    created: 1736991610749,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'desatender, negar atención',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2mhIA',
    created: 1736991612114,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'convencer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'T-4Cp',
    created: 1736991613175,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-KWSZ',
    created: 1736991614165,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'seguramente, con seguridad',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z0w8t',
    created: 1736991615075,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'en particular',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zjKfw',
    created: 1736991616586,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ahora mismo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JjULx',
    created: 1736991617460,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'casi, aproximadamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dXoaF',
    created: 1736992524227,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficientemente, de manera suficiente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kBqkm',
    created: 1736992525773,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'diligente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aOaVq',
    created: 1736992527143,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integral, completo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'a53nV',
    created: 1736992529468,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'divertido, entretenido',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dzI-T',
    created: 1736992533408,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cuidado, precaución',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DR3qS',
    created: 1736992534548,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perezoso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IcVwK',
    created: 1736992536773,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: '',
      example: '',
      definition: '',
      translation: 'destacado, notorio',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
