import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'M8t13',
    created: 1736992674212,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: '',
      example: '',
      definition: '',
      translation: '清廉',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wo0K1',
    created: 1736992676168,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: '',
      example: '',
      definition: '',
      translation: '不動',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7kAVd',
    created: 1736992677505,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: '',
      example: '',
      definition: '',
      translation: '敷居',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ws2wu',
    created: 1736992679098,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: '',
      example: '',
      definition: '',
      translation: '行動する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7SdxM',
    created: 1736992680435,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: '',
      example: '',
      definition: '',
      translation: '反射',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IZPYD',
    created: 1736993730204,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: '',
      example: '',
      definition: '',
      translation: '残り, 成果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DJYg6',
    created: 1736993731817,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: '',
      example: '',
      definition: '',
      translation: '定まる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'leh3P',
    created: 1736993733497,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: '',
      example: '',
      definition: '',
      translation: '考える, 尊重する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fzfRH',
    created: 1736993734847,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: '',
      example: '',
      definition: '',
      translation: '椅子',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'a4zk0',
    created: 1736993736349,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: '',
      example: '',
      definition: '',
      translation: '説明する, 弁明する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H-zPF',
    created: 1736993738311,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: '',
      example: '',
      definition: '',
      translation: '無視する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iVZ2F',
    created: 1736993739840,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: '',
      example: '',
      definition: '',
      translation: '納得させる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qka8Z',
    created: 1736993740771,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: '段階的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UouQb',
    created: 1736993741767,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: '確実に, 必ず',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BeBgh',
    created: 1736993742654,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: '特に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qYoQb',
    created: 1736993744361,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'すぐに',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1OAec',
    created: 1736993745113,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ほぼ, おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'f_5uC',
    created: 1736993746189,
    data: {
      language: 'ar',
      source: 'بِشَكْلٍ كَافٍ',
      ipa: '',
      example: '',
      definition: '',
      translation: '十分に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gcDWX',
    created: 1736993747704,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: '',
      example: '',
      definition: '',
      translation: '勤勉な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jeaOD',
    created: 1736993749301,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: '',
      example: '',
      definition: '',
      translation: '包括的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JegST',
    created: 1736993754267,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: '',
      example: '',
      definition: '',
      translation: '楽しい, 面白い',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eyHQ8',
    created: 1736993759517,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: '',
      example: '',
      definition: '',
      translation: '注意, 警戒',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'J6gG9',
    created: 1736993760642,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: '怠け者, なまけもの',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XBEv1',
    created: 1736993762269,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: '',
      example: '',
      definition: '',
      translation: '目立つ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
