import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'J3VAm',
    created: 1737002246168,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'სისუფთავე, სამართლიანობა',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kNHFV',
    created: 1737002247006,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გამძლეობა',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'k67CV',
    created: 1737002247930,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'საფეხური',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'D3KtI',
    created: 1737002248902,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მოქმედება, გზავება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SJpIX',
    created: 1737002249898,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: '',
      example: '',
      definition: '',
      translation: 'რეფლექსია',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'thUrt',
    created: 1737002250801,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შედეგი, შედეგები',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Z3nwV',
    created: 1737002251581,
    data: {
      language: 'ar',
      source: 'იუკრ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'იუკრ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DTgkU',
    created: 1737002252537,
    data: {
      language: 'ar',
      source: 'იაკადრებ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შენ შეძლებ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'twFQy',
    created: 1737002253402,
    data: {
      language: 'ar',
      source: 'კურსი',
      ipa: '',
      example: '',
      definition: '',
      translation: 'კურსი',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'w6kRI',
    created: 1737002254517,
    data: {
      language: 'ar',
      source: 'იბრერ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'იბრერ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yPHOO',
    created: 1737002255336,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მივატოვო, გაუფრთხილება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PxYRq',
    created: 1737002256250,
    data: {
      language: 'ar',
      source: 'قنع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'კმაყოფილი',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8N_eA',
    created: 1737002257078,
    data: {
      language: 'ar',
      source: 'تدريجياً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ნაბიჯ-ნაბიჯ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3reK0',
    created: 1737002257858,
    data: {
      language: 'ar',
      source: 'ضمنا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შიგნით',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wzla4',
    created: 1737002258624,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصულად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'h6fmJ',
    created: 1737002259430,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ახლავე',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-zojS',
    created: 1737002260160,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაახლოებით',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3trtn',
    created: 1737002269906,
    data: {
      language: 'ar',
      source: 'ბრიტანული',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ბრიტანული',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Up1qM',
    created: 1737002279674,
    data: {
      language: 'ar',
      source: 'მტკიცე',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მტკიცე',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 't-Kli',
    created: 1737002289479,
    data: {
      language: 'ar',
      source: 'შამელ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შამელი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'usYe2',
    created: 1737002299585,
    data: {
      language: 'ar',
      source: 'მომხიბლავი',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მომხიბლავი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6my0V',
    created: 1737002300491,
    data: {
      language: 'ar',
      source: 'ჰადრ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ჰადრ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iwIgC',
    created: 1737002310297,
    data: {
      language: 'ar',
      source: 'متكاسل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ზარმაცი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5GuI5',
    created: 1737002322240,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გამორჩეული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
