import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'FExTP',
    created: 1736994780590,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriteit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'O4VC5',
    created: 1736994781790,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: '',
      example: '',
      definition: '',
      translation: 'standvastigheid',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TZ1WU',
    created: 1736994783452,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'drempel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_F52T',
    created: 1736994784775,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zich gedragen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'L1w03',
    created: 1736994786098,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reflectie',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OllQK',
    created: 1736994787376,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultaat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'd7VUg',
    created: 1736994788691,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vaststellen, zich vestigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gMNVe',
    created: 1736994789971,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'beschouwen, overwegen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8tavG',
    created: 1736994791274,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'stoel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DNGXc',
    created: 1736994793015,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtvaardigen, verklaren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eJXhS',
    created: 1736994794361,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verwaarlozen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Fmun1',
    created: 1736994796140,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overtuigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-8V6r',
    created: 1736994797169,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geleidelijk, stapsgewijs',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pGoZu',
    created: 1736994798017,
    data: {
      language: 'ar',
      source: 'ضمنا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inbegrepen, inclusief',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'toPDx',
    created: 1736994798786,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'in het bijzonder',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'izAPg',
    created: 1736994800363,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'direct, onmiddellijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JsRgl',
    created: 1736994801178,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bijna, ongeveer',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VWWr3',
    created: 1736994802106,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voldoende, voldoende manier',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NAsA8',
    created: 1736994803330,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ijverig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Z4PeC',
    created: 1736994804669,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omvattend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gJJWJ',
    created: 1736994805859,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vermakelijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2t2_5',
    created: 1736994807491,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzichtigheid',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bVxeD',
    created: 1736994808320,
    data: {
      language: 'ar',
      source: 'متكاسل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lui, traag',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8tkCe',
    created: 1736994809604,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: '',
      example: '',
      definition: '',
      translation: 'opvallend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
