import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'yXtDQ',
    created: 1737090946604,
    data: {
      language: 'da',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'インテグリティ, 誠実',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'm-uyg',
    created: 1737090956397,
    data: {
      language: 'da',
      source: 'en modstandsdygtighed',
      ipa: '',
      example: '',
      definition: '',
      translation: '耐性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'FoAPq',
    created: 1737090966020,
    data: {
      language: 'da',
      source: 'en tærskel',
      ipa: '',
      example: '',
      definition: '',
      translation: '敷居, しきい',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nwkAU',
    created: 1737090985048,
    data: {
      language: 'da',
      source: 'en disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: '決定, 配置',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-gqEo',
    created: 1737090994819,
    data: {
      language: 'da',
      source: 'en eftervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: '影響, 後遺症',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'aNPRv',
    created: 1737091014332,
    data: {
      language: 'da',
      source: 'et resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, 成果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kFBN7',
    created: 1737091024952,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: '',
      example: '',
      definition: '',
      translation: '認める, 承認する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-VDyZ',
    created: 1737091053058,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WQDBB',
    created: 1737091082872,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: '',
      example: '',
      definition: '',
      translation: '聖なる, 神聖な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'z_mBR',
    created: 1737091093371,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '',
      example: '',
      definition: '',
      translation: '正当化する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7gsyy',
    created: 1737091121771,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: '',
      example: '',
      definition: '',
      translation: '怠る, 無視する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hOEIu',
    created: 1737091140987,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: '説得する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xSfTM',
    created: 1737091168498,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: '徐々に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6gBuO',
    created: 1737091187080,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗黙の',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ATSFu',
    created: 1737091206248,
    data: {
      language: 'da',
      source: 'især',
      ipa: '',
      example: '',
      definition: '',
      translation: '特に, 特別に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'H6mlE',
    created: 1737091236131,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: '',
      example: '',
      definition: '',
      translation: '即座の, 瞬時の',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'd6go7',
    created: 1737091264293,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'まあまあ, そこそこ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5xivB',
    created: 1737091274654,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: '十分な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0nAEl',
    created: 1737091311505,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '',
      example: '',
      definition: '',
      translation: '持続的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'D1zdo',
    created: 1737091348266,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: '広範な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'eSU22',
    created: 1737091376622,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '素晴らしい, 快適',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '8uAAk',
    created: 1737091387169,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: '',
      example: '',
      definition: '',
      translation: '慎重な, 用心深い',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '8cnWV',
    created: 1737091396993,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '',
      example: '',
      definition: '',
      translation: '抵抗する, 反抗的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'QYCoI',
    created: 1737091433116,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要な, 本質的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
