import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'p6O8t',
    created: 1737092498654,
    data: {
      language: 'da',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridade',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nr2Gg',
    created: 1737092508669,
    data: {
      language: 'da',
      source: 'en modstandsdygtighed',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliência, resistência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MAcBI',
    created: 1737092518379,
    data: {
      language: 'da',
      source: 'en tærskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'um limiar, uma sole',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'f8suA',
    created: 1737092519355,
    data: {
      language: 'da',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposição',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DDVkO',
    created: 1737092529021,
    data: {
      language: 'da',
      source: 'en eftervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uma consequência, um efeito',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DJzkv',
    created: 1737092538941,
    data: {
      language: 'da',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4KptZ',
    created: 1737092558198,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconhecer, aceitar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wwSf_',
    created: 1737092586402,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar, ponderar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ojEFN',
    created: 1737092596262,
    data: {
      language: 'da',
      source: 'sagrado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sagrado, sagrada',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4okrs',
    created: 1737092606575,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-Y6PT',
    created: 1737092635038,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negligenciar, descurar, faltar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'IoWK9',
    created: 1737092654083,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuadir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dr0gl',
    created: 1737092682940,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradual',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AkiBU',
    created: 1737092683996,
    data: {
      language: 'da',
      source: 'implícito',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícito, subentendido',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9Pyho',
    created: 1737092712932,
    data: {
      language: 'da',
      source: 'især',
      ipa: '',
      example: '',
      definition: '',
      translation: 'especialmente, sobretudo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'etWLO',
    created: 1737092732321,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: '',
      example: '',
      definition: '',
      translation: 'imediato, pronto',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6OJL8',
    created: 1737092742956,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mais ou menos, razoável',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'N1wps',
    created: 1737092762217,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Y6T_R',
    created: 1737092790314,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sustentável, perene',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'KkGWm',
    created: 1737092818285,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'abrangente, extensivo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 't_3qR',
    created: 1737092837825,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'maravilhoso, agradável, lindo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nauNe',
    created: 1737092857351,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cauteloso, cuidadoso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gmqb1',
    created: 1737092869557,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'relutante, resistente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lzlZW',
    created: 1737092888768,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'essencial, significativo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
