import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'U8VZo',
    created: 1737090044048,
    data: {
      language: 'da',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: '完整性, 正直性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lJ5xN',
    created: 1737090054298,
    data: {
      language: 'da',
      source: 'en modstandsdygtighed',
      ipa: '',
      example: '',
      definition: '',
      translation: '韧性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iX6p4',
    created: 1737090064062,
    data: {
      language: 'da',
      source: 'en tærskel',
      ipa: '',
      example: '',
      definition: '',
      translation: '门槛',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5NIS9',
    created: 1737090074829,
    data: {
      language: 'da',
      source: 'en disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: '安排, 处置',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TTocU',
    created: 1737090084505,
    data: {
      language: 'da',
      source: 'en eftervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: '后果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HBJn3',
    created: 1737090103589,
    data: {
      language: 'da',
      source: 'et resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: '结果, 成果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 's8EKQ',
    created: 1737090122814,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: '',
      example: '',
      definition: '',
      translation: '承认, 认可',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SweXb',
    created: 1737090151204,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '',
      example: '',
      definition: '',
      translation: '考虑',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wlGkc',
    created: 1737090179546,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: '',
      example: '',
      definition: '',
      translation: '神圣, 圣洁',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qcekx',
    created: 1737090199860,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '',
      example: '',
      definition: '',
      translation: '辩解, 证明',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'L6-ko',
    created: 1737090228076,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽视, 疏忽, 缺席',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3PP42',
    created: 1737090238158,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gO0b_',
    created: 1737090268835,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐渐的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iYxp8',
    created: 1737090278522,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '隐含的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'N9RxP',
    created: 1737090306593,
    data: {
      language: 'da',
      source: 'især',
      ipa: '',
      example: '',
      definition: '',
      translation: '特别, 尤其',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0X9X0',
    created: 1737090325891,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即, 马上',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SoLJD',
    created: 1737090344977,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: '',
      example: '',
      definition: '',
      translation: '还不错, 差不多',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RoHBN',
    created: 1737090365431,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'McRW-',
    created: 1737090384671,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '',
      example: '',
      definition: '',
      translation: '持续的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'FfIji',
    created: 1737090412831,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: '广泛的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PJGhx',
    created: 1737090440786,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '美好, 愉快, 宜人',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Wb1Um',
    created: 1737090460412,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: '',
      example: '',
      definition: '',
      translation: '小心, 谨慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TKdlW',
    created: 1737090470275,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '',
      example: '',
      definition: '',
      translation: '抵触的, 反抗的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GT-rM',
    created: 1737090481132,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的, 显著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
