import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'PTAfA',
    created: 1737090500620,
    data: {
      language: 'da',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: '完整性, 正直',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Um_o1',
    created: 1737090510688,
    data: {
      language: 'da',
      source: 'en modstandsdygtighed',
      ipa: '',
      example: '',
      definition: '',
      translation: '韌性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AX3FK',
    created: 1737090520317,
    data: {
      language: 'da',
      source: 'en tærskel',
      ipa: '',
      example: '',
      definition: '',
      translation: '門檻',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CgzaE',
    created: 1737090531304,
    data: {
      language: 'da',
      source: 'en disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: '決定, 支配, 安排',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'VAxaG',
    created: 1737090541033,
    data: {
      language: 'da',
      source: 'en eftervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: '後果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rZGwd',
    created: 1737090560286,
    data: {
      language: 'da',
      source: 'et resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, 成果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A2dgh',
    created: 1737090579745,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: '',
      example: '',
      definition: '',
      translation: '承認, 認可, 接受',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'j-Icd',
    created: 1737090607766,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Sr4NA',
    created: 1737090635877,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: '',
      example: '',
      definition: '',
      translation: '神聖, 聖潔',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wRAh7',
    created: 1737090655316,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '',
      example: '',
      definition: '',
      translation: '辯解, 合理化',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zz0Lo',
    created: 1737090683369,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽視, 疏忽, 缺席',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HLJBv',
    created: 1737090702757,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tvpEd',
    created: 1737090723213,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐漸的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0VT_F',
    created: 1737090733110,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '隱含的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vAVny',
    created: 1737090761305,
    data: {
      language: 'da',
      source: 'især',
      ipa: '',
      example: '',
      definition: '',
      translation: '特別',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SQ-Pi',
    created: 1737090780861,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即, 立刻',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Vxbn1',
    created: 1737090791520,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: '',
      example: '',
      definition: '',
      translation: '還可以, 差不多',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yMk4n',
    created: 1737090810657,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: '足夠',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'XBBhf',
    created: 1737090838629,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '',
      example: '',
      definition: '',
      translation: '持續的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'L-pUw',
    created: 1737090866583,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: '廣泛的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ryHhY',
    created: 1737090886435,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '美好, 愉快, 宜人',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_8jqt',
    created: 1737090905621,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: '',
      example: '',
      definition: '',
      translation: '小心, 謹慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hl8-Z',
    created: 1737090915261,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '',
      example: '',
      definition: '',
      translation: '抗拒的, 反抗的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GBqb-',
    created: 1737090935817,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要, 本質的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
