import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'WgccI',
    created: 1736963389886,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ինտեգրիտետ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_YYkk',
    created: 1736963390837,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'դիմադրողականություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TYrkV',
    created: 1736963391813,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'շեմ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3OMpc',
    created: 1736963392611,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'կարգադրություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G0DP2',
    created: 1736963393439,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ազդեցություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TGaK_',
    created: 1736963394365,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0ycdP',
    created: 1736963395689,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ճանաչել, ընդունել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NWmw1',
    created: 1736963396798,
    data: {
      language: 'de',
      source: 'halten',
      ipa: '',
      example: '',
      definition: '',
      translation: 'պահել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KlRl3',
    created: 1736963397768,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նվիրել, հատկացնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VyvGo',
    created: 1736963398781,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդարացնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2uJzj',
    created: 1736963399575,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անտեսում',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GZlAy',
    created: 1736963400384,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WkNkF',
    created: 1736963401609,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: '',
      example: '',
      definition: '',
      translation: 'քայլ առ քայլ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's9zqo',
    created: 1736963402617,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անհայտ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A5lXn',
    created: 1736963403547,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'առաջին հերթին',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BTcpt',
    created: 1736963404630,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: '',
      example: '',
      definition: '',
      translation: 'միանգամից',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wME03',
    created: 1736963406093,
    data: {
      language: 'de',
      source: 'rund',
      ipa: '',
      example: '',
      definition: '',
      translation: 'լիակատար, գլանաձև',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mpAmw',
    created: 1736963408162,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'բավարար',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0zJpa',
    created: 1736963409275,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համառ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-R_2B',
    created: 1736963410314,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ընդհանուր, համապարփակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XKBef',
    created: 1736963411144,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հրաշալի',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FChAA',
    created: 1736963412317,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հետադարձ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mjcab',
    created: 1736963413273,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հակառակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uEZh7',
    created: 1736963414050,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նշանակալի',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
