import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Bmxu4',
    created: 1736963309833,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriti',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nGQ0k',
    created: 1736963311855,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ketahanan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd6cNp',
    created: 1736963313307,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ambang, batas',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YYlmv',
    created: 1736963314003,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perintah, susunan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm5pGD',
    created: 1736963314946,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kesan, impak',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd1_lr',
    created: 1736963316290,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil, keputusan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EkPzT',
    created: 1736963318233,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengakui, menghargai',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'E-apD',
    created: 1736963324155,
    data: {
      language: 'de',
      source: 'halten',
      ipa: '',
      example: '',
      definition: '',
      translation: 'memegang, menahan, menyimpan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AlJwR',
    created: 1736963325709,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedikasikan, persembahkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HPV86',
    created: 1736963326563,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membenarkan, justifikasi',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_yVxg',
    created: 1736963327564,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'pengabaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fMFjE',
    created: 1736963329080,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'memujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MaEZ5',
    created: 1736963330651,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara beransur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QGJZ-',
    created: 1736963332116,
    data: {
      language: 'de',
      source: 'implisit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tersirat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NALga',
    created: 1736963333115,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terutama',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aNFFH',
    created: 1736963335489,
    data: {
      language: 'de',
      source: 'segera',
      ipa: '',
      example: '',
      definition: '',
      translation: 'segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_HEDK',
    created: 1736963337866,
    data: {
      language: 'de',
      source: 'rund',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bulat, bentuk bulat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9Bd6I',
    created: 1736963339310,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup, memadai',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'J7m_V',
    created: 1736963341093,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tegas, kekal',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C5xiF',
    created: 1736963342820,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menyeluruh, lengkap',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hIOD9',
    created: 1736963343607,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menawan, menggembirakan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bnDE9',
    created: 1736963345467,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tenang, sederhana',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aGFqO',
    created: 1736963346400,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'enggan, tidak rela',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xMCNq',
    created: 1736963348032,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bermakna, signifikan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
