import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '18l-s',
    created: 1736962585997,
    data: {
      language: 'de',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridade',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uafyp',
    created: 1736962586865,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliência, resistência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UCXaO',
    created: 1736962587966,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'soleira, limite',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GrSlo',
    created: 1736962588833,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'a ordem, a disposição',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lUExo',
    created: 1736962589555,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'o efeito, a consequência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9Bjs8',
    created: 1736962590380,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, consequência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jPF2Y',
    created: 1736962591325,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconhecer, aceitar, respeitar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I2m6P',
    created: 1736962592174,
    data: {
      language: 'de',
      source: 'halten',
      ipa: '',
      example: '',
      definition: '',
      translation: 'segurar, manter, parar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fkT_V',
    created: 1736962593407,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicar, consagrar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Xj1QL',
    created: 1736962594571,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZANYZ',
    created: 1736962595504,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negligência, desleixo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mBnj9',
    created: 1736962596303,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuadir, convencer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FEBpw',
    created: 1736962597256,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente, passo a passo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jM7GI',
    created: 1736962598051,
    data: {
      language: 'de',
      source: 'implícito',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícito',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Rqfjs',
    created: 1736962598805,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'principalmente, sobretudo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wP5TZ',
    created: 1736962599720,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: '',
      example: '',
      definition: '',
      translation: 'imediatamente, de imediato',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'q0cvO',
    created: 1736962600646,
    data: {
      language: 'de',
      source: 'rund',
      ipa: '',
      example: '',
      definition: '',
      translation: 'redondo, circular',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3dJ4w',
    created: 1736962601635,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uCFgO',
    created: 1736962602530,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente, tenaz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ae_VR',
    created: 1736962603418,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'abrangente, completo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nT1Q3',
    created: 1736962604351,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'encantador, lindo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7opJ2',
    created: 1736962605890,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reservado, discreto',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vLZbj',
    created: 1736962606702,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'relutante, contrariado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kkHln',
    created: 1736962607522,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significativo, importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
