import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'kBQzU',
    created: 1736962904039,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integritet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qmfk1',
    created: 1736962905211,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motståndskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'l-MaN',
    created: 1736962906142,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tröskel, ränna, gräns',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1BVts',
    created: 1736962907306,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ordning, anordning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Arow8',
    created: 1736962908215,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'effekt, påverkan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vHNGp',
    created: 1736962909083,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat, utfall, slutresultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9w3Mw',
    created: 1736962910081,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkänna, acceptera, respektera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6STJ9',
    created: 1736962911878,
    data: {
      language: 'de',
      source: 'halten',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hålla, behålla, fästa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JhjTE',
    created: 1736962914110,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ägnar, dedikera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PHYp0',
    created: 1736962915157,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rättfärdiga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ccI4J',
    created: 1736962916479,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försummelse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zmtII',
    created: 1736962917586,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'X8tOu',
    created: 1736962918328,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lwgL5',
    created: 1736962919785,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'underförstådd',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jC453',
    created: 1736962920644,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'framför allt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zZ_VT',
    created: 1736962921430,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omedelbart, genast',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GcGRe',
    created: 1736962922970,
    data: {
      language: 'de',
      source: 'rund',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rund, cirkelformad',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CpVoa',
    created: 1736962924082,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräcklig, godkänd',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ARFm6',
    created: 1736962925178,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ihärdig, enveten',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4Wq92',
    created: 1736962926431,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omfattande, fullständig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pyk44',
    created: 1736962927402,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'förtjusande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4o1FI',
    created: 1736962928430,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillbakadragen, diskret',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_Unl9',
    created: 1736962929637,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dZaEh',
    created: 1736962931432,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: '',
      example: '',
      definition: '',
      translation: 'betydelsefull, meningsfull',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
