import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'o3CgN',
    created: 1736963233241,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tính toàn vẹn',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YauW9',
    created: 1736963234165,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'khả năng chống chịu',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xRzqQ',
    created: 1736963236154,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ngưỡng, bậc cửa, đoạn cuối',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Gxz8x',
    created: 1736963236975,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sự sắp xếp, sự chỉ định',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ES8sl',
    created: 1736963237765,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tác động, hệ quả',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S86ly',
    created: 1736963239191,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kết quả, sản phẩm',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VR8Vd',
    created: 1736963240855,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'công nhận, thừa nhận',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vx_FO',
    created: 1736963243435,
    data: {
      language: 'de',
      source: 'halten',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cầm, giữ, để lại',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-DmoV',
    created: 1736963245195,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dành cho, tặng cho',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RJtuS',
    created: 1736963246017,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'biện minh, bào chữa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zw365',
    created: 1736963250550,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sự bỏ bê',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1H-Na',
    created: 1736963252254,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'thuyết phục',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TNWfz',
    created: 1736963254022,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dần dần',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n1xAc',
    created: 1736963255453,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ngầm',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9xnYG',
    created: 1736963256260,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'trước hết, trên hết',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0u0ka',
    created: 1736963257813,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ngay lập tức, liền',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zdpxb',
    created: 1736963259964,
    data: {
      language: 'de',
      source: 'rund',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tròn, bầu, mềm mại',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '50G56',
    created: 1736963261908,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'đủ, điểm trung bình',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SLPLK',
    created: 1736963263304,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bền bỉ, kiên trì',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HBDy2',
    created: 1736963264881,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'toàn diện, bao quát',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WhbAG',
    created: 1736963265993,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'đáng yêu, dễ thương',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DjiIt',
    created: 1736963267574,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kín đáo, nhẹ nhàng',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0SrJA',
    created: 1736963269131,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'miễn cưỡng',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MRkAB',
    created: 1736963270610,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: '',
      example: '',
      definition: '',
      translation: 'quan trọng, có ý nghĩa',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
