import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'PqtfB',
    created: 1736959621798,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriti, keseluruhan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'a91QV',
    created: 1736959623597,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'daya tahan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EzPdz',
    created: 1736959625642,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ambang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wBXwY',
    created: 1736959628199,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sikap',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fhpDu',
    created: 1736959630155,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kesan, reaksi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eYkVT',
    created: 1736959631785,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YYPof',
    created: 1736959634040,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengakui, menghargai, menjawab',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CI3uO',
    created: 1736959635992,
    data: {
      language: 'en',
      source: 'consider',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mempertimbangkan, menganggap, memandang',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tyCGk',
    created: 1736959638140,
    data: {
      language: 'en',
      source: 'devote',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengabdikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xSmlb',
    created: 1736959639994,
    data: {
      language: 'en',
      source: 'justify',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membenarkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0dfHD',
    created: 1736959641925,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: '',
      example: '',
      definition: '',
      translation: 'abaikan, mengabaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tuMaT',
    created: 1736959643328,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'memujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A0nlF',
    created: 1736959645308,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara beransur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dgy6g',
    created: 1736959647036,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tersirat, tidak diragukan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'byAx_',
    created: 1736959648962,
    data: {
      language: 'en',
      source: 'notably',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terutama, secara ketara',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QQijP',
    created: 1736959651078,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'segera, cepat',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HjDWV',
    created: 1736959653061,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kira-kira, kasar, secara kasar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mno0P',
    created: 1736959655613,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup, secukupnya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eDFdN',
    created: 1736959657835,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berterusan, kekal',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vP26U',
    created: 1736959660358,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menyeluruh',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YIL2s',
    created: 1736959663204,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menyenangkan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5SX3r',
    created: 1736959665077,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berhati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BPCcW',
    created: 1736959666817,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'enggan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UUZsZ',
    created: 1736959668785,
    data: {
      language: 'en',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikan, penting',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
