import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '35F68',
    created: 1736959103174,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integritet, helhet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4qQs9',
    created: 1736959104331,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motstandskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EHmbk',
    created: 1736959105865,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terskel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r_jfM',
    created: 1736959107260,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposisjon',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'np_Rw',
    created: 1736959109359,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ettervirkning, tilbakevirkning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gs6Zj',
    created: 1736959110677,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: '',
      example: '',
      definition: '',
      translation: 'utfall',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QSs-w',
    created: 1736959111533,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkjenne, anerkjenne, bekrefte',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fYRuC',
    created: 1736959112620,
    data: {
      language: 'en',
      source: 'consider',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vurdere, betrakte, tenke på',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xiEsG',
    created: 1736959113738,
    data: {
      language: 'en',
      source: 'devote',
      ipa: '',
      example: '',
      definition: '',
      translation: 'å vie',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xTRAD',
    created: 1736959115065,
    data: {
      language: 'en',
      source: 'justify',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rettferdiggjøre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FSFpm',
    created: 1736959116412,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsømmelse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0VCic',
    created: 1736959117789,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GC0Lj',
    created: 1736959121505,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qg0vL',
    created: 1736959122882,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implisitt, underforstått',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1_aAq',
    created: 1736959124281,
    data: {
      language: 'en',
      source: 'notably',
      ipa: '',
      example: '',
      definition: '',
      translation: 'merkbart, særlig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tJtpp',
    created: 1736959125492,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umiddelbart, snart',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '92Kir',
    created: 1736959126654,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omtrent, grovt, ufullstendig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dYQv8',
    created: 1736959128180,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tilstrekkelig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sV8XJ',
    created: 1736959129064,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vedvarende, utholdende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZOPfp',
    created: 1736959133604,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omfattende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gRIbX',
    created: 1736959134976,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: '',
      example: '',
      definition: '',
      translation: 'herlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ycLQG',
    created: 1736959138286,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsiktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tizdp',
    created: 1736959139565,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kLBwd',
    created: 1736959140690,
    data: {
      language: 'en',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'betydelig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
