import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'H8QRb',
    created: 1736958833371,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriteit, eenheid',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5tocH',
    created: 1736958837259,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'veerkracht',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3Jgks',
    created: 1736958839108,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: '',
      example: '',
      definition: '',
      translation: 'drempel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7UDvX',
    created: 1736958841357,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dispositie',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yvzX5',
    created: 1736958844375,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nasleep, terugslag',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gag8F',
    created: 1736958846251,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uitkomst',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Uc5V7',
    created: 1736958848632,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkennen, erkenning geven, bevestigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uv3-l',
    created: 1736958850537,
    data: {
      language: 'en',
      source: 'consider',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overwegen, beschouwen, rekening houden met',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oX_xI',
    created: 1736958852980,
    data: {
      language: 'en',
      source: 'devote',
      ipa: '',
      example: '',
      definition: '',
      translation: 'toewijden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ePjmI',
    created: 1736958854927,
    data: {
      language: 'en',
      source: 'justify',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtvaardigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pE4x2',
    created: 1736958857573,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verwaarlozing',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'viAup',
    created: 1736958859217,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overtuigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GLUZk',
    created: 1736958861424,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geleidelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FtOmj',
    created: 1736958862945,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'impliciet, onbetwist',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dPxfF',
    created: 1736958864813,
    data: {
      language: 'en',
      source: 'notably',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bijzonder, opmerkelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ndlld',
    created: 1736958867190,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'onmiddellijk, prompt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P6oCZ',
    created: 1736958869113,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ongeveer, ruw, grof',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'w4_oD',
    created: 1736958870953,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voldoende',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6ggPr',
    created: 1736958872504,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistent, volhardend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rQr8k',
    created: 1736958874883,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uitgebreid',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0h0AM',
    created: 1736958876884,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verrukkelijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fL9Av',
    created: 1736958878629,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'w62q5',
    created: 1736958880347,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'onwillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DyNdn',
    created: 1736958882620,
    data: {
      language: 'en',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
