import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'fqk0N',
    created: 1736958622423,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: '',
      example: '',
      definition: '',
      translation: 'целостность, доброта',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'USUDu',
    created: 1736958625092,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'устойчивость',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mvcof',
    created: 1736958627185,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: '',
      example: '',
      definition: '',
      translation: 'порог',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3nxXK',
    created: 1736958628980,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'расположение',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Xwwiq',
    created: 1736958631142,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'последствие, отдача',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4mM3C',
    created: 1736958632959,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: '',
      example: '',
      definition: '',
      translation: 'результат',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CTCDl',
    created: 1736958635297,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: '',
      example: '',
      definition: '',
      translation: 'признавать, признавать наличие, ответить на',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aQcD4',
    created: 1736958637209,
    data: {
      language: 'en',
      source: 'consider',
      ipa: '',
      example: '',
      definition: '',
      translation: 'рассматривать, учитывать, обдумывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NkWd4',
    created: 1736958639445,
    data: {
      language: 'en',
      source: 'devote',
      ipa: '',
      example: '',
      definition: '',
      translation: 'посвящать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '415Mv',
    created: 1736958641142,
    data: {
      language: 'en',
      source: 'justify',
      ipa: '',
      example: '',
      definition: '',
      translation: 'оправдывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Vgkdp',
    created: 1736958643103,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: '',
      example: '',
      definition: '',
      translation: 'пренебрежение',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JeOqS',
    created: 1736958645373,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'убедить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lzWoS',
    created: 1736958646999,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KB7J0',
    created: 1736958649061,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неявный, подразумеваемый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lSN-6',
    created: 1736958651021,
    data: {
      language: 'en',
      source: 'notably',
      ipa: '',
      example: '',
      definition: '',
      translation: 'заметно, особенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FDEiu',
    created: 1736958653461,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'незамедлительно, сразу после',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VAKFf',
    created: 1736958655762,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: '',
      example: '',
      definition: '',
      translation: 'примерно, грубо, неаккуратно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kN6NB',
    created: 1736958657805,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достаточно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'u6Pj6',
    created: 1736958659695,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'упорный, настойчивый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7dnBf',
    created: 1736958661594,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: '',
      example: '',
      definition: '',
      translation: 'всесторонний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pydu6',
    created: 1736958663621,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: '',
      example: '',
      definition: '',
      translation: 'восхитительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GrzZ7',
    created: 1736958670881,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: '',
      example: '',
      definition: '',
      translation: 'осторожный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I5EAR',
    created: 1736958673051,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неохотный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DVyA9',
    created: 1736958674633,
    data: {
      language: 'en',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'значительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
