import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'u0uBA',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛɡrɪti',
      example:
        "* She is known for her integrity.\n* The building's integrity was compromised.",
      definition:
        '* adherence to moral and ethical principles; soundness of moral character\n* the state of being whole, entire, or undiminished',
      translation: 'ايمانداري, سچائي, ديانت, اُصوليّت',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'x1v2B',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪliəns',
      example:
        "* She showed great resilience in the face of adversity.\n* The material's resilience makes it ideal for shock absorption.",
      definition:
        '* The capacity to recover quickly from difficulties; toughness.\n* The ability of a substance or object to spring back into shape; elasticity.',
      translation: 'مزاحمت, لچڪ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'JzaiU',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃˌhoʊld',
      example:
        '* He stood on the threshold of his career.\n* She paused on the threshold.',
      definition:
        '* The point or level at which something begins or changes\n* A strip of wood, metal, or stone forming the bottom of a doorway and crossed in entering a house or room',
      translation: 'حد, دروازو',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'twZtm',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example:
        '* She has a cheerful disposition.\n* A disposition to avoid conflicts.\n* The disposition of troops.',
      definition:
        "* a person's inherent qualities of mind and character\n* an inclination or tendency of a particular kind\n* the action of arranging or ordering",
      translation: 'رويو, مزاج, فطرت',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'BMDjf',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpərˈkʌʃən',
      example:
        '* The decision had serious repercussions.\n* Economic repercussions were felt worldwide.',
      definition:
        'an unintended consequence occurring some time after an event or action',
      translation: 'نتيجو, اثر',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'kwj_A',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example:
        '* The outcome was unexpected.\n* A positive outcome is desired.',
      definition: 'a result or effect of an action, situation, or event',
      translation: 'نتيجو, پيدائش',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'zJBW6',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'əkˈnɒl.ɪdʒ',
      example:
        "* She acknowledged her team's effort.\n* He acknowledged the mistake.\n* I acknowledge this receipt.",
      definition:
        'to accept, admit, or recognize something, or the truth or existence of something',
      translation: 'مڃڻ, تسليم ڪرڻ, قبول ڪرڻ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'b0K8_',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example: '* She considered the offer.\n* They considered him a friend.',
      definition:
        '* to think carefully about something, typically before making a decision\n* to regard someone or something in a particular way',
      translation: 'غور ڪريو, سوچيو',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '7D2RD',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example:
        '* She devotes her time to charity.\n* He devotes effort to research.',
      definition:
        "to give one's time, effort, or attention earnestly to a particular activity or purpose",
      translation: 'وقف, ارپڻ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Uwmxr',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstɪfaɪ',
      example: '* Justify your decision.\n* Can you justify the expense?',
      definition:
        '* show or prove to be right or reasonable\n* give a good reason for',
      translation: 'جواز ڏيڻ, سند ڏيڻ, ثابت ڪرڻ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'szHOc',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈɡlɛkt',
      example: '* neglected the garden\n* neglect your duties',
      definition:
        '* fail to care for properly\n* omit or disregard intentionally',
      translation: 'وسارڻ, نظرانداز ڪرڻ, لاپرواهي ڪرڻ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '7RFGE',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example:
        '* She persuaded him to join\n* They persuaded me with their argument',
      definition:
        '* To cause someone to do something through reasoning or argument\n* To convince someone to believe something',
      translation: 'قائل ڪرڻ, سمجهائڻ, رضامند ڪرڻ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'wpE5q',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈɡrædʒ.u.ə.li',
      example:
        '* The plant grew gradually\n* He spoke more confidently gradually',
      definition: '* In a gradual manner\n* Little by little',
      translation: 'وٺندي, آهستي آهستي, تدريجي طور تي',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'iPrTg',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'implicitly',
      ipa: 'ɪmˈplɪsɪtli',
      example: '* She implicitly agreed.\n* He trusted her implicitly.',
      definition: 'in a way that is not directly expressed; tacitly',
      translation: 'اڻسڌي طرح, اڻڄاڻائي سان',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'g190p',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: '* He is notably absent.\n* The event was notably successful.',
      definition:
        '* in a way that is striking or remarkable\n* especially or particularly',
      translation: 'خاص طور تي, نمايان طور تي',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'wDuiY',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'ˈprɒmptli',
      example:
        '* he arrived promptly at 9 am\n* reply promptly to the invitation',
      definition:
        '* with little or no delay\n* immediately or without hesitation',
      translation: 'فوراً, جلدي',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'B0_kQ',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* The population increased roughly by 20,000.\n* He pushed the chair roughly aside.\n* Roughly speaking, it's a two-hour drive.",
      definition:
        '* approximately but not exactly\n* without being gentle or careful\n* in a manner lacking precision or detail',
      translation: 'لڳ ڀڳ, تقريباً, اندازاً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Mo0D9',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example:
        '* He was sufficiently prepared.\n* The work was sufficiently detailed.',
      definition: 'to an adequate degree; enough',
      translation: 'ڪافي, پوري طرح',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'zQgux',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example: '* persistent effort\n* persistent rain',
      definition:
        '* continuing firmly or obstinately despite difficulty or opposition\n* lasting for a long time or longer than expected',
      translation: 'مسلسل, مستقل, پائيدار',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'YSl8b',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example:
        '* A comprehensive review was conducted.\n* They made a comprehensive list.',
      definition:
        'Thoroughly covering all or nearly all elements or aspects of something.',
      translation: 'جامع, مڪمل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Rgl3I',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfʊl',
      example: '* a delightful book\n* delightful weather',
      definition: 'Causing great pleasure or delight.',
      translation: 'دلڪش, خوشگوار, پُر مسرت',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'mqPcS',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔːʃəs',
      example: '* cautious driver\n* cautious approach',
      definition:
        '* careful to avoid potential problems or dangers\n* prudent in action or decision',
      translation: 'محتاط, خبردار',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3yLK0',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: '* Reluctant to answer.\n* She was reluctant to agree.',
      definition: 'Unwilling and hesitant; disinclined.',
      translation: 'هچڪچائيندڙ, بيزار',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'oc3Iq',
    created: 1764155774036,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪɡˈnɪf.ɪ.kənt',
      example: '* significant improvement\n* significant impact',
      definition:
        '* important and meaningful\n* notable or large enough to make a difference',
      translation: 'اهم, معني خيز, نمايان',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
