import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '3GmRb',
    created: 1736958467995,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: '',
      example: '',
      definition: '',
      translation: '诚信, 完整性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U1J6M',
    created: 1736958469939,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: '',
      example: '',
      definition: '',
      translation: '韧性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IbaET',
    created: 1736958473170,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: '',
      example: '',
      definition: '',
      translation: '门槛',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '48ay1',
    created: 1736958475654,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: '性格, 性情',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VqeDa',
    created: 1736958478028,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: '影响, 反响',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_jLal',
    created: 1736958480353,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: '',
      example: '',
      definition: '',
      translation: '结果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Bk4Qr',
    created: 1736958483234,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: '',
      example: '',
      definition: '',
      translation: '承认, 认可, 回复',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CpSL9',
    created: 1736958484833,
    data: {
      language: 'en',
      source: 'consider',
      ipa: '',
      example: '',
      definition: '',
      translation: '考虑, 思考',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wjPNl',
    created: 1736958487248,
    data: {
      language: 'en',
      source: 'devote',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉献, 致力于',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NaQPi',
    created: 1736958489101,
    data: {
      language: 'en',
      source: 'justify',
      ipa: '',
      example: '',
      definition: '',
      translation: '证明, 辩护',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'V5Sa6',
    created: 1736958490654,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽视, 疏忽',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8GQG_',
    created: 1736958496374,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: '',
      example: '',
      definition: '',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HyWjv',
    created: 1736958498533,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐渐',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-bKF6',
    created: 1736958500887,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '隐含的, 内在的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ccVLo',
    created: 1736958502682,
    data: {
      language: 'en',
      source: 'notably',
      ipa: '',
      example: '',
      definition: '',
      translation: '显著地, 特别地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4Zx3p',
    created: 1736958504729,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: '',
      example: '',
      definition: '',
      translation: '及时, 立刻',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6GawV',
    created: 1736958506834,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: '',
      example: '',
      definition: '',
      translation: '大致, 粗暴, 粗糙',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3GWkO',
    created: 1736958509628,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够地, 充分地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xyEMM',
    created: 1736958511550,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: '',
      example: '',
      definition: '',
      translation: '持续的, 坚持不懈的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ax0T1',
    created: 1736958514765,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: '',
      example: '',
      definition: '',
      translation: '全面的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'No0dy',
    created: 1736958517295,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快的, 令人愉快的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OSw9w',
    created: 1736958519126,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: '',
      example: '',
      definition: '',
      translation: '谨慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1FLWj',
    created: 1736958520759,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情愿',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BNUfb',
    created: 1736958522658,
    data: {
      language: 'en',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的, 显著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
