import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'm7jBY',
    created: 1736959889985,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EzsT-',
    created: 1736959890134,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliencia',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5OlQr',
    created: 1736959890316,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2NMv5',
    created: 1736959890481,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QHi1i',
    created: 1736959890619,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fl5hR',
    created: 1736959890824,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dEzoY',
    created: 1736959890988,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ETuNm',
    created: 1736959891210,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1S57X',
    created: 1736959891360,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9KQEK',
    created: 1736959891525,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WQlgV',
    created: 1736959891668,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S4sTA',
    created: 1736959891830,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nRw9c',
    created: 1736959891981,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YFAOj',
    created: 1736959892151,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HYBSi',
    created: 1736959892830,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FKREM',
    created: 1736959893092,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zpA8x',
    created: 1736959893311,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nRoVL',
    created: 1736959893450,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QJAxS',
    created: 1736959893593,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lzys1',
    created: 1736959893727,
    data: {
      language: 'es',
      source: 'integral',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0Opw-',
    created: 1736959893891,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SoS1I',
    created: 1736959894044,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Im0ZI',
    created: 1736959894204,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dPKxP',
    created: 1736959894375,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
