import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '-8DSP',
    created: 1736960710909,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تمامیت',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fMEEu',
    created: 1736960713274,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تاب آوری',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'T0RZd',
    created: 1736960716781,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حد, مرز',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7oPOP',
    created: 1736960718270,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ترتیب, استعداد, حال',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5wATw',
    created: 1736960719690,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تأثیر, پخش عمومی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yoiKR',
    created: 1736960725537,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نتیجه, خروجی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7TyKr',
    created: 1736960727881,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شناسایی, بررسی, پذیرفتن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CZQRz',
    created: 1736960730296,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'در نظر گرفتن, تفکر کردن, قضاوت کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'saw0s',
    created: 1736960732080,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقدیم کردن, اختصاص دادن, صرف کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eIn5u',
    created: 1736960733721,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'توجیه کردن, اثبات کردن, تنظیم متن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iRyrP',
    created: 1736960735503,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بی‌توجهی, سهل‌انگاری, بی‌نظمی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '695ty',
    created: 1736960736960,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'متقاعد کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '24c3D',
    created: 1736960738617,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به تدریج',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EiX1y',
    created: 1736960744869,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به طور ضمنی',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M5ftK',
    created: 1736960746455,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به‌طور قابل توجهی',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '03-u0',
    created: 1736960748100,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'فوراً, بلافاصله',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I1hNX',
    created: 1736960750000,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به‌سختی, فقط',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SyrAw',
    created: 1736960752256,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به اندازه کافی',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-5B1x',
    created: 1736960758118,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'پایدار, مداوم',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PSatV',
    created: 1736960759478,
    data: {
      language: 'es',
      source: 'integral',
      ipa: '',
      example: '',
      definition: '',
      translation: 'کامل, سبوس‌دار, آرد کامل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-lwrN',
    created: 1736960762206,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: '',
      example: '',
      definition: '',
      translation: 'دلنشین',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dMu3d',
    created: 1736960763927,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'محتاط, پیش‌بینی‌کننده',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'E5LH9',
    created: 1736960765433,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مخالف',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bfL-E',
    created: 1736960767302,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مهم, معنادار',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
