import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'q3AFV',
    created: 1736959896168,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: '',
      example: '',
      definition: '',
      translation: "l'intégrité",
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uyr1j',
    created: 1736959897478,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'résilience',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MdOn-',
    created: 1736959899287,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'limite',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XkLLn',
    created: 1736959901225,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: "la disposition, l'état d'esprit",
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JshSN',
    created: 1736959902848,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: '',
      example: '',
      definition: '',
      translation: 'répercussion, impact',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oDlnb',
    created: 1736959904519,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'le résultat, conséquence',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G9Plu',
    created: 1736959909653,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconnaître, considérer, admettre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ItdF7',
    created: 1736959912674,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considérer, prendre en compte, évaluer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6GuXZ',
    created: 1736959914904,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'consacrer, décerner, employer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 't1zsv',
    created: 1736959916857,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justifier, rendre adéquat, aligner le texte',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'skjOZ',
    created: 1736959918252,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'négligence, inattention, désordre',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4Zg6y',
    created: 1736959919868,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuader',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iyERt',
    created: 1736959921248,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'graduellement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NX9E6',
    created: 1736959922730,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2jWJy',
    created: 1736959923508,
    data: {
      language: 'es',
      source: 'notablement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notablement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xz-q4',
    created: 1736959925030,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'immédiatement, tout de suite',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'l8ykS',
    created: 1736959926515,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: '',
      example: '',
      definition: '',
      translation: 'à peine, juste',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W8pTy',
    created: 1736959928766,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suffisamment',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Sf7IL',
    created: 1736959930439,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistant, durable',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4k5S1',
    created: 1736959931772,
    data: {
      language: 'es',
      source: 'integral',
      ipa: '',
      example: '',
      definition: '',
      translation: 'intégral, complet',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eXs09',
    created: 1736959933858,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: '',
      example: '',
      definition: '',
      translation: 'charmant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pQLd1',
    created: 1736959935417,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prudent, préventif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JoZSA',
    created: 1736959936861,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: '',
      example: '',
      definition: '',
      translation: 'réticent',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'blSjK',
    created: 1736959939368,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significatif, significative',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
