import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'oqu4b',
    created: 1736960179246,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: '',
      example: '',
      definition: '',
      translation: "l'integrità",
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lZ27H',
    created: 1736960180339,
    data: {
      language: 'es',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resilienza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nEcKg',
    created: 1736960182713,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'il limite',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v4mtR',
    created: 1736960186174,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposizione',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P49Q9',
    created: 1736960187760,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ripercussione, influenza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '11TRo',
    created: 1736960190584,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: "il risultato, l'effetto",
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wzMwK',
    created: 1736960192615,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riconoscere, considerare, ammettere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VEQS2',
    created: 1736960194220,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerare, tenere in considerazione, giudicare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9VZDe',
    created: 1736960195579,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicare, consacrare, impiegare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yVT4Z',
    created: 1736960197251,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'giustificare, dimostrare, allineare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Dl37n',
    created: 1736960198970,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'distrazione, negligenza, trascuratezza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nvgI6',
    created: 1736960200418,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuadere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XxU63',
    created: 1736960201904,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P89Vy',
    created: 1736960203348,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TTTpk',
    created: 1736960204722,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notevolmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RylrZ',
    created: 1736960206189,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'immediatamente, subito',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3R_QE',
    created: 1736960208073,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: '',
      example: '',
      definition: '',
      translation: 'appena, quasi nulla',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gInIV',
    created: 1736960209162,
    data: {
      language: 'es',
      source: 'sufficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficientemente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oDu8c',
    created: 1736960210591,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente, tenace',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DlKlE',
    created: 1736960212436,
    data: {
      language: 'es',
      source: 'integral',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integrale, completo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0rmHE',
    created: 1736960214556,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: '',
      example: '',
      definition: '',
      translation: 'incantevole',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9IVh4',
    created: 1736960216064,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prudenti, cauteloso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'meO01',
    created: 1736960217728,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riluttante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Y_zsd',
    created: 1736960219261,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significativo, importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
