import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZyLtb',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: 'inteɣɾiˈðað',
      example: '* Actuar con integridad\n* Mantener la integridad del sistema',
      definition:
        '* Cualidad de íntegro\n* Estado de lo que está completo o no ha sido alterado',
      translation: 'សេចក្តីស្មោះត្រង់, ភាពទៀងត្រង់',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'pWXth',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'la resiliencia',
      ipa: 'resiˈljenθja',
      example:
        '* La resiliencia es clave en tiempos de crisis.\n* El acero tiene alta resiliencia.',
      definition:
        '* Capacidad de adaptación de un ser vivo frente a un agente perturbador o un estado o situación adversos.\n* Capacidad de un material elástico para absorber y almacenar energía de deformación.',
      translation: 'ការស្ទាក់ស្ទើរ, ការស្ទន់ស្ទើរ',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '9Zf4D',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: 'ˈlimite',
      example:
        '* El límite de velocidad es 80 km/h.\n* Cruzó el límite de la propiedad.\n* Alcanzó su límite de paciencia.',
      definition:
        '* Línea real o imaginaria que marca el fin de una superficie o cuerpo.\n* Extremo que no se debe o no se puede sobrepasar.\n* Cantidad máxima o mínima que se permite.',
      translation: 'ដែនកំណត់, ព្រំដែន',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '4fBWd',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: 'dispoˈθjon',
      example:
        '* Tiene buena disposición para aprender.\n* La disposición de los muebles es importante.\n* Está a disposición del público.',
      definition:
        '* Acción y efecto de disponer.\n* Inclinación natural hacia algo.\n* Ordenación de las cosas en un lugar.\n* Facultad o capacidad para hacer algo.',
      translation: 'ការរៀបចំ, ការត្រៀម, អាកប្បកិរិយា, ចរិត',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '8zSzb',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: 'repeɾkuˈsjon',
      example:
        '* La noticia tuvo gran repercusión\n* Las repercusiones del evento fueron significativas',
      definition:
        '* Consecuencia o efecto de un hecho o acción\n* Resonancia o impacto que algo tiene en un contexto determinado',
      translation: 'ផលប៉ះពាល់, ឥទ្ធិពល',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'CDjYc',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: 'resulˈtado',
      example:
        '* El resultado fue inesperado.\n* Calcula el resultado de la suma.',
      definition:
        '* Efecto o consecuencia de un hecho, operación o deliberación.\n* Lo que se obtiene al resolver un problema matemático.',
      translation: 'លទ្ធផល, ផល, ចុងក្រោយ',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3OLg4',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: 'rekonoˈθeɾ',
      example:
        '* Reconoció su error.\n* No lo pude reconocer.\n* Reconocieron su esfuerzo.',
      definition:
        '* Distinguir o identificar a una persona o cosa entre varias por una serie de características propias.\n* Aceptar o admitir la verdad o existencia de algo.\n* Agradecer o mostrar gratitud por un favor o servicio recibido.',
      translation: 'ស្គាល់, ទទួលស្គាល់',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'LPWEX',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: 'kon.si.ðeˈɾaɾ',
      example:
        '* Considerar una propuesta\n* Considerar las consecuencias\n* Considerar necesario',
      definition:
        '* Pensar detenidamente sobre algo\n* Tener en cuenta\n* Juzgar o estimar',
      translation: 'ពិចារណា, គិត',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'CxCtX',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: 'deðiˈkaɾ',
      example: '* Dedico este libro a mis padres.\n* Se dedica a la enseñanza.',
      definition:
        '* Consagrar o destinar algo a un fin determinado\n* Ofrecer una obra o acción a alguien como muestra de respeto o afecto',
      translation: 'ឧទ្ទិស, ប្តេជ្ញា, ផ្តោត, ចំណាយ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '_mCdN',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: 'xus.ti.fiˈkaɾ',
      example:
        '* No pudo justificar su ausencia\n* Justificó su decisión con argumentos sólidos',
      definition:
        '* Probar algo con razones convincentes\n* Demostrar la inocencia de alguien\n* Dar razones para explicar un comportamiento',
      translation: 'បញ្ជាក់, ពន្យល់',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jMal-',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: 'desˈkwiðo',
      example: '* Cometió un descuido\n* Fue un descuido involuntario',
      definition:
        '* Falta de atención o cuidado\n* Negligencia en el cumplimiento de una obligación',
      translation: 'ការធ្វេសប្រហែស, ការមិនប្រុងប្រយ័ត្ន',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'tj3vP',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: 'peɾswaˈðiɾ',
      example: '* Persuadir a un amigo\n* Persuadir con argumentos',
      definition: 'Inducir a alguien con razones a hacer o creer algo',
      translation: 'បញ្ចុះបញ្ចូល, បញ្ចុះបញ្ចូលបាន',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'yX0T7',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: 'ɡɾaðwaˈmente',
      example: '* El clima cambia gradualmente.\n* Mejoró gradualmente.',
      definition: '* De manera gradual\n* Poco a poco',
      translation: 'តិចតួច, បន្តិចម្ដងៗ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Pkica',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: 'imˈplisitamente',
      example: '* Aceptó implícitamente\n* Entendió implícitamente',
      definition: '* De manera implícita\n* Sin expresarlo directamente',
      translation: 'ដោយប្រយោល, ដោយលាក់លៀម',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'ThATR',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: 'notaˈβlemen̪te',
      example: '* Mejoró notablemente\n* Se destacó notablemente',
      definition:
        '* De manera notable o destacada\n* Con distinción o relevancia',
      translation: 'យ៉ាងច្បាស់, យ៉ាងច្រើន',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '_wwgv',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: 'inmeðjaˈtamen̪te',
      example: '* Llegó inmediatamente\n* Responde inmediatamente',
      definition: '* Sin demora\n* En el acto',
      translation: 'ភ្លាម, ភ្លាមៗ, ភ្លាមៗនោះ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'JwZhg',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* Apenas llegué, comenzó a llover.\n* Apenas se ve en la oscuridad.',
      definition: '* Casi no\n* Con dificultad\n* Tan pronto como',
      translation: 'ទើបតែ, ស្ទើរតែ, មិនសូវ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'njSiB',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: 'su.fi.θjen.teˈmen.te',
      example: '* Está suficientemente claro.\n* Habló suficientemente alto.',
      definition: 'En cantidad o grado suficiente',
      translation: 'គ្រប់គ្រាន់, ពេញលេញ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'mimmF',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: 'peɾ.siˈsten.te',
      example: '* Es un trabajador persistente.\n* La lluvia fue persistente.',
      definition:
        '* Que persiste o se mantiene firme en algo.\n* Que dura mucho tiempo.',
      translation: 'ជាប់ជានិច្ច, អចិន្រ្តៃយ៍',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'zJgQY',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'integral',
      ipa: 'inteˈɡɾal',
      example: '* parte integral\n* visión integral',
      definition: '* Que forma parte de un todo\n* Completo, total',
      translation: 'សរុប, ពេញលេញ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'a1mbR',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: 'enkanˈtadoɾ',
      example: '* Un paisaje encantador\n* Una sonrisa encantadora',
      definition: '* Que causa encanto o deleite\n* Agradable o atractivo',
      translation: 'គួរឱ្យចាប់អារម្មណ៍, គួរឱ្យស្រឡាញ់',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'LLEwI',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: 'pɾekaˈβiðo',
      example:
        '* Es muy precavido al cruzar la calle.\n* Siempre es precavido con sus inversiones.',
      definition:
        'Que actúa con precaución y anticipación para evitar posibles problemas o peligros.',
      translation: 'ប្រុងប្រយ័ត្ន, ប្រយ័ត្ន',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'lc5p7',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: 'reˈaθjo',
      example:
        '* Es reacio a cambiar de opinión\n* Se mostró reacio a participar',
      definition:
        '* Que muestra resistencia a hacer algo\n* Poco dispuesto a aceptar o admitir algo',
      translation: 'មិនចង់, មិនពេញចិត្ត',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Cta0a',
    created: 1764156145574,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: 'siɣnifikaˈtiβo',
      example: '* Un cambio significativo\n* Un gesto significativo',
      definition:
        '* Que tiene significado o importancia\n* Que expresa o manifiesta algo',
      translation: 'សំខាន់, មានន័យ',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
