import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'XXB1h',
    created: 1736959994086,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: '',
      example: '',
      definition: '',
      translation: '完整性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'khPXA',
    created: 1736959994870,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: '韧性, 适应力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z4Myd',
    created: 1736959996477,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: '',
      example: '',
      definition: '',
      translation: '界限, 限制',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O0uhO',
    created: 1736959998261,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: '安排, 性格, 状态',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7uKCC',
    created: 1736959999817,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: '',
      example: '',
      definition: '',
      translation: '影响, 影响力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jsKLm',
    created: 1736960005443,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: '结果, 成果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uV1IJ',
    created: 1736960007055,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: '',
      example: '',
      definition: '',
      translation: '认出, 承认',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K85BB',
    created: 1736960008929,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: '考虑, 考虑到, 评估',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pKMEj',
    created: 1736960010539,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉献, 致敬, 专用',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qvp6n',
    created: 1736960012397,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: '证明, 辩护, 对齐',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OnXLN',
    created: 1736960015419,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: '',
      example: '',
      definition: '',
      translation: '疏忽, 失误, 不修边幅',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_q_2G',
    created: 1736960017303,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TOtnS',
    created: 1736960022196,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐渐',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '32K01',
    created: 1736960023716,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '隐含地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dPLL_',
    created: 1736960025489,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '显著地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DFJZN',
    created: 1736960026796,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即, 马上',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U8Oy9',
    created: 1736960028283,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: '',
      example: '',
      definition: '',
      translation: '几乎不, 刚刚',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZAz5c',
    created: 1736960029884,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BawmK',
    created: 1736960031357,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '持久的, 坚持的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1eO-4',
    created: 1736960032880,
    data: {
      language: 'es',
      source: 'integral',
      ipa: '',
      example: '',
      definition: '',
      translation: '全面的, 完整的, 全麦的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'idph5',
    created: 1736960038213,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: '',
      example: '',
      definition: '',
      translation: '迷人',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sn3-u',
    created: 1736960039957,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: '',
      example: '',
      definition: '',
      translation: '谨慎的, 小心的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'udV5m',
    created: 1736960041726,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: '',
      example: '',
      definition: '',
      translation: '抵触的, 反对的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3ij3E',
    created: 1736960043594,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的, 有意义的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
