import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Q0jcL',
    created: 1737102355987,
    data: {
      language: 'fi',
      source: 'eheys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'अखंडता, पूर्णता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sdWj9',
    created: 1737102356797,
    data: {
      language: 'fi',
      source: 'joustavuutta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लचीलापन',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DGggG',
    created: 1737102357667,
    data: {
      language: 'fi',
      source: 'kynnys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'कदम, सीमा',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'J0z-f',
    created: 1737102358393,
    data: {
      language: 'fi',
      source: 'taipumus',
      ipa: '',
      example: '',
      definition: '',
      translation: 'झुकाव, प्रवृत्ति',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3gko6',
    created: 1737102359327,
    data: {
      language: 'fi',
      source: 'jälkivaikutusta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पश्चात प्रभाव',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A-ce8',
    created: 1737102360304,
    data: {
      language: 'fi',
      source: 'tulokset',
      ipa: '',
      example: '',
      definition: '',
      translation: 'परिणाम, नतीजे',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-Ip8F',
    created: 1737102361082,
    data: {
      language: 'fi',
      source: 'tunnustaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'स्वीकृत करना, मान लेना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7Cto2',
    created: 1737102361686,
    data: {
      language: 'fi',
      source: 'harkita',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विचार करना, सोचना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '509FS',
    created: 1737102362557,
    data: {
      language: 'fi',
      source: 'omistautua',
      ipa: '',
      example: '',
      definition: '',
      translation: 'समर्पित होना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LNkMi',
    created: 1737102363342,
    data: {
      language: 'fi',
      source: 'perustella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सिद्ध करना, व्याख्या करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wbhVI',
    created: 1737102363898,
    data: {
      language: 'fi',
      source: 'laiminlyödä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'उपेक्षा करना, नज़रअंदाज़ करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6z7rf',
    created: 1737102364501,
    data: {
      language: 'fi',
      source: 'suostutella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'मनाना, राजी करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dNEUG',
    created: 1737102365078,
    data: {
      language: 'fi',
      source: 'vähitellen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'धीरे-धीरे',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YZ-Cx',
    created: 1737102365833,
    data: {
      language: 'fi',
      source: 'epäsuorasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'अप्रत्यक्ष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xS6h-',
    created: 1737102366664,
    data: {
      language: 'fi',
      source: 'erityisesti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विशेष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Lr1yA',
    created: 1737102367453,
    data: {
      language: 'fi',
      source: 'viipymättä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'तुरंत, बिना देरी',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cRqWN',
    created: 1737102368158,
    data: {
      language: 'fi',
      source: 'karkeasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'क粗粗, सामान्यत:',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CUlR2',
    created: 1737102368806,
    data: {
      language: 'fi',
      source: 'riittävästi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पर्याप्त, काफी',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'd-puG',
    created: 1737102369363,
    data: {
      language: 'fi',
      source: 'jatkuvaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'निरंतर, लगातार',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PUcA7',
    created: 1737102370152,
    data: {
      language: 'fi',
      source: 'kattava',
      ipa: '',
      example: '',
      definition: '',
      translation: 'व्यापक, सम्पूर्ण',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4IaPe',
    created: 1737102370761,
    data: {
      language: 'fi',
      source: 'ihana',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सुंदर, अद्भुत',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'EkxJP',
    created: 1737102371700,
    data: {
      language: 'fi',
      source: 'varovainen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सावधान, सतर्क',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HgxjL',
    created: 1737102372328,
    data: {
      language: 'fi',
      source: 'vastahakoinen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विरोधी, विरोध करने वाला',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HEfVA',
    created: 1737102372908,
    data: {
      language: 'fi',
      source: 'merkittävä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'महत्वपूर्ण, प्रमुख',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
