import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'jMf7z',
    created: 1736961349139,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Integrität, Ehrlichkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zjsC0',
    created: 1736961350400,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Resilienz',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Kxw_7',
    created: 1736961351413,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Schwelle, Beginn, Grenze',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FNcPf',
    created: 1736961353344,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Anordnung, Fähigkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'soMRm',
    created: 1736961354324,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Echolot, Folge',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DLA4q',
    created: 1736961355366,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Ergebnis, Resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RM-fr',
    created: 1736961356385,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkennen, zugeben, anerkennen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7OqMf',
    created: 1736961357192,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'betrachten, in Betracht ziehen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mUUFx',
    created: 1736961358304,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'widmen, heiligen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vd6Nb',
    created: 1736961359057,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtfertigen, beweisen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sRluS',
    created: 1736961362941,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Nachlässigkeit, Vernachlässigung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lcWld',
    created: 1736961363774,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: '',
      example: '',
      definition: '',
      translation: 'überzeugen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-q881',
    created: 1736961364537,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'schrittweise',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R-J2F',
    created: 1736961366423,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implizit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CeYQK',
    created: 1736961367288,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'insbesondere',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FbbXz',
    created: 1736961368373,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'schnell',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QbLRK',
    created: 1736961369189,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefähr, fast',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wwuYN',
    created: 1736961369974,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ausreichend',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hXmxN',
    created: 1736961372104,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'anhaltend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0TZKq',
    created: 1736961373001,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voll, komplett',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oWeJP',
    created: 1736961373993,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: '',
      example: '',
      definition: '',
      translation: 'köstlich',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm_UBB',
    created: 1736961375033,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vorsichtig, umsichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZYYHl',
    created: 1736961376228,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zögerlich',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nwp-_',
    created: 1736961377129,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bedeutend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
