import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8ogee',
    created: 1736961825309,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rehellisyys, kokonaisuus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Uu0qE',
    created: 1736961826384,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kestävyys',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WFRE3',
    created: 1736961828021,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kynnys, alku, raja',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hzUet',
    created: 1736961830000,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'järjestys, kyky',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tJAzA',
    created: 1736961831493,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kaiunta, seuraus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ua3nz',
    created: 1736961833363,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tulos, informaatio, laskun ratkaisu',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k8nSh',
    created: 1736961835327,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tunnistaa, myöntää, hyväksyä',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K5Yua',
    created: 1736961836352,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'katsella, ottaa huomioon',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yLV6J',
    created: 1736961838145,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omistaa, pyhittää',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gfvlY',
    created: 1736961839754,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: '',
      example: '',
      definition: '',
      translation: 'oikeuttaa, perustella',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WvUTS',
    created: 1736961841899,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: '',
      example: '',
      definition: '',
      translation: 'huolimattomuus, negligenssi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'asJqH',
    created: 1736961843417,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vakuuttaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oaLAI',
    created: 1736961845043,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vähitellen',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4eWi1',
    created: 1736961846865,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'epäsuorasti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8T4nn',
    created: 1736961848274,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erityisesti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oo6Bk',
    created: 1736961850142,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nopeasti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HrXJt',
    created: 1736961850862,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'melkein, noin',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cHt7r',
    created: 1736961852344,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riittävästi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dcTFC',
    created: 1736961855422,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kestävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jypXy',
    created: 1736961857164,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kokonainen, täysi',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ITs9u',
    created: 1736961858679,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: '',
      example: '',
      definition: '',
      translation: 'herkullinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OtDsR',
    created: 1736961860161,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'varovainen, huolellinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NlZ72',
    created: 1736961861716,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'epäilevä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9WFjc',
    created: 1736961863211,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'merkittävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
