import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'jFtgj',
    created: 1736961648130,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ईमानदारी, पूर्णता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wPtE2',
    created: 1736961649006,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लचीलापन, संवेदनशीलता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lIp3K',
    created: 1736961650906,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: '',
      example: '',
      definition: '',
      translation: 'द्वार, शुरुआत, सीमा',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '20HNG',
    created: 1736961654724,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'व्यवस्था, क्षमता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xSEbK',
    created: 1736961656158,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'प्रतिध्वनि, परिणाम',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eK-TJ',
    created: 1736961657770,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'परिणाम, सूचना, हल',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JX3TP',
    created: 1736961659318,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पहचानना, स्वीकृति देना, मान लेना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RQ1KP',
    created: 1736961660144,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'गंभीरता से लेना, विचार करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DLMPt',
    created: 1736961661678,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'समर्पित करना, पवित्र करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vUxrL',
    created: 1736961664991,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सिद्ध करना, व्याख्या करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f7Biu',
    created: 1736961672220,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लापरवाही, अवहेलना',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r0zaH',
    created: 1736961673559,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: '',
      example: '',
      definition: '',
      translation: 'मनाना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'En-Eg',
    created: 1736961675171,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'धीरे-धीरे',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'L45b-',
    created: 1736961676629,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'अप्रत्यक्ष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r6tdM',
    created: 1736961678079,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विशेष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kdLEI',
    created: 1736961679739,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'तेज़ी से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KwsSJ',
    created: 1736961680421,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लगभग, करीब',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hVj6U',
    created: 1736961681747,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पर्याप्त',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JIEpS',
    created: 1736961683360,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'स्थायी',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vJ0WN',
    created: 1736961684805,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पूर्ण, संपूर्ण',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PDt5W',
    created: 1736961686782,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: '',
      example: '',
      definition: '',
      translation: 'स्वादिष्ट',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jWMxN',
    created: 1736961688365,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सावधान, संवेदनशील',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6x0Nd',
    created: 1736961690477,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'संकोची',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NqnfC',
    created: 1736961697681,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'महत्वपूर्ण',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
