import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'HfvB5',
    created: 1736962212138,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ինտեգրիտետ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Sv_xP',
    created: 1736962212938,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հաստատակամություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LAxnv',
    created: 1736962213877,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: '',
      example: '',
      definition: '',
      translation: 'սահման, սահմանագիծ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BdnmV',
    created: 1736962215292,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'կարգավորում, վիճակ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xuJSc',
    created: 1736962216052,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հետադարձություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4BPd1',
    created: 1736962217209,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 't3m_r',
    created: 1736962218131,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ճանաչել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'u-Wg4',
    created: 1736962218999,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համարել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '931Ne',
    created: 1736962219948,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'վճռել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2cUo7',
    created: 1736962221754,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդարացնել, հիմնավորել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G1LgF',
    created: 1736962224925,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անփույթություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's66C-',
    created: 1736962225879,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PhOGT',
    created: 1736962226894,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հետզհետե',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DRhu5',
    created: 1736962227900,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անհայտորեն',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wOHIf',
    created: 1736962228657,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: '',
      example: '',
      definition: '',
      translation: '特别地, 特别是',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'T8g9J',
    created: 1736962229752,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արագ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RzNN7',
    created: 1736962230416,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մոտավորապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5AYhh',
    created: 1736962231404,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'բավական',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vMx1f',
    created: 1736962232706,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համառ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rywUI',
    created: 1736962233773,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'լրիվ, ամբողջ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FwFH-',
    created: 1736962234541,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համեղ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wL4WH',
    created: 1736962235444,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'խելամիտ, զգույշ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IKXzf',
    created: 1736962236384,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հակառակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CEhlB',
    created: 1736962237190,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նշանավոր, նշանակալից',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
