import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'E11Lf',
    created: 1736962129139,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriti, keutuhan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm_Q7U',
    created: 1736962129984,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ketahanan, daya tahan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'y-qK3',
    created: 1736962131753,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ambang, permulaan, had',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1mfKu',
    created: 1736962134871,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'susunan, kemampuan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sY2Nh',
    created: 1736962136203,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reaksi, akibat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lFdb6',
    created: 1736962138223,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil, keputusan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dnGxf',
    created: 1736962139955,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengenali, mengakui, mengakui sebagai sah',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'F-8Jv',
    created: 1736962140971,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ulhzB',
    created: 1736962142753,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menggunakan, menyucikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'arQSE',
    created: 1736962144287,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membuktikan, menjelaskan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '06cxe',
    created: 1736962145934,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kelalaian, kecuaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HEZgk',
    created: 1736962147975,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: '',
      example: '',
      definition: '',
      translation: 'meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qm3Kq',
    created: 1736962149338,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara beransur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wvLsc',
    created: 1736962150794,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara tersirat',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qzAHk',
    created: 1736962152338,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terutamanya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QgxXL',
    created: 1736962153733,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cepat',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OzitV',
    created: 1736962154484,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kira-kira, lebih kurang',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6bGb8',
    created: 1736962156849,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm4NvS',
    created: 1736962158542,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berterusan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Joh56',
    created: 1736962160308,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lengkap, penuh',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nEWIQ',
    created: 1736962161842,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lezat, enak',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZMGRd',
    created: 1736962163858,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berhati-hati, cermat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LkZSG',
    created: 1736962165258,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ragu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p5uum',
    created: 1736962166934,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bermakna',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
