import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '7e03e',
    created: 1737103228905,
    data: {
      language: 'he',
      source: 'שְׁלֵמוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridad, completud',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kOQju',
    created: 1737103230036,
    data: {
      language: 'he',
      source: 'כּוֹשֵׁר הִתאוֹשְׁשׁוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'recuperación',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'M1RmE',
    created: 1737103231642,
    data: {
      language: 'he',
      source: 'סף',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umbral, inicio, punto de reacción',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9hz8s',
    created: 1737103233047,
    data: {
      language: 'he',
      source: 'מזג',
      ipa: '',
      example: '',
      definition: '',
      translation: 'temperamento, clima',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WBVY0',
    created: 1737103234027,
    data: {
      language: 'he',
      source: 'הַשְׁלָכָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'desplazamiento, lanzamiento',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cFCKk',
    created: 1737103235021,
    data: {
      language: 'he',
      source: 'תוֹצָאָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, producción',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9iSuB',
    created: 1737103244841,
    data: {
      language: 'he',
      source: 'לְהוֹדוֹת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'agradecer, dar gracias',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Pb7B6',
    created: 1737103254634,
    data: {
      language: 'he',
      source: 'לִשְׁקוֹל',
      ipa: '',
      example: '',
      definition: '',
      translation: 'pesar, considerar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sKyQU',
    created: 1737103265008,
    data: {
      language: 'he',
      source: 'הקדיש',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HLh0k',
    created: 1737103274904,
    data: {
      language: 'he',
      source: 'לְהַצְדִיק',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificar, defender',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'omCLF',
    created: 1737103294246,
    data: {
      language: 'he',
      source: 'הזנחה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negligencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PE9_9',
    created: 1737103304351,
    data: {
      language: 'he',
      source: 'לְשַׁכְנֵעַ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'convencer, persuadir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'J6GTc',
    created: 1737103314140,
    data: {
      language: 'he',
      source: 'בְּהַדְרָגָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'en la jerarquía',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yuzNw',
    created: 1737103324063,
    data: {
      language: 'he',
      source: 'באופן מרומז',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícitamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'aS5Ng',
    created: 1737103333975,
    data: {
      language: 'he',
      source: 'בְּמִיּוּחָד',
      ipa: '',
      example: '',
      definition: '',
      translation: 'especialmente, en particular',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Y6Oza',
    created: 1737103335064,
    data: {
      language: 'he',
      source: 'באופן מיידי',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inmediatamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Rqc4Q',
    created: 1737103354297,
    data: {
      language: 'he',
      source: 'בערך',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jbQzA',
    created: 1737103365055,
    data: {
      language: 'he',
      source: 'בְּמִדָּה מַסְפִּיקָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'XXWMt',
    created: 1737103375137,
    data: {
      language: 'he',
      source: 'מתמיד',
      ipa: '',
      example: '',
      definition: '',
      translation: 'constante, perseverante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_yWmN',
    created: 1737103385005,
    data: {
      language: 'he',
      source: 'מַקִיף',
      ipa: '',
      example: '',
      definition: '',
      translation: 'amplio, extensivo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xu1ck',
    created: 1737103389386,
    data: {
      language: 'he',
      source: 'מְהַנֶה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hacer sentir, hacer experimentar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'U7VZ6',
    created: 1737103408863,
    data: {
      language: 'he',
      source: 'זהיר',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cauteloso, precavido',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qrasK',
    created: 1737103428324,
    data: {
      language: 'he',
      source: 'סרבן',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rebelde',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BJc9k',
    created: 1737103439190,
    data: {
      language: 'he',
      source: 'חשוב',
      ipa: '',
      example: '',
      definition: '',
      translation: 'importante, significativo, esencial',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
