import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '9bjkN',
    created: 1737104735150,
    data: {
      language: 'he',
      source: 'שְׁלֵמוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: '完全性, 完全',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uz9up',
    created: 1737104745452,
    data: {
      language: 'he',
      source: 'כּוֹשֵׁר הִתאוֹשְׁשׁוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: '回復力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9xBCY',
    created: 1737104764781,
    data: {
      language: 'he',
      source: 'סף',
      ipa: '',
      example: '',
      definition: '',
      translation: '入口の下部, 始まり, 反応点',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sDCcu',
    created: 1737104774655,
    data: {
      language: 'he',
      source: 'מזג',
      ipa: '',
      example: '',
      definition: '',
      translation: '気候, 性格',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Cu9my',
    created: 1737104784642,
    data: {
      language: 'he',
      source: 'הַשְׁלָכָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '投棄, 投げ捨て',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kq_KP',
    created: 1737104785653,
    data: {
      language: 'he',
      source: 'תוֹצָאָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, アウトプット',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tZm-G',
    created: 1737104795581,
    data: {
      language: 'he',
      source: 'לְהוֹדוֹת',
      ipa: '',
      example: '',
      definition: '',
      translation: '感謝する, 謝る',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fGipW',
    created: 1737104805445,
    data: {
      language: 'he',
      source: 'לִשְׁקוֹל',
      ipa: '',
      example: '',
      definition: '',
      translation: '重さを量る, 計量する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JTACQ',
    created: 1737104841634,
    data: {
      language: 'he',
      source: 'הקדיש',
      ipa: '',
      example: '',
      definition: '',
      translation: '捧げる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HaF99',
    created: 1737104859816,
    data: {
      language: 'he',
      source: 'לְהַצְדִיק',
      ipa: '',
      example: '',
      definition: '',
      translation: '正当化する',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'KYve6',
    created: 1737104878320,
    data: {
      language: 'he',
      source: 'הַזנָחָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '放置',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'y5Wvg',
    created: 1737104888130,
    data: {
      language: 'he',
      source: 'לְשַׁכְנֵעַ',
      ipa: '',
      example: '',
      definition: '',
      translation: '説得する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DziLR',
    created: 1737104889124,
    data: {
      language: 'he',
      source: 'בְּהַדרָגָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '階級, ランク',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PDvfj',
    created: 1737104899558,
    data: {
      language: 'he',
      source: 'באופן מרומז',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗示的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yl32e',
    created: 1737104911676,
    data: {
      language: 'he',
      source: 'בְּמִיּוּחָד',
      ipa: '',
      example: '',
      definition: '',
      translation: '特に, 特別に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ScX3b',
    created: 1737104922183,
    data: {
      language: 'he',
      source: 'באופן מיידי',
      ipa: '',
      example: '',
      definition: '',
      translation: '即座に, すぐに',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'mqd6R',
    created: 1737104932711,
    data: {
      language: 'he',
      source: 'בערך',
      ipa: '',
      example: '',
      definition: '',
      translation: 'おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RU-sY',
    created: 1737104942711,
    data: {
      language: 'he',
      source: 'בְּמִדָּה מַסְפִּיקָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '十分に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Ts3zf',
    created: 1737104952737,
    data: {
      language: 'he',
      source: 'מתמיד',
      ipa: '',
      example: '',
      definition: '',
      translation: '勤勉な, 常に',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'v2fxs',
    created: 1737104962490,
    data: {
      language: 'he',
      source: 'מַקִיף',
      ipa: '',
      example: '',
      definition: '',
      translation: '包括的, 周囲の',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'IULEZ',
    created: 1737104972485,
    data: {
      language: 'he',
      source: 'מְהַנֶה',
      ipa: '',
      example: '',
      definition: '',
      translation: '楽しませる, 喜ばせる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uP_At',
    created: 1737104991715,
    data: {
      language: 'he',
      source: 'זהיר',
      ipa: '',
      example: '',
      definition: '',
      translation: '注意深い, 慎重な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YA8Tf',
    created: 1737105011021,
    data: {
      language: 'he',
      source: 'סרבן',
      ipa: '',
      example: '',
      definition: '',
      translation: '反抗者',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '8OEPR',
    created: 1737105039205,
    data: {
      language: 'he',
      source: 'חשוב',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要な, 大切な, 必要な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
