import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'WyuXs',
    created: 1736966658523,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridad, entereza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BAyjG',
    created: 1736966659402,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0CHdM',
    created: 1736966660828,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'el umbral',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cou9z',
    created: 1736966663522,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposición, arreglo, estado de ánimo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i-_HI',
    created: 1736966664896,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: '',
      example: '',
      definition: '',
      translation: 'repercusión',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sjqvH',
    created: 1736966666452,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, puntaje',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FctU2',
    created: 1736966668605,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconocer, identificar, dar cuenta',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jrnbh',
    created: 1736966671272,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar, tener en cuenta, examinar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DJOCp',
    created: 1736966672800,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicar, consagrar, nombrar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lXvLm',
    created: 1736966674866,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificar, dar cuenta, admitir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iI3O9',
    created: 1736966676441,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'desatender, ignorar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'g5XZo',
    created: 1736966677901,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuadir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Kntls',
    created: 1736966678805,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3Ng7J',
    created: 1736966679856,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícitamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xWHLQ',
    created: 1736966680810,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'en particular',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rfTGR',
    created: 1736966682406,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rápidamente, de inmediato',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cj8Vg',
    created: 1736966683927,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'md7sP',
    created: 1736966684644,
    data: {
      language: 'it',
      source: 'suficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficientemente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Rud9_',
    created: 1736966686093,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-5Jvp',
    created: 1736966687562,
    data: {
      language: 'it',
      source: 'completo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'completo, entero, máximo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xPwwX',
    created: 1736966689588,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'delicioso, sabroso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RE47_',
    created: 1736966691114,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cauteloso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kPYxl',
    created: 1736966692542,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reacio',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fz7fE',
    created: 1736966694085,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significativo, importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
