import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'dGKDd',
    created: 1736966878744,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: '',
      example: '',
      definition: '',
      translation: '完全性, 誠実',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_bHN9',
    created: 1736966897499,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'レジリエンス, 復元力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rV1pp',
    created: 1736966907168,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'しきい, しきい値',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_cXay',
    created: 1736966925749,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: '',
      example: '',
      definition: '',
      translation: '決定, 配置, 気分',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '21gL3',
    created: 1736966935649,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: '',
      example: '',
      definition: '',
      translation: '影響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fvSju',
    created: 1736966936609,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, スコア',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1p7Jv',
    created: 1736966955112,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: '',
      example: '',
      definition: '',
      translation: '認識する, 識別する, 認める',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DOKhs',
    created: 1736966965007,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮する, 検討する, 見なす',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'b6yL-',
    created: 1736966983781,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: '',
      example: '',
      definition: '',
      translation: '捧げる, 献呈する, 名付ける',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'npIc9',
    created: 1736966993837,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: '',
      example: '',
      definition: '',
      translation: '正当化する, 説明する, 許可する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZhkMv',
    created: 1736967003823,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: '',
      example: '',
      definition: '',
      translation: '無視する, 放置する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fcpzF',
    created: 1736967013521,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: '',
      example: '',
      definition: '',
      translation: '説得する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1oC9d',
    created: 1736967014657,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '徐々に, 段階的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gFdjN',
    created: 1736967024427,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗黙に, 暗黙的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ten6T',
    created: 1736967034340,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: '特に, 具体的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Citkb',
    created: 1736967044103,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '迅速に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O04zp',
    created: 1736967072143,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uVzfC',
    created: 1736967081936,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '十分に, 足りるほど',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YQwFV',
    created: 1736967101131,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '持続的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8upHL',
    created: 1736967110846,
    data: {
      language: 'it',
      source: 'completo',
      ipa: '',
      example: '',
      definition: '',
      translation: '完全な, 全体の, フル',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IFqT7',
    created: 1736967129261,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: '',
      example: '',
      definition: '',
      translation: '美味しい, 素晴らしい',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'y2GRA',
    created: 1736967138929,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: '',
      example: '',
      definition: '',
      translation: '慎重な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kMqHJ',
    created: 1736967157745,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ためらいがち',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c6MAu',
    created: 1736967167608,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要な, 意味のある',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
