import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xXFUY',
    created: 1736970430036,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: '',
      example: '',
      definition: '',
      translation: 'integritet, helhet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3-v_y',
    created: 1736970439872,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliens',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MZOhl',
    created: 1736970449706,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terskel, grense, minimum',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ldunV',
    created: 1736970459482,
    data: {
      language: 'it',
      source: 'disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposisjon',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gA78X',
    created: 1736970469349,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: '',
      example: '',
      definition: '',
      translation: 'virkning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TjvOu',
    created: 1736970470590,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat, utfall',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2dPb6',
    created: 1736970480549,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gjenkjenne, skille, erkjenne',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FEOBu',
    created: 1736970490733,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vurdere, betrakte, ta hensyn til',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HCxvR',
    created: 1736970500582,
    data: {
      language: 'it',
      source: 'dedikere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedikere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gGVic',
    created: 1736970510707,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rettferdiggjøre, begrunne, godkjenne',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VSMV2',
    created: 1736970522590,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsømme, se bort fra',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qG4rT',
    created: 1736970523490,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SQYPT',
    created: 1736970533113,
    data: {
      language: 'it',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LkYXA',
    created: 1736970542891,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implisitt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NmijW',
    created: 1736970552722,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'spesielt, i særdeleshet',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bEmGH',
    created: 1736970562436,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'raskt, hurtig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KCXxl',
    created: 1736970590297,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omtrent',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7BLA8',
    created: 1736970591676,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tilstrekkelig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r4PDq',
    created: 1736970612229,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vedvarende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sxzDF',
    created: 1736970622062,
    data: {
      language: 'it',
      source: 'komplett',
      ipa: '',
      example: '',
      definition: '',
      translation: 'komplett',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QOq56',
    created: 1736970632167,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'deilig, herlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kE1N7',
    created: 1736970642035,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsiktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qAc7a',
    created: 1736970643159,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KVYz4',
    created: 1736970653569,
    data: {
      language: 'it',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
