import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'IM0px',
    created: 1736974606444,
    data: {
      language: 'it',
      source: 'інтегритà',
      ipa: '',
      example: '',
      definition: '',
      translation: 'цілісність',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9Qogx',
    created: 1736974617079,
    data: {
      language: 'it',
      source: 'резилієнція',
      ipa: '',
      example: '',
      definition: '',
      translation: 'резилієнція',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UqDm6',
    created: 1736974618157,
    data: {
      language: 'it',
      source: 'соглія',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ydViA',
    created: 1736974637596,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: '',
      example: '',
      definition: '',
      translation: 'розпорядження, упорядкування, настрій',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AdSWN',
    created: 1736974663718,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: '',
      example: '',
      definition: '',
      translation: 'вплив',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IPig1',
    created: 1736974683203,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: '',
      example: '',
      definition: '',
      translation: 'результат, вихід',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fenO1',
    created: 1736974702921,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'визнати, ідентифікувати, виявити',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jxBDm',
    created: 1736974713662,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'розглядати, вважати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MkM1z',
    created: 1736974733444,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'присвятити, посвятити, назвати на честь',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_cJbv',
    created: 1736974752834,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'виправдовувати, обґрунтовувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2psPa',
    created: 1736974772291,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'не дбати, не враховувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iOQ-u',
    created: 1736974782941,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'переконати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NcWZT',
    created: 1736974793486,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постепово',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CgaAo',
    created: 1736974803331,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неявно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-IJ-M',
    created: 1736974813382,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'зокрема',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Boivi',
    created: 1736974841204,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'швидко',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'msx1U',
    created: 1736974842223,
    data: {
      language: 'it',
      source: 'в приблизно',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приблизно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'a1oJt',
    created: 1736974852584,
    data: {
      language: 'it',
      source: 'достатньо',
      ipa: '',
      example: '',
      definition: '',
      translation: 'досить, достатньо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qc6E7',
    created: 1736974872664,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постійний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'X-PmS',
    created: 1736974901903,
    data: {
      language: 'it',
      source: 'completo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'повний, цілісний, максимальний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7oCs8',
    created: 1736974912071,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'смачний, приємний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FgK-W',
    created: 1736974931527,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обережний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's6ex_',
    created: 1736974941517,
    data: {
      language: 'it',
      source: 'рилутант',
      ipa: '',
      example: '',
      definition: '',
      translation: 'рилутант',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Eitjm',
    created: 1736974960733,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'значний, суттєвий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
