import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'f1cWL',
    created: 1736966772487,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: '',
      example: '',
      definition: '',
      translation: '完整性, 正直',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k-uMi',
    created: 1736966773296,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: '韧性, 适应力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3AIdZ',
    created: 1736966774691,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: '',
      example: '',
      definition: '',
      translation: '门槛, 阈值',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UAFMr',
    created: 1736966776190,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: '',
      example: '',
      definition: '',
      translation: '安排, 处置, 心态',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D2xQ1',
    created: 1736966780205,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: '',
      example: '',
      definition: '',
      translation: '影响, 后果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'E0WBF',
    created: 1736966781839,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: '',
      example: '',
      definition: '',
      translation: '结果, 得分',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ksxLi',
    created: 1736966783369,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: '',
      example: '',
      definition: '',
      translation: '识别, 认出, 承认',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qR9cF',
    created: 1736966785118,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: '',
      example: '',
      definition: '',
      translation: '考虑, 认为',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Nz-BA',
    created: 1736966786966,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉献, 献给, 致敬',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fmTqF',
    created: 1736966788872,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: '',
      example: '',
      definition: '',
      translation: '证明, 辩解, 合理化',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xE_IW',
    created: 1736966790605,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽视, 不考虑',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2-l4V',
    created: 1736966791814,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: '',
      example: '',
      definition: '',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EkZ0L',
    created: 1736966793180,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐渐',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'a9EYg',
    created: 1736966794072,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '隐含地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ehF0g',
    created: 1736966799292,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: '特别, 尤其',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cQpkN',
    created: 1736966800601,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '迅速地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uFIds',
    created: 1736966801857,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: '',
      example: '',
      definition: '',
      translation: '大约',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lzkq-',
    created: 1736966802919,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4bG0O',
    created: 1736966804414,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '持续的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gVFle',
    created: 1736966806189,
    data: {
      language: 'it',
      source: 'completo',
      ipa: '',
      example: '',
      definition: '',
      translation: '完整的, 完全的, 满的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GAR1r',
    created: 1736966808625,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: '',
      example: '',
      definition: '',
      translation: '美味的, 可口的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lhe9d',
    created: 1736966810145,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: '',
      example: '',
      definition: '',
      translation: '谨慎的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OAbWJ',
    created: 1736966811838,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情愿',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IFjhR',
    created: 1736966813385,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的, 显著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
