import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'b4Lmw',
    created: 1736966610261,
    data: {
      language: 'ja',
      source: 'səmimiyyət',
      ipa: '',
      example: '',
      definition: '',
      translation: 'səmimiyyət',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EZxIE',
    created: 1736966611690,
    data: {
      language: 'ja',
      source: 'qayıtma gücü',
      ipa: '',
      example: '',
      definition: '',
      translation: 'qayıtma gücü',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8ET8o',
    created: 1736966612460,
    data: {
      language: 'ja',
      source: 'şikiyi həddi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'şikayət həddi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z60vZ',
    created: 1736966613295,
    data: {
      language: 'ja',
      source: 'hədd',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hədd',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Lu455',
    created: 1736966614210,
    data: {
      language: 'ja',
      source: 'həng',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jeAf8',
    created: 1736966614986,
    data: {
      language: 'ja',
      source: 'nəticə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəticə',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-kWAT',
    created: 1736966615854,
    data: {
      language: 'ja',
      source: 'tanımaq',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tanımaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3dwaU',
    created: 1736966616931,
    data: {
      language: 'ja',
      source: 'konsiderasiya etmək',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəzərə almaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lScEh',
    created: 1736966617855,
    data: {
      language: 'ja',
      source: 'kənşin',
      ipa: '',
      example: '',
      definition: '',
      translation: 'qəbul etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'u2B80',
    created: 1736966618616,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'haqlı çıxarmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-MqJG',
    created: 1736966619467,
    data: {
      language: 'ja',
      source: 'müsi',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_90Aq',
    created: 1736966620462,
    data: {
      language: 'ja',
      source: 'sözləşdirmək',
      ipa: '',
      example: '',
      definition: '',
      translation: 'razılaşmaq, sözləşmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PPHIv',
    created: 1736966621526,
    data: {
      language: 'ja',
      source: 'cəld-cəld',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tez-tez',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EuoNy',
    created: 1736966622600,
    data: {
      language: 'ja',
      source: 'anımktik',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GTHsI',
    created: 1736966623355,
    data: {
      language: 'ja',
      source: 'xüsusilə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'xüsusilə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oA8Nq',
    created: 1736966624299,
    data: {
      language: 'ja',
      source: 'sürətlə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sürətlə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A5M1O',
    created: 1736966625223,
    data: {
      language: 'ja',
      source: 'daidə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'çox, böyük',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yftUR',
    created: 1736966626510,
    data: {
      language: 'ja',
      source: 'yeterincə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kafi, yetərincə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M8MLM',
    created: 1736966627447,
    data: {
      language: 'ja',
      source: 'davamlı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'davamlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r7dZt',
    created: 1736966628335,
    data: {
      language: 'ja',
      source: 'əhatəli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gözəl',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6PDiC',
    created: 1736966629209,
    data: {
      language: 'ja',
      source: 'əyləncəli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'əyləncəli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gr_qg',
    created: 1736966630399,
    data: {
      language: 'ja',
      source: 'yoxlamaq',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sınamaq, test etmək',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rpHbh',
    created: 1736966631482,
    data: {
      language: 'ja',
      source: 'ki ga sunmanai',
      ipa: '',
      example: '',
      definition: '',
      translation: 'narahat olmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N-82h',
    created: 1736966632278,
    data: {
      language: 'ja',
      source: 'önəmli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'önəmli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
