import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'JdFfg',
    created: 1736966346190,
    data: {
      language: 'ja',
      source: '誠実さ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'יושר',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5tWZi',
    created: 1736966347282,
    data: {
      language: 'ja',
      source: '回復力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'חוסן',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7Jr4n',
    created: 1736966348742,
    data: {
      language: 'ja',
      source: 'しきい値',
      ipa: '',
      example: '',
      definition: '',
      translation: 'סף',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ewLzD',
    created: 1736966349724,
    data: {
      language: 'ja',
      source: '配置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'סידור, הנחה',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HGU_8',
    created: 1736966351083,
    data: {
      language: 'ja',
      source: '反響',
      ipa: '',
      example: '',
      definition: '',
      translation: 'הד, תגובה',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AlD0W',
    created: 1736966352099,
    data: {
      language: 'ja',
      source: '結果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'תוצאה, מסקנה',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qRttp',
    created: 1736966353420,
    data: {
      language: 'ja',
      source: '認める',
      ipa: '',
      example: '',
      definition: '',
      translation: 'להכיר, לאשר',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UIub8',
    created: 1736966354556,
    data: {
      language: 'ja',
      source: '考慮する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'לשקול',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Rdk0y',
    created: 1736966355525,
    data: {
      language: 'ja',
      source: '献身する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'להקדיש, להתמסר',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Gdxmk',
    created: 1736966356492,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'להצדיק',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Z-xX4',
    created: 1736966357611,
    data: {
      language: 'ja',
      source: '無視',
      ipa: '',
      example: '',
      definition: '',
      translation: 'התעלמות, זניחה',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D3tFw',
    created: 1736966358447,
    data: {
      language: 'ja',
      source: '説得する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'שכנע',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_k1da',
    created: 1736966359953,
    data: {
      language: 'ja',
      source: '徐々に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'בהדרגה, לאט לאט',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6tM7B',
    created: 1736966361470,
    data: {
      language: 'ja',
      source: '暗黙的に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'מובלע, מובן מאליו',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SzqTf',
    created: 1736966362499,
    data: {
      language: 'ja',
      source: '特に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'במיוחד, בעיקר',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BBaWV',
    created: 1736966363554,
    data: {
      language: 'ja',
      source: '速やかに',
      ipa: '',
      example: '',
      definition: '',
      translation: 'במהירות',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Iwiei',
    created: 1736966364739,
    data: {
      language: 'ja',
      source: '大体',
      ipa: '',
      example: '',
      definition: '',
      translation: 'בעיקרון, בגדול',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CuizZ',
    created: 1736966365934,
    data: {
      language: 'ja',
      source: '十分に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'די, מספיק',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1n-h1',
    created: 1736966366797,
    data: {
      language: 'ja',
      source: '持続的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'מתמשך',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NxRVo',
    created: 1736966368010,
    data: {
      language: 'ja',
      source: '包括的な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'כולל',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gW4LA',
    created: 1736966369057,
    data: {
      language: 'ja',
      source: '楽しい',
      ipa: '',
      example: '',
      definition: '',
      translation: 'מהנה, נעים',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K1Gci',
    created: 1736966369982,
    data: {
      language: 'ja',
      source: '用心深い',
      ipa: '',
      example: '',
      definition: '',
      translation: 'זהיר, נזהר',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vx2IY',
    created: 1736966370824,
    data: {
      language: 'ja',
      source: '気が進まない',
      ipa: '',
      example: '',
      definition: '',
      translation: 'לא מעוניין',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FVn4w',
    created: 1736966371660,
    data: {
      language: 'ja',
      source: '重要な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'חשוב',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
