import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'QKFO-',
    created: 1737020783926,
    data: {
      language: 'ko',
      source: '실성',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Geisteskrankheit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pcMTJ',
    created: 1737020793658,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Widerstandsfähigkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'P0zOA',
    created: 1737020803471,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Grenzpunkt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Cj36Y',
    created: 1737020823560,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Bearbeitung, Verkauf, Maßnahme',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VLwEk',
    created: 1737020833306,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Echolot, Widerhall',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'V0_8E',
    created: 1737020861253,
    data: {
      language: 'ko',
      source: '결과',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Ergebnis',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Kc5iy',
    created: 1737020889329,
    data: {
      language: 'ko',
      source: '인정',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Anerkennung, Mitgefühl',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WeAZh',
    created: 1737020917446,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Vorwärtsbewegung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pwLTF',
    created: 1737020954230,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'übergeben, opfern, zahlen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dlZQq',
    created: 1737020972200,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Gott sagt',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aUW9O',
    created: 1737020981924,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vernachlässigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KGOSb',
    created: 1737021010236,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Vorwärtsbewegung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SIwaN',
    created: 1737021020031,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'langsam, allmählich',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'b3E_G',
    created: 1737021048072,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'konkret',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3QGyE',
    created: 1737021067199,
    data: {
      language: 'ko',
      source: '특히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'insbesondere',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zdyf4',
    created: 1737021086179,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sofort',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_ha80',
    created: 1737021095827,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefähr, halbherzig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HzWhI',
    created: 1737021105615,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ausreichend, genug',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NzS93',
    created: 1737021115391,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'beständig, dauerhaft',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TtcS6',
    created: 1737021143686,
    data: {
      language: 'ko',
      source: '포괄적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umfassend',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ncR7M',
    created: 1737021153566,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sehr glücklich',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3egGj',
    created: 1737021163724,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vorsichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jWpvu',
    created: 1737021200820,
    data: {
      language: 'ko',
      source: '의존',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Abhängigkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KkdRA',
    created: 1737021229440,
    data: {
      language: 'ko',
      source: '한',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ein, eine, etwa',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
