import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'vq6Ch',
    created: 1737022960369,
    data: {
      language: 'ko',
      source: '실성',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disturbo mentale',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zYEHO',
    created: 1737022978601,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resilienza',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kGy49',
    created: 1737022996796,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'punto limite',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'v-31k',
    created: 1737023032895,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eliminazione, vendita, misura',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'r2bw1',
    created: 1737023050944,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eco, riflesso',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8RKnc',
    created: 1737023087175,
    data: {
      language: 'ko',
      source: '결과',
      ipa: '',
      example: '',
      definition: '',
      translation: 'risultato',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KO8c5',
    created: 1737023123613,
    data: {
      language: 'ko',
      source: '인정',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riconoscimento, compassione',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Atosf',
    created: 1737023159766,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'avanzamento',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MmB_B',
    created: 1737023196044,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'offrire, dedicare, pagare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8p4uk',
    created: 1737023205678,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Dio dice giusto',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IjxSy',
    created: 1737023215465,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'trascurare, negligenza',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wHP6d',
    created: 1737023252912,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'avanzamento',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rkxic',
    created: 1737023263086,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lentamente, poco a poco',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mTU8V',
    created: 1737023291406,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'specifico',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gkdnR',
    created: 1737023318971,
    data: {
      language: 'ko',
      source: '특히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'particolarmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MFCno',
    created: 1737023337565,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: '',
      example: '',
      definition: '',
      translation: 'immediatamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'b3IQD',
    created: 1737023347266,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'approssimativamente, in modo approssimativo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ItWdF',
    created: 1737023357592,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficientemente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HLjOq',
    created: 1737023367140,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sostenibile',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZxQGE',
    created: 1737023395234,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'potenziale',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Hf2xF',
    created: 1737023404985,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'molto felice',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hloHz',
    created: 1737023415186,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cauteloso, prudente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4ozzD',
    created: 1737023434957,
    data: {
      language: 'ko',
      source: '의존',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dipendenza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'puvYx',
    created: 1737023462962,
    data: {
      language: 'ko',
      source: '한',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uno, un, circa',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
