import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'jlR4C',
    created: 1737024292926,
    data: {
      language: 'ko',
      source: '실성',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geestelijke afwijking',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zA5bk',
    created: 1737024302534,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'veerkracht',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oRpjv',
    created: 1737024312185,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'grenspunt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wOncX',
    created: 1737024323057,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verkoop, afhandeling, maatregel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AozI9',
    created: 1737024332649,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'echo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nfM1l',
    created: 1737024364344,
    data: {
      language: 'ko',
      source: '결과',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultaat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Az7xW',
    created: 1737024392761,
    data: {
      language: 'ko',
      source: '인정',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkenning, waardering',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FNTsv',
    created: 1737024420865,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vooruitgang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BcaX1',
    created: 1737024449673,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geven, offeren, betalen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HySkF',
    created: 1737024459305,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'God zegt',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Gm7HS',
    created: 1737024468990,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verwaarlozen, vergeten',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WpewB',
    created: 1737024487972,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vooruitgang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BQOFC',
    created: 1737024497702,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'langzaam, geleidelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_nbRx',
    created: 1737024525677,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'concreet',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Zuuh0',
    created: 1737024544871,
    data: {
      language: 'ko',
      source: '특히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bijzonder',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MjvM1',
    created: 1737024564021,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: '',
      example: '',
      definition: '',
      translation: 'onmiddellijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lqh_G',
    created: 1737024565217,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ongeveer, min of meer',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xSDKU',
    created: 1737024574961,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voldoende, genoeg',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pfd6P',
    created: 1737024584694,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'duurzaam',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rY6Wo',
    created: 1737024612557,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'potentieel',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'A07G2',
    created: 1737024622418,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zeer blij',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '48yGl',
    created: 1737024632055,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'L0jDZ',
    created: 1737024660012,
    data: {
      language: 'ko',
      source: '주저하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aarzelen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'foro8',
    created: 1737024688902,
    data: {
      language: 'ko',
      source: '한',
      ipa: '',
      example: '',
      definition: '',
      translation: 'één, een, ongeveer',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
