import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'CAjLW',
    created: 1737044896919,
    data: {
      language: 'ko',
      source: '실성',
      ipa: '',
      example: '',
      definition: '',
      translation: 'психічний розлад',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NGRpr',
    created: 1737044897797,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'відновлювальність',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JL2WX',
    created: 1737044898741,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'межа, гранична точка',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zDPqE',
    created: 1737044900336,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обробка, продаж, заходи',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0E0BE',
    created: 1737044901319,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'відлуння',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FyPx3',
    created: 1737044902742,
    data: {
      language: 'ko',
      source: '결과',
      ipa: '',
      example: '',
      definition: '',
      translation: 'результат',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GKImA',
    created: 1737044906976,
    data: {
      language: 'ko',
      source: '인정',
      ipa: '',
      example: '',
      definition: '',
      translation: 'визнання, тепле серце',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9b3I-',
    created: 1737044912932,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'просування',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AHNMa',
    created: 1737044915342,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'передати, пожертвувати, сплачувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kP84q',
    created: 1737044916203,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Бог каже',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9jB25',
    created: 1737044917095,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неуважно ставитися',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bAA1a',
    created: 1737044918836,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: 'просування',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OGGM9',
    created: 1737044919883,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'повільно, поступово',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '13Epe',
    created: 1737044921472,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'конкретний',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Zj4ZV',
    created: 1737044922967,
    data: {
      language: 'ko',
      source: '특히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'особливо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4z98C',
    created: 1737044924880,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: '',
      example: '',
      definition: '',
      translation: 'негайно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FJsKW',
    created: 1737044925694,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приблизно, на око',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'm54dv',
    created: 1737044926545,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достатньо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ksuMr',
    created: 1737044927548,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'стійкий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'l6TlH',
    created: 1737044929402,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: '',
      example: '',
      definition: '',
      translation: 'потенційний',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'l_lID',
    created: 1737044930507,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дуже радісний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Tqo6W',
    created: 1737044931349,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обережний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9t7ZJ',
    created: 1737044932924,
    data: {
      language: 'ko',
      source: '주저하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'вагатися',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VJc3S',
    created: 1737044935338,
    data: {
      language: 'ko',
      source: '한',
      ipa: '',
      example: '',
      definition: '',
      translation: 'один, якийсь, приблизно',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
