import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'NiiNj',
    created: 1737021695301,
    data: {
      language: 'ko',
      source: '융통성',
      ipa: '',
      example: '',
      definition: '',
      translation: '靈活性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XsAiN',
    created: 1737021705038,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: '韌性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jLuGH',
    created: 1737021724275,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: '極限',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z9llm',
    created: 1737021753700,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: '',
      example: '',
      definition: '',
      translation: '處理, 銷售, 措施',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GM9kT',
    created: 1737021763492,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: '回響, 反響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zhx81',
    created: 1737021791679,
    data: {
      language: 'ko',
      source: '결과',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DhC08',
    created: 1737021828884,
    data: {
      language: 'ko',
      source: '인정',
      ipa: '',
      example: '',
      definition: '',
      translation: '承認, 仁慈',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'k9ZDL',
    created: 1737021865144,
    data: {
      language: 'ko',
      source: '고려',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hNUsn',
    created: 1737021902323,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉獻, 交納',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1d04V',
    created: 1737021912021,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: '神說',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '042b4',
    created: 1737021914970,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽視, 疏忽',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'c7gm7',
    created: 1737021942972,
    data: {
      language: 'ko',
      source: '전진',
      ipa: '',
      example: '',
      definition: '',
      translation: '前進',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VdQdm',
    created: 1737021953337,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐漸, 慢慢',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ar3yB',
    created: 1737021981359,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: '',
      example: '',
      definition: '',
      translation: '具體的',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'j55pZ',
    created: 1737022000487,
    data: {
      language: 'ko',
      source: '특히',
      ipa: '',
      example: '',
      definition: '',
      translation: '特別',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7H29n',
    created: 1737022028067,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C0gIO',
    created: 1737022037934,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: '大概, 隨便',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WO-Oi',
    created: 1737022047637,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: '',
      example: '',
      definition: '',
      translation: '足夠地, 充分地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'otCCN',
    created: 1737022057552,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: '持續的, 持續性',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ofJrs',
    created: 1737022085375,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: '',
      example: '',
      definition: '',
      translation: '潛在的',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-XzZE',
    created: 1737022095598,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: '非常高興',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NEfTc',
    created: 1737022105510,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: '小心的, 謹慎的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Si7qb',
    created: 1737022133790,
    data: {
      language: 'ko',
      source: '의존',
      ipa: '',
      example: '',
      definition: '',
      translation: '依賴',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OG98v',
    created: 1737022162323,
    data: {
      language: 'ko',
      source: '한',
      ipa: '',
      example: '',
      definition: '',
      translation: '一個, 某個, 大約',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
