import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'o4rcj',
    created: 1737019122304,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bütünlük',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eBYZi',
    created: 1737019134430,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: '',
      example: '',
      definition: '',
      translation: 'müqavimət',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jHwxr',
    created: 1737019144361,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eşik dəyəri',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'g94Dj',
    created: 1737019162400,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dispozisiya',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iVdli',
    created: 1737019172166,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəticə, cavab',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_CN2E',
    created: 1737019190284,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəticə',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ceQj9',
    created: 1737019208471,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tanımaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_cmJ9',
    created: 1737019226687,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'düşünmək, nəzərə almaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cm06S',
    created: 1737019244991,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'həsr etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'An88c',
    created: 1737019264335,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'izah etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Q411D',
    created: 1737019274128,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'əhəmiyyətsiz',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6l4ew',
    created: 1737019284196,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inandırmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qU1E6',
    created: 1737019294193,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tədricən',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nuiyY',
    created: 1737019295304,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gizli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zzIDx',
    created: 1737019305108,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'qeyri-adi, diqqətəlayiq',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7jdhb',
    created: 1737019314744,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'təklif',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Iucs-',
    created: 1737019324872,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'təxminən',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'h1TXE',
    created: 1737019334604,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kafi, yetərli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bZCHR',
    created: 1737019353041,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: '',
      example: '',
      definition: '',
      translation: 'səbr, davamlılıq',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Qo7q9',
    created: 1737019371957,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geniş, ətraflı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NXjDq',
    created: 1737019372699,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ləziz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kBtXl',
    created: 1737019391104,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ehtiyatlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7vsKt',
    created: 1737019400840,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'titrəyən, titrətici',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tsc_r',
    created: 1737019410511,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mühüm, əhəmiyyətli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
