import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'mBsHm',
    created: 1737003446961,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integrity',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TZCMX',
    created: 1737003447795,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resistance, immunity',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rG6QW',
    created: 1737003448804,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'threshold value',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'l6-4T',
    created: 1737003449597,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'organ disposition, bank deposit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'chySW',
    created: 1737003450417,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'repercussion, consequence',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'L5vtQ',
    created: 1737003451327,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'result',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ot24s',
    created: 1737003452139,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to acknowledge, to admit',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4n8sS',
    created: 1737003453263,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to consider',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AiZ8g',
    created: 1737003454191,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to dedicate',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BPaQ0',
    created: 1737003455230,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to justify',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '14wlU',
    created: 1737003456121,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to neglect',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CGepe',
    created: 1737003457143,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to convince',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'domAK',
    created: 1737003457944,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradual',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wrhHh',
    created: 1737003458584,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nKbi4',
    created: 1737003459725,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'remarkable, notable',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NywG0',
    created: 1737003460555,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prompt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8Nh11',
    created: 1737003461378,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'approximately, about',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C1_JO',
    created: 1737003462819,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficient',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rZx0A',
    created: 1737003463763,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perseverance',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OOUY-',
    created: 1737003464523,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: '',
      example: '',
      definition: '',
      translation: 'extensive',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kNIzH',
    created: 1737003465263,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'delicious, delightful',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '26jBV',
    created: 1737003466058,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cautious, careful',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dMm4i',
    created: 1737003467256,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hesitant, apprehensive',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1P7uH',
    created: 1737003476906,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significant, important',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
