import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'F80gU',
    created: 1737012254730,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rehellisyys',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oPZfA',
    created: 1737012274015,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vastustus, vastustuskyky',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_NzGg',
    created: 1737012293128,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kynnysarvo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4uCf6',
    created: 1737012312366,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rekisterit, talletus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cCRNP',
    created: 1737012322585,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'seuraamus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZahLQ',
    created: 1737012341671,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tulos',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_euf3',
    created: 1737012378026,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'myöntää',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mCdcK',
    created: 1737012406156,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'pohdiskella',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'imh0G',
    created: 1737012425475,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vihkiä',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z4opr',
    created: 1737012467726,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perustella',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4gWn0',
    created: 1737012478179,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'huomiotta jättää',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KKrgx',
    created: 1737012505850,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vakuuttaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'e68iH',
    created: 1737012533736,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'asteittain',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6On7e',
    created: 1737012561355,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'epäsuora',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wauPH',
    created: 1737012589275,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'huomattava',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ncnu_',
    created: 1737012608754,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kehotus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'k10p_',
    created: 1737012627980,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'noin',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'i-44N',
    created: 1737012656348,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riittävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cPh3P',
    created: 1737012684515,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kestävyys',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vwjZD',
    created: 1737012703963,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: '',
      example: '',
      definition: '',
      translation: 'laaja',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IsMOS',
    created: 1737012722860,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'herkullinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HOs1m',
    created: 1737012742138,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'varovainen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gA1dx',
    created: 1737012779341,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'epävarma',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hrj3Z',
    created: 1737012789545,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'merkittävä, tilastollisesti merkittävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
