import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'GogN7',
    created: 1737012810823,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'یکپارچگی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XsbsT',
    created: 1737012846869,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مقاومت, ایستادگی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3eH6Z',
    created: 1737012865910,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'آستانه ارزش',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dX_v7',
    created: 1737012894326,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ترتیب, واریز',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eGyYf',
    created: 1737012914744,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'عواقب',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3zcrV',
    created: 1737012951667,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نتیجه',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Vp2ez',
    created: 1737012970735,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'به رسمیت شناختن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QguO6',
    created: 1737012998673,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'در نظر گرفتن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gllXd',
    created: 1737013026653,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقدیس کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FLoo-',
    created: 1737013054391,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'توجیه کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'B8MJu',
    created: 1737013064718,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نادیده گرفتن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MtBBV',
    created: 1737013093182,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'قانع کردن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bUi2u',
    created: 1737013121043,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تدریجی',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cTb7B',
    created: 1737013139985,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ضمنی',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Dok-D',
    created: 1737013168142,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'قابل توجه',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0O38c',
    created: 1737013187513,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نشان',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NBFWB',
    created: 1737013206552,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقریباً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yugN4',
    created: 1737013234453,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'کافی',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RNgNr',
    created: 1737013263048,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: '',
      example: '',
      definition: '',
      translation: 'پایداری',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'odi3y',
    created: 1737013282351,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: '',
      example: '',
      definition: '',
      translation: 'گسترده',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7RdSZ',
    created: 1737013301852,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خوشمزه',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mI0ha',
    created: 1737013320999,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'محتاط',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 's1GMt',
    created: 1737013349133,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ترسیده',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7Ia_L',
    created: 1737013360655,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مهم, معنادار',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
