import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ApCtb',
    created: 1737010619207,
    data: {
      language: 'nl',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integritet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Tag2a',
    created: 1737010632964,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motstånd, resistens',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TvJTX',
    created: 1737010642741,
    data: {
      language: 'nl',
      source: 'drempelvärde',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tröskelvärde',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tSxAd',
    created: 1737010661651,
    data: {
      language: 'nl',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposition',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SK8BM',
    created: 1737010672124,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'återverkan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qBZni',
    created: 1737010691176,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C-8C9',
    created: 1737010727937,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkänna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WsQ5C',
    created: 1737010737578,
    data: {
      language: 'nl',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'överväga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7xDG_',
    created: 1737010766951,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inviga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'b6aJw',
    created: 1737010785890,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'förklara',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '80jZu',
    created: 1737010804933,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försumma',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'I4tf2',
    created: 1737010833205,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RwLWJ',
    created: 1737010861568,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4D36s',
    created: 1737010862452,
    data: {
      language: 'nl',
      source: 'implicitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CXSOa',
    created: 1737010890484,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'anmärkningsvärd',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yyI7F',
    created: 1737010918490,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prompt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KIDX6',
    created: 1737010937350,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefär',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oMjsz',
    created: 1737010956500,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräcklig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-Fxn-',
    created: 1737010984756,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uthållighet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'K1Cu8',
    created: 1737011013225,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omfattande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NfE79',
    created: 1737011041105,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: '',
      example: '',
      definition: '',
      translation: 'läckra',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dfyXS',
    created: 1737011060431,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försiktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rcXvb',
    created: 1737011079616,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rädd',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zuwef',
    created: 1737011103133,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'betydande, signifikant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
