import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'SdcpX',
    created: 1737087812812,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ինտեգրիտետ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jngem',
    created: 1737087822516,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'դիմադրություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4QFxG',
    created: 1737087832408,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մուտք, հանդերձարան',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hYw12',
    created: 1737087850887,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մասնագիր',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'usY2l',
    created: 1737087860559,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հետադարձ ազդեցություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JrQ56',
    created: 1737087861582,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մարտահրավեր',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Mb0Yf',
    created: 1737087871587,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հաստատել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HrPTe',
    created: 1737087881170,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'գնահատել, վերլուծել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'FHD9o',
    created: 1737087890792,
    data: {
      language: 'no',
      source: 'vie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'վերապահել, նվիրվել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YoMoO',
    created: 1737087900449,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդարացնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'M8SVF',
    created: 1737087910580,
    data: {
      language: 'no',
      source: 'forsømme',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անտեսել, մոռանալ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Iahlk',
    created: 1737087920492,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ZHE7i',
    created: 1737087930427,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հասարակաբար',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wfk6U',
    created: 1737087931507,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անհայտ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lIR0f',
    created: 1737087941218,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: '',
      example: '',
      definition: '',
      translation: '特别, विशेषत',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4BzeC',
    created: 1737087951226,
    data: {
      language: 'no',
      source: 'rask',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արագ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ekmcJ',
    created: 1737087970407,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մոտավորապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'X3y7V',
    created: 1737087980099,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'բավարար',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UQfry',
    created: 1737087990041,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'պահպանել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2cWu8',
    created: 1737087999937,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ընդհանուր, համապարփակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LXVgs',
    created: 1737088000913,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հրաշալի, հիանալի',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UjSUQ',
    created: 1737088011296,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'զգույշ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cMoeP',
    created: 1737088021072,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հակառակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DDzVs',
    created: 1737088039769,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'значительный, նշանավոր',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
