import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'wQ6oR',
    created: 1737088049601,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ინტეგრიტეტი',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0ZP79',
    created: 1737088059857,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გამძლეობა',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zSKKQ',
    created: 1737088078005,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'საფეხური',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yZDXN',
    created: 1737088096197,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაგეგმარება',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'd1fbC',
    created: 1737088114363,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შემდგომი შედეგი',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xwgAO',
    created: 1737088132381,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გამოსავალი',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'S1zr4',
    created: 1737088150602,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაადასტურო',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2iHKC',
    created: 1737088168826,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შეფასება, დაფიქრება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'm2wsr',
    created: 1737088186895,
    data: {
      language: 'no',
      source: 'vie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაკავშირება, მოწირვა',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fgK1_',
    created: 1737088205595,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მართლება',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6vo1P',
    created: 1737088225170,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გაზაფხულის დასაწყისი',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qvaJj',
    created: 1737088234983,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაარწმუნო',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'U87Ge',
    created: 1737088244742,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ნაბიჯ-ნაბიჯ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yMclj',
    created: 1737088254450,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'იმპლიციტური',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'p9S00',
    created: 1737088264240,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصاً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Rb3iU',
    created: 1737088274063,
    data: {
      language: 'no',
      source: 'rask',
      ipa: '',
      example: '',
      definition: '',
      translation: 'სწრაფი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5s3g9',
    created: 1737088283856,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაახლოებით',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UWekx',
    created: 1737088284905,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'საკმარისი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'B7psn',
    created: 1737088294619,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'გრძელდება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dN_LJ',
    created: 1737088304475,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მკაფიო, სრული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JKCot',
    created: 1737088314324,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'შესანიშნავი, მშვენიერი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-WLuC',
    created: 1737088325545,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მზრუნველად',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ANn1a',
    created: 1737088335221,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მოწინააღმდეგე, არასურველი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rPx6z',
    created: 1737088345101,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მნიშვნელოვანი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
