import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'N4gt_',
    created: 1737080880331,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: '독립성, 존엄성',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4eyF2',
    created: 1737080880913,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: '저항력',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'U8StC',
    created: 1737080890746,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: '',
      example: '',
      definition: '',
      translation: '문턱, 경계, 수중의 높이',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gjI37',
    created: 1737080900518,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: '계획, 배치',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wQwFG',
    created: 1737080910442,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: '여파, 후유증',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ZZQN9',
    created: 1737080920125,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: '',
      example: '',
      definition: '',
      translation: '공격, 결과',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DrMTD',
    created: 1737080930099,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: '',
      example: '',
      definition: '',
      translation: '확인하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'B6iQw',
    created: 1737080939812,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: '',
      example: '',
      definition: '',
      translation: '평가하다, 고려하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JSGmB',
    created: 1737080949811,
    data: {
      language: 'no',
      source: 'vie',
      ipa: '',
      example: '',
      definition: '',
      translation: '헌신하다, 결혼시키다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dtbsJ',
    created: 1737080950823,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: '정당화하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7_FuA',
    created: 1737080960451,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: '',
      example: '',
      definition: '',
      translation: '초여름',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'P23fL',
    created: 1737080970082,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: '설득하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'EfUWK',
    created: 1737080980006,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: '점진적으로',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hqncv',
    created: 1737080989981,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: '',
      example: '',
      definition: '',
      translation: '암시적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'eB3Cd',
    created: 1737080999897,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: '',
      example: '',
      definition: '',
      translation: '특히',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fJIZn',
    created: 1737081009873,
    data: {
      language: 'no',
      source: 'rask',
      ipa: '',
      example: '',
      definition: '',
      translation: '빠른, 신속한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xmTAy',
    created: 1737081010726,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: '',
      example: '',
      definition: '',
      translation: '대략, 약',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zV0-K',
    created: 1737081020487,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: '충분한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'y8_D-',
    created: 1737081030253,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: '',
      example: '',
      definition: '',
      translation: '지속하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vRRAn',
    created: 1737081039934,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: '포괄적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WveoV',
    created: 1737081049944,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '훌륭한, 멋진',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-zKfU',
    created: 1737081059682,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: '조심스러운, 신중한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-9a09',
    created: 1737081069597,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: '마지못해',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Xp3fc',
    created: 1737081070500,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: '',
      example: '',
      definition: '',
      translation: '상당한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
