import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'SS4tg',
    created: 1737080403241,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriteit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9n3Ls',
    created: 1737080413286,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'weerstandkracht',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DDrNq',
    created: 1737080423887,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'drempel, grens, verhoging',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NNOi8',
    created: 1737080443556,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: 'een opzet, beschikking, ontvankelijkheid',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-eKo7',
    created: 1737080453085,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nasleep',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zVF0j',
    created: 1737080472751,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aanval, resultaat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hcC7C',
    created: 1737080492438,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bevestigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qAWWe',
    created: 1737080511579,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'beoordelen, overwegen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LlVzl',
    created: 1737080531769,
    data: {
      language: 'no',
      source: 'vie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'wijden, trouwen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uyOtS',
    created: 1737080541744,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtvaardigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qpcWK',
    created: 1737080561841,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzomer',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'R9dKy',
    created: 1737080581208,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overtuigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iXTO8',
    created: 1737080600548,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geleidelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uA9U9',
    created: 1737080636802,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'impliciet',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Wnj75',
    created: 1737080672929,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bijzonder',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'auO6K',
    created: 1737080692458,
    data: {
      language: 'no',
      source: 'rask',
      ipa: '',
      example: '',
      definition: '',
      translation: 'snel, gezond',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bJ81j',
    created: 1737080720675,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ongeveer',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WdZCb',
    created: 1737080739719,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voldoende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xSF61',
    created: 1737080759179,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voortduren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2Uu7n',
    created: 1737080778519,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omvattend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5uiz4',
    created: 1737080806793,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'heerlijk, prachtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'O6Au4',
    created: 1737080834936,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '37rzw',
    created: 1737080851478,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tegenstribbelend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'V0HQ6',
    created: 1737080870590,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aanzienlijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
