import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8xlR5',
    created: 1737078645045,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'интегритет',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dPYRa',
    created: 1737078655084,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сопротивляемость',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jtSwz',
    created: 1737078683386,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'порог, граница',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5yTj0',
    created: 1737078711343,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: '',
      example: '',
      definition: '',
      translation: 'план, распоряжение, восприятие',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SzhyG',
    created: 1737078712323,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'последствие',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CV0zR',
    created: 1737078731421,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: '',
      example: '',
      definition: '',
      translation: 'выпад, результат',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'keVUE',
    created: 1737078759452,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: '',
      example: '',
      definition: '',
      translation: 'подтверждать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5seeQ',
    created: 1737078796274,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: '',
      example: '',
      definition: '',
      translation: 'оценивать, рассматривать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'S03S3',
    created: 1737078806983,
    data: {
      language: 'no',
      source: 'vie',
      ipa: '',
      example: '',
      definition: '',
      translation: 'освятить, посвятить, сочетать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iZ9-i',
    created: 1737078816777,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'оправдывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YAwZb',
    created: 1737078844467,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'предлето',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iNz_d',
    created: 1737078863613,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: '',
      example: '',
      definition: '',
      translation: 'уговорить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2mZFw',
    created: 1737078900563,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9x3fL',
    created: 1737078911115,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неявный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A_cPY',
    created: 1737078947913,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: '',
      example: '',
      definition: '',
      translation: 'особенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cIdyj',
    created: 1737078967106,
    data: {
      language: 'no',
      source: 'rask',
      ipa: '',
      example: '',
      definition: '',
      translation: 'быстрый, здоровый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3sdDB',
    created: 1737078995510,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: '',
      example: '',
      definition: '',
      translation: 'примерно, около',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'H884o',
    created: 1737079006056,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достаточно',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7LQf8',
    created: 1737079034316,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'продолжать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sBiIU',
    created: 1737079062681,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обширный, значительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jRBYC',
    created: 1737079090604,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'прекрасный, замечательный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'R460y',
    created: 1737079118629,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'осторожно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7iZkt',
    created: 1737079142337,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неохотно',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6fx5z',
    created: 1737079152691,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'значительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
