import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '3oCov',
    created: 1736977409414,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'intégrité',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Vtye7',
    created: 1736977410467,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'résilience',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SXlYB',
    created: 1736977411268,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'frontière, délai, seuil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iUyzk',
    created: 1736977412162,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation:
        "disposition, état d'esprit, disposition à faire quelque chose",
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nze-l',
    created: 1736977412982,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'répercussion, effet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XjESe',
    created: 1736977413823,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'résultat, issue, solution',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oBW6m',
    created: 1736977414557,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconnaître, admettre, accepter',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'py7t-',
    created: 1736977415349,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considérer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rp9yv',
    created: 1736977416097,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'offrir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UBLk9',
    created: 1736977417333,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justifier',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OeB6H',
    created: 1736977418070,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'négligence',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wRK3q',
    created: 1736977418969,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuader',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n04vo',
    created: 1736977419839,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'progressivement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LfcYz',
    created: 1736977420748,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dIUaX',
    created: 1736977421800,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notablement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cUAqs',
    created: 1736977422805,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prêt, immédiat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AgzhJ',
    created: 1736977423604,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'environ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6y09f',
    created: 1736977424515,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suffisant, raisonnable',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lJGRF',
    created: 1736977425957,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistant, durable',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j7lhs',
    created: 1736977426971,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'global, étendu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z1DTK',
    created: 1736977427815,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'délicieux',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i1tTo',
    created: 1736977428626,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prudence, ticket de loterie',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C2qxk',
    created: 1736977429420,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'réticent',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '30lKH',
    created: 1736977430197,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significatif',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
