import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '2J0Pv',
    created: 1736990592672,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'тұтастық, интегритет',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xhuNN',
    created: 1736990593437,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'төзімділік, сабырлылық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'M_LXt',
    created: 1736990594429,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шекара, шек',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UwT59',
    created: 1736990595219,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дайындық, күй',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PBlFg',
    created: 1736990596046,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'әсер, салдар',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lvIU6',
    created: 1736990597192,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QdOBj',
    created: 1736990598000,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'тану, белгілеу',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z9g1h',
    created: 1736990598792,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ескеру, қарастыру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UtQbE',
    created: 1736990599571,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'арнау, багыштау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '82_bg',
    created: 1736990600383,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'негіздеу, ақтау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6i-mk',
    created: 1736990601492,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'босқа жіберу, немқұрайдылық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Pj0sp',
    created: 1736990602238,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сендіру, құлату',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9mKf3',
    created: 1736990603102,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EV_L5',
    created: 1736990603962,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жасырын түрде',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'k9cD_',
    created: 1736990604822,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'айтарлықтай',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EjlPP',
    created: 1736990606038,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дайын',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'td_Xr',
    created: 1736990607009,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шамамен',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IN1Ln',
    created: 1736990608060,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жеткілікті',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C80pg',
    created: 1736990608850,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'тұрақты, табандылық',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z6TXa',
    created: 1736990609701,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қамтитын, кешенді',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UuPVN',
    created: 1736990610742,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дәмді',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TMAqo',
    created: 1736990611644,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сақтық, абайлық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4gb9C',
    created: 1736990612494,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'күмәнді, қарсы',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pH4Mk',
    created: 1736990613751,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'маңызды, мәнді',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
