import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'iVUfa',
    created: 1736980777044,
    data: {
      language: 'pt-PT',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نزاهة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2eCBf',
    created: 1736980777978,
    data: {
      language: 'pt-PT',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مرونة, قدرة على التكيف',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_gwrM',
    created: 1736980779397,
    data: {
      language: 'pt-PT',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حدود, موعد, حد',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vGl-G',
    created: 1736980780912,
    data: {
      language: 'pt-PT',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ترتيب, حالة ذهنية, قبول القيام بشيء',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kEarZ',
    created: 1736980782415,
    data: {
      language: 'pt-PT',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'صدى, أثر',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qfueK',
    created: 1736980784220,
    data: {
      language: 'pt-PT',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نتيجة, نتيجة المنافسة, حل حسابي',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '23uWz',
    created: 1736980785859,
    data: {
      language: 'pt-PT',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'يُعَرِّف, يُقِرّ, يَقبل',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JI0m5',
    created: 1736980787494,
    data: {
      language: 'pt-PT',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'يعتبر, يفكر في',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2nyLr',
    created: 1736980789017,
    data: {
      language: 'pt-PT',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'يقدم',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hDC8d',
    created: 1736980790735,
    data: {
      language: 'pt-PT',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تبرير',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MCJxr',
    created: 1736980792373,
    data: {
      language: 'pt-PT',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إهمال',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'y8QNY',
    created: 1736980793643,
    data: {
      language: 'pt-PT',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إقناع',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Nz2xM',
    created: 1736980795278,
    data: {
      language: 'pt-PT',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تدريجياً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZuLWt',
    created: 1736980796032,
    data: {
      language: 'pt-PT',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ضمنياً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jATBC',
    created: 1736980796943,
    data: {
      language: 'pt-PT',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بشكل ملحوظ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sYl18',
    created: 1736980799493,
    data: {
      language: 'pt-PT',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'جاهز, سريع',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'b5z_P',
    created: 1736980801001,
    data: {
      language: 'pt-PT',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حوالي',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YuY6A',
    created: 1736980802533,
    data: {
      language: 'pt-PT',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'كافٍ, معتدل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BC6Aa',
    created: 1736980804083,
    data: {
      language: 'pt-PT',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مُثابر, مستمر',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MRWjb',
    created: 1736980804927,
    data: {
      language: 'pt-PT',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شامل, واسع',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Hby-y',
    created: 1736980807620,
    data: {
      language: 'pt-PT',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'لذيذ',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cRBWq',
    created: 1736980809206,
    data: {
      language: 'pt-PT',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حذر, تذكرة يانصيب',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pS78R',
    created: 1736980810997,
    data: {
      language: 'pt-PT',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مُتَرَدِّد',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 't4Vx2',
    created: 1736980813299,
    data: {
      language: 'pt-PT',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'دال, معبر',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
