import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'QJUO0',
    created: 1736989512620,
    data: {
      language: 'pt-PT',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriti',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'P9SHI',
    created: 1736989513703,
    data: {
      language: 'pt-PT',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ketahanan, daya tahan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'e6ARB',
    created: 1736989515002,
    data: {
      language: 'pt-PT',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sempadan, had, batas',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EXfLH',
    created: 1736989517960,
    data: {
      language: 'pt-PT',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'susunan, keadaan fikiran, kesediaan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'D7Z8s',
    created: 1736989519297,
    data: {
      language: 'pt-PT',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reaksi, kesan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JY9DS',
    created: 1736989521124,
    data: {
      language: 'pt-PT',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil, keputusan, jawapan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'F6L_y',
    created: 1736989522591,
    data: {
      language: 'pt-PT',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengenali, mengakui, menerima',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8n5O-',
    created: 1736989524023,
    data: {
      language: 'pt-PT',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YNOb2',
    created: 1736989525834,
    data: {
      language: 'pt-PT',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedikasi',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8JZpR',
    created: 1736989527301,
    data: {
      language: 'pt-PT',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membenarkan, menjelaskan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wfwAX',
    created: 1736989529038,
    data: {
      language: 'pt-PT',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kelalaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2qrxU',
    created: 1736989530474,
    data: {
      language: 'pt-PT',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'memujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3i0yp',
    created: 1736989532156,
    data: {
      language: 'pt-PT',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara beransur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ai_69',
    created: 1736989533008,
    data: {
      language: 'pt-PT',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara tersirat',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2Qr_c',
    created: 1736989533853,
    data: {
      language: 'pt-PT',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara ketara',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2yLH5',
    created: 1736989535799,
    data: {
      language: 'pt-PT',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'siap, cepat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CO-9X',
    created: 1736990483508,
    data: {
      language: 'pt-PT',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kira-kira',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zR6te',
    created: 1736990488086,
    data: {
      language: 'pt-PT',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup, memadai',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Wm5GN',
    created: 1736990489593,
    data: {
      language: 'pt-PT',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bertekun, kekal',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vIalZ',
    created: 1736990490593,
    data: {
      language: 'pt-PT',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menyeluruh, komprehensif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EfJW4',
    created: 1736990493325,
    data: {
      language: 'pt-PT',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lezat',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '04at1',
    created: 1736990494892,
    data: {
      language: 'pt-PT',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hati-hati, kupon loteri',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Dcgg5',
    created: 1736990496039,
    data: {
      language: 'pt-PT',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ragu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ycdAn',
    created: 1736990497734,
    data: {
      language: 'pt-PT',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikan',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
