import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '14Nrw',
    created: 1736977431728,
    data: {
      language: 'pt-PT',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Integrität',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gw0cW',
    created: 1736977432507,
    data: {
      language: 'pt-PT',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Resilienz',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fs55h',
    created: 1736977434377,
    data: {
      language: 'pt-PT',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Grenze, Frist',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nuzFU',
    created: 1736977436039,
    data: {
      language: 'pt-PT',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Anordnung, Stimmung, Bereitschaft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'McCjR',
    created: 1736977437355,
    data: {
      language: 'pt-PT',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Widerhall, Auswirkung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M1ACz',
    created: 1736977438966,
    data: {
      language: 'pt-PT',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Folge, Ergebnis, Lösung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lxdQN',
    created: 1736977440564,
    data: {
      language: 'pt-PT',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkennen, zugeben, akzeptieren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BNtmq',
    created: 1736977442491,
    data: {
      language: 'pt-PT',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'betrachten, erwägen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j7scR',
    created: 1736977443938,
    data: {
      language: 'pt-PT',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'widmen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hXsBP',
    created: 1736977445480,
    data: {
      language: 'pt-PT',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtfertigen, begründen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vSqtH',
    created: 1736977446901,
    data: {
      language: 'pt-PT',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Nachlässigkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BZc5V',
    created: 1736977448360,
    data: {
      language: 'pt-PT',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'überzeugen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1hFFN',
    created: 1736977449736,
    data: {
      language: 'pt-PT',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'allmählich',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9b73B',
    created: 1736977450459,
    data: {
      language: 'pt-PT',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implizit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UORXY',
    created: 1736977451204,
    data: {
      language: 'pt-PT',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bemerkenswert, auffallend',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TI469',
    created: 1736977453154,
    data: {
      language: 'pt-PT',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'fertig, schnell',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VflvS',
    created: 1736977454574,
    data: {
      language: 'pt-PT',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefähr',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8IoOp',
    created: 1736977456126,
    data: {
      language: 'pt-PT',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ausreichend, genügend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7R9cM',
    created: 1736977467146,
    data: {
      language: 'pt-PT',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hartnäckig, beständig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EShHm',
    created: 1736977476991,
    data: {
      language: 'pt-PT',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umfassend, weitreichend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sON5M',
    created: 1736977496414,
    data: {
      language: 'pt-PT',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lecker, köstlich',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-nPA1',
    created: 1736977515594,
    data: {
      language: 'pt-PT',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Vorsicht, Lottoschein',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'F9jwc',
    created: 1736977534667,
    data: {
      language: 'pt-PT',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zögerlich, widerwillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WWqpV',
    created: 1736977563235,
    data: {
      language: 'pt-PT',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bedeutend',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
