import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'HXCTi',
    created: 1736980764935,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sC9w3',
    created: 1736980765092,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliência',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6Hl2Z',
    created: 1736980765237,
    data: {
      language: 'pt',
      source: 'limitado',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UllcF',
    created: 1736980765380,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HKyfD',
    created: 1736980765532,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YJAga',
    created: 1736980765716,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mi2IT',
    created: 1736980765898,
    data: {
      language: 'pt',
      source: 'reconhecido',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0X_v7',
    created: 1736980766034,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'q30am',
    created: 1736980766243,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8md85',
    created: 1736980766573,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ccm1r',
    created: 1736980766906,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3wSyr',
    created: 1736980767265,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OhslX',
    created: 1736980767604,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zfpl-',
    created: 1736980767862,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitamente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'urcnw',
    created: 1736980768220,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notavelmente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-IBMG',
    created: 1736980768534,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VDPEd',
    created: 1736980768876,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0LF9q',
    created: 1736980769216,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UKFIa',
    created: 1736980769566,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '79O9E',
    created: 1736980769870,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'abrangente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c_3FL',
    created: 1736980770225,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QULWx',
    created: 1736980770584,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gxTkM',
    created: 1736980770883,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tgjB_',
    created: 1736980771237,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
