import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'gzyxi',
    created: 1736988424498,
    data: {
      language: 'pt-PT',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integritas',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OaUlh',
    created: 1736988425396,
    data: {
      language: 'pt-PT',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ketahanan, resiliensi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UyF9B',
    created: 1736988430754,
    data: {
      language: 'pt-PT',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'batas, batas waktu, batasan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZuclP',
    created: 1736988432225,
    data: {
      language: 'pt-PT',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'pengaturan, keadaan pikiran, kesediaan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kXs3H',
    created: 1736988433732,
    data: {
      language: 'pt-PT',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gema, dampak',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sHUup',
    created: 1736988435220,
    data: {
      language: 'pt-PT',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil, konsekuensi, solusi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6q0kY',
    created: 1736988436839,
    data: {
      language: 'pt-PT',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengidentifikasi, mengakui, menerima',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OWaHv',
    created: 1736988438399,
    data: {
      language: 'pt-PT',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vcLG5',
    created: 1736988439809,
    data: {
      language: 'pt-PT',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedikasikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CtIfd',
    created: 1736988441337,
    data: {
      language: 'pt-PT',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membenarkan, menjelaskan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'r2tTG',
    created: 1736988442543,
    data: {
      language: 'pt-PT',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kelalaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6DlPY',
    created: 1736988444180,
    data: {
      language: 'pt-PT',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NKYg0',
    created: 1736989405137,
    data: {
      language: 'pt-PT',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara bertahap',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LhyZc',
    created: 1736989406377,
    data: {
      language: 'pt-PT',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara implisit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kQ6NW',
    created: 1736989407160,
    data: {
      language: 'pt-PT',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara mencolok, dengan jelas',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'y17V-',
    created: 1736989408807,
    data: {
      language: 'pt-PT',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'siap, cepat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wmf7d',
    created: 1736989410228,
    data: {
      language: 'pt-PT',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sekitar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qDFxp',
    created: 1736989501877,
    data: {
      language: 'pt-PT',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup, memadai',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Egcct',
    created: 1736989503661,
    data: {
      language: 'pt-PT',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gigih, tahan lama',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'T9T1m',
    created: 1736989504877,
    data: {
      language: 'pt-PT',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'komprehensif, menyeluruh',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '87T2O',
    created: 1736989506313,
    data: {
      language: 'pt-PT',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'lezat, enak',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NBmRO',
    created: 1736989508048,
    data: {
      language: 'pt-PT',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perhatian, kupon lotere',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'O9_tw',
    created: 1736989509432,
    data: {
      language: 'pt-PT',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ragu, enggan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'apb8t',
    created: 1736989511251,
    data: {
      language: 'pt-PT',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikan',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
