import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'XjSOA',
    created: 1736977372261,
    data: {
      language: 'pt-PT',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridad',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VqKi0',
    created: 1736977373271,
    data: {
      language: 'pt-PT',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AhZi3',
    created: 1736977375313,
    data: {
      language: 'pt-PT',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'límite, plazo, frontera',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KT3mt',
    created: 1736977376599,
    data: {
      language: 'pt-PT',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposición, estado de ánimo, disposición a hacer algo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3tdPl',
    created: 1736977378535,
    data: {
      language: 'pt-PT',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'repercusión, efecto',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Q2Mjy',
    created: 1736977380558,
    data: {
      language: 'pt-PT',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, consecuencia, solución',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vMKE_',
    created: 1736977382946,
    data: {
      language: 'pt-PT',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconocer, admitir, aceptar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wQvIL',
    created: 1736977384152,
    data: {
      language: 'pt-PT',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar, pensar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S4hHS',
    created: 1736977385607,
    data: {
      language: 'pt-PT',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vxubG',
    created: 1736977387070,
    data: {
      language: 'pt-PT',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justificar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0Mpr5',
    created: 1736977388298,
    data: {
      language: 'pt-PT',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negligencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Su3_i',
    created: 1736977389550,
    data: {
      language: 'pt-PT',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuadir, convencer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9kb8D',
    created: 1736977390873,
    data: {
      language: 'pt-PT',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente, progresivamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fBZAg',
    created: 1736977391714,
    data: {
      language: 'pt-PT',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícitamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd9WsC',
    created: 1736977392560,
    data: {
      language: 'pt-PT',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notablemente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FtCFs',
    created: 1736977394100,
    data: {
      language: 'pt-PT',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'listo, preparado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-tiQP',
    created: 1736977395444,
    data: {
      language: 'pt-PT',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente, cerca de',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vwIt0',
    created: 1736977397129,
    data: {
      language: 'pt-PT',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente, adecuado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4HeEl',
    created: 1736977398585,
    data: {
      language: 'pt-PT',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente, tenaz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yIUTU',
    created: 1736977399548,
    data: {
      language: 'pt-PT',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'amplio, extenso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zxW6X',
    created: 1736977401974,
    data: {
      language: 'pt-PT',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'delicioso',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GhDn4',
    created: 1736977403881,
    data: {
      language: 'pt-PT',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cuidado, fracción de billete de lotería',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mx7tF',
    created: 1736977405753,
    data: {
      language: 'pt-PT',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reacio, reticente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4y4UG',
    created: 1736977408175,
    data: {
      language: 'pt-PT',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significativo',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
