import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'EH53g',
    created: 1736988337110,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความซื่อสัตย์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4I8gj',
    created: 1736988338159,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความยืดหยุ่น',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MHNza',
    created: 1736988340209,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: 'เส้นแบ่ง, กำหนดเวลา, จุดที่ไม่ควรข้าม',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LDCIG',
    created: 1736988342008,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การจัดเรียง, อารมณ์, ความเต็มใจ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NTVrU',
    created: 1736988343828,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การสะท้อน, ผลกระทบ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-xAhk',
    created: 1736988347547,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ผลลัพธ์, ผลการแข่งขัน, ผลการคำนวณ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JHKdZ',
    created: 1736988349407,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ระบุ, ยอมรับ, รับรู้',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C4xzG',
    created: 1736988350710,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4qlfc',
    created: 1736988352087,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'มอบให้',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vV0_C',
    created: 1736988354646,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ชี้แจง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TjF6f',
    created: 1736988356500,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความประมาท',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QNb0E',
    created: 1736988357902,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ชักชวน',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TyniL',
    created: 1736988359809,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทีละน้อย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ksBFC',
    created: 1736988360770,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยนัย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Wg_C3',
    created: 1736988362219,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างเด่นชัด',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KePYj',
    created: 1736988364467,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'เสร็จ, พร้อม',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jm33l',
    created: 1736988365913,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XeKR9',
    created: 1736988369117,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'เพียงพอ, พอสมควร',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8tF8w',
    created: 1736988370919,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ดื้อรั้น, คงทน',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vSrO5',
    created: 1736988371999,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ครอบคลุม',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bRAJA',
    created: 1736988373515,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อร่อย',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DsEOi',
    created: 1736988376085,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความระมัดระวัง, ตั๋วลอตเตอรี่',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1Uw66',
    created: 1736988377311,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ลังเล',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pAvTv',
    created: 1736988378956,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: 'มีความหมาย',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
