import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'EGYPY',
    created: 1736978065578,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: '',
      example: '',
      definition: '',
      translation: '誠實, 正直',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xRmHH',
    created: 1736978075308,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: '韌性, 彈性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-nSUU',
    created: 1736978103284,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: '',
      example: '',
      definition: '',
      translation: '邊界, 期限, 界限',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4b02n',
    created: 1736978122659,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: '',
      example: '',
      definition: '',
      translation: '安排, 心情, 接受',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AlJlX',
    created: 1736978133516,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: '',
      example: '',
      definition: '',
      translation: '回響, 影響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8fy6q',
    created: 1736978161539,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, 比賽結果, 計算結果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZNU4W',
    created: 1736978189968,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: '',
      example: '',
      definition: '',
      translation: '認出, 承認, 接受',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'L7yTS',
    created: 1736978209291,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮, 認為',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '96xXs',
    created: 1736978219737,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉獻',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Lkn2E',
    created: 1736978238828,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: '',
      example: '',
      definition: '',
      translation: '解釋, 辯解',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Y0rbI',
    created: 1736978267086,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: '',
      example: '',
      definition: '',
      translation: '疏忽, 忽視',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NQeDf',
    created: 1736978286499,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: '',
      example: '',
      definition: '',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N9Czj',
    created: 1736978305650,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐漸',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kNW0a',
    created: 1736978306603,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗示地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p4HzX',
    created: 1736978316411,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '顯著地, 明顯地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZAqub',
    created: 1736978344763,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: '',
      example: '',
      definition: '',
      translation: '完成, 迅速',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_3D2e',
    created: 1736978373085,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '大約',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S4m7q',
    created: 1736978401544,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: '',
      example: '',
      definition: '',
      translation: '足夠的, 適度的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GIKoi',
    created: 1736978420894,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: '',
      example: '',
      definition: '',
      translation: '堅持的, 持久的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm0AjC',
    created: 1736978430870,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: '廣泛的, 包羅萬象的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bCB5I',
    created: 1736978458706,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: '',
      example: '',
      definition: '',
      translation: '美味',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Fzn3k',
    created: 1736978478147,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: '',
      example: '',
      definition: '',
      translation: '小心, 彩票票根',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-cqyj',
    created: 1736978489199,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: '',
      example: '',
      definition: '',
      translation: '猶豫的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iEcZd',
    created: 1736978517465,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的, 顯著的',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
