import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'iaGMj',
    created: 1737063012103,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Integrität, Ehrlichkeit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WDbLR',
    created: 1737063013174,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Elastizität',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JsyV-',
    created: 1737063023004,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Schwelle, Beginn, Untergrenze',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yJA19',
    created: 1737063032805,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Verfügung, Gliederung, Anlage',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yn9Sw',
    created: 1737063042564,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Rückwirkung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6CNlx',
    created: 1737063052531,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Ergebnis',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MbIi4',
    created: 1737063062503,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'anerkennen, zugeben, akzeptieren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QbF2o',
    created: 1737063072515,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'überlegen, vorherrschen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H6sgO',
    created: 1737063091766,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'widmen, zuwenden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'B9kJ3',
    created: 1737063101502,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtfertigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LMP_M',
    created: 1737063130135,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Vernachlässigung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'J49JA',
    created: 1737063139874,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'überzeugen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JBOmx',
    created: 1737063149482,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'allmählich',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3J6s_',
    created: 1737063159957,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implizit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3YOJ-',
    created: 1737063160792,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'insbesondere',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mDTi6',
    created: 1737063170368,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sofort',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nfgyN',
    created: 1737063180096,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefähr, circa',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H16FB',
    created: 1737063189828,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ausreichend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9Vvd3',
    created: 1737063209093,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'beständig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PkR8l',
    created: 1737063228550,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'umfassend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tczme',
    created: 1737063247775,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'herrlich, wunderbar',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VqCpk',
    created: 1737063266290,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vorsichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ceJD8',
    created: 1737063276166,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'widerwillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'la7GE',
    created: 1737063286161,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikant, bedeutend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
