import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '_rf01',
    created: 1737071598791,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ακεραιότητα, ιδιωτικότητα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'v3O2x',
    created: 1737071608596,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ελαστικότητα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'W5LcH',
    created: 1737071619281,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'κατώφλι, αρχή, κατώφλι αποτελέσματος',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XlquK',
    created: 1737071638364,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'διάθεση, διάταξη, κλίση',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RTg0X',
    created: 1737071667300,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αντίκτυπος',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QOnFg',
    created: 1737071686457,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αποτέλεσμα',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Dq_cq',
    created: 1737071705853,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αναγνωρίζω, παραδέχομαι',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RxKhV',
    created: 1737071733991,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σκεφτώ, υπερτερώ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EaBXY',
    created: 1737071762029,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αφιερώνομαι, είμαι κατάλληλος για',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mE8r1',
    created: 1737071789993,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'δικαιολογώ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vXTna',
    created: 1737071809357,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: '',
      example: '',
      definition: '',
      translation: 'παράλειψη',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-UMcz',
    created: 1737071837488,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'πειθώ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dJNum',
    created: 1737071856972,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σταδιακά',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'U2jU7',
    created: 1737071869311,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'υπονοούμενος',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gzlv8',
    created: 1737071870473,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ιδίως, κυρίως',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TTPjV',
    created: 1737071898641,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '',
      example: '',
      definition: '',
      translation: 'άμεσα',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'u5LU5',
    created: 1737071926949,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: '',
      example: '',
      definition: '',
      translation: 'περίπου',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 't4M23',
    created: 1737071937742,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'αρκετός',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Skye-',
    created: 1737071967109,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σταθερός',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MMKBc',
    created: 1737071995403,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'εκτενής',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8ukm0',
    created: 1737072024098,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'υπέροχος',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BIS1p',
    created: 1737072043516,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'προσεκτικός',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3b6DM',
    created: 1737072062877,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'απρόθυμος',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'T3ecL',
    created: 1737072082328,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'σημαντικός, σημαντική',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
