import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'zvXB-',
    created: 1737065392366,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integrità, riservatezza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eYdNg',
    created: 1737065402212,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elasticità',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jAKyp',
    created: 1737065422475,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'soglia, inizio, limite inferiore',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qah09',
    created: 1737065433643,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposizione, pianificazione, predisposizione',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kR_oM',
    created: 1737065461546,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'repercussione',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5UtbQ',
    created: 1737065480857,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'risultato',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9iB7i',
    created: 1737065509069,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ammettere, riconoscere, accettare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5oMqa',
    created: 1737065528357,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerare, prendere in considerazione',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BXmKw',
    created: 1737065556203,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicare, riservare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'OwTLx',
    created: 1737065584679,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'giustificare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'O6ug8',
    created: 1737065613250,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negligenza',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Xs_Nl',
    created: 1737065632472,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'convincere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MM4a-',
    created: 1737065651699,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xW18E',
    created: 1737065661453,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicito',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yHOeV',
    created: 1737065671613,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'in particolare',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wjAPh',
    created: 1737065690817,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '',
      example: '',
      definition: '',
      translation: 'immediatamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SnOkQ',
    created: 1737065719030,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: '',
      example: '',
      definition: '',
      translation: 'circa',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_yXng',
    created: 1737065738055,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficiente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IzZwN',
    created: 1737065766352,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resistente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wldNO',
    created: 1737065794622,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ampio, esteso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'f0F5S',
    created: 1737065814443,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'delizioso, piacevole',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uMl_3',
    created: 1737065842304,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cauto, attento',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YaeEO',
    created: 1737065861349,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'riluttante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4Aibt',
    created: 1737065881358,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significativo, notevole',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
