import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ry39X',
    created: 1737067475749,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: '개인정보 보호, 정직',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0vPPL',
    created: 1737067485418,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: '탄력성',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Wuloo',
    created: 1737067513393,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '',
      example: '',
      definition: '',
      translation: '문턱, 시작, 하한선',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ObbFr',
    created: 1737067523983,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: '처분권, 구성 계획, 소질',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-l7-l',
    created: 1737067551939,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '',
      example: '',
      definition: '',
      translation: '영향',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ryNN_',
    created: 1737067571398,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: '결과',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SghRn',
    created: 1737067599448,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '',
      example: '',
      definition: '',
      translation: '인정하다, 허용하다, 수용하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NUZK4',
    created: 1737067636109,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: '고려하다, 우선하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AYA_S',
    created: 1737067663993,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '',
      example: '',
      definition: '',
      translation: '할애하다, 전념하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vL9Tu',
    created: 1737067691805,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '',
      example: '',
      definition: '',
      translation: '정당화하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qvuJs',
    created: 1737067728885,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: '',
      example: '',
      definition: '',
      translation: '무시, 태만',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FJ9ys',
    created: 1737067756737,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '',
      example: '',
      definition: '',
      translation: '확신시키다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '120ml',
    created: 1737067785005,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: '점진적으로',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IfUUg',
    created: 1737067803327,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '암시적인, 내포된',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'a_nm8',
    created: 1737067813299,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: '특히',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0ULsk',
    created: 1737067841317,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '',
      example: '',
      definition: '',
      translation: '즉시',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RcO6F',
    created: 1737067860370,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: '',
      example: '',
      definition: '',
      translation: '약, 대략',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'btjgT',
    created: 1737067879427,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '',
      example: '',
      definition: '',
      translation: '충분한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ShwfI',
    created: 1737067908531,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: '',
      example: '',
      definition: '',
      translation: '지속적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '40jR3',
    created: 1737067936555,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '',
      example: '',
      definition: '',
      translation: '광범위한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GBk-Z',
    created: 1737067965125,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '',
      example: '',
      definition: '',
      translation: '아름다운, 즐거운',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ctmkZ',
    created: 1737067993187,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: '조심스러운, 신중한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gcoMa',
    created: 1737068012361,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: '마지못해',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vrZiQ',
    created: 1737068031583,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: '상당한, 중요한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
