import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZxtOy',
    created: 1737072604930,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความเป็นส่วนตัว, ความซื่อสัตย์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bXv24',
    created: 1737072614843,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความยืดหยุ่น',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Wz0Sc',
    created: 1737072634682,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ธรณี, จุดเริ่มต้น, ขีดต่ำสุด',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'o825n',
    created: 1737072654343,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การจัดการ, การวางแผน',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ygxY5',
    created: 1737072673722,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ผลกระทบ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LPM2g',
    created: 1737072692941,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ผลลัพธ์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '22XyB',
    created: 1737072721408,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ยอมรับ, รับรอง, อนุญาต',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9dtUE',
    created: 1737072749512,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'พิจารณา, เหนือกว่า',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RHm_D',
    created: 1737072769311,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '',
      example: '',
      definition: '',
      translation: 'มอบหมาย, เหมาะสมสำหรับ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JrtmX',
    created: 1737072797501,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'พิสูจน์ความถูกต้อง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sJdN2',
    created: 1737072826487,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การละเลย',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MVoV8',
    created: 1737072855053,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โน้มน้าว',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'b871S',
    created: 1737072874430,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทีละน้อย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9PrA0',
    created: 1737072884067,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยนัย',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bbKXP',
    created: 1737072894122,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยเฉพาะ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uENGn',
    created: 1737072922336,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทันที',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zLUfa',
    created: 1737072942085,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'b3hS5',
    created: 1737072961344,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'เพียงพอ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gs1ev',
    created: 1737072991704,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'คงทน',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hY_fQ',
    created: 1737073010961,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'กว้างขวาง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'C9rMl',
    created: 1737073039634,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'น่ารัก',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'amzoa',
    created: 1737073068044,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ระมัดระวัง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pEuZ6',
    created: 1737073078824,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ไม่เต็มใจ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6BDXg',
    created: 1737073099355,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: '',
      example: '',
      definition: '',
      translation: 'สำคัญ, มีนัยสำคัญ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
