import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Y8GSs',
    created: 1737057006380,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: 'helhed',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yT8Pw',
    created: 1737057016010,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'holdbarhed',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JjKAF',
    created: 1737057026759,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dørtrin, startpunkt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zbrZN',
    created: 1737057055634,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tendens',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9kVOD',
    created: 1737057074539,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ekko, respons',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'w512L',
    created: 1737057094138,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat, udfald, konklusion',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vT-pL',
    created: 1737057094985,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'acceptere, tage imod',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JTQfI',
    created: 1737057104981,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tage hensyn til',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qMZlT',
    created: 1737057114844,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedikere, afgive',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '96-yf',
    created: 1737057124760,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsvare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'y1kp3',
    created: 1737057134692,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'forsømme',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'n6pVc',
    created: 1737057152833,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overbevise',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '01h8v',
    created: 1737057189915,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: '',
      example: '',
      definition: '',
      translation: 'stadig mere',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'irboI',
    created: 1737057199673,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indirekte',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FUAHh',
    created: 1737057227707,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'især',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'P6nyW',
    created: 1737057246798,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: '',
      example: '',
      definition: '',
      translation: 'straks',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mfDsb',
    created: 1737057274680,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'groft, omtrent, stort',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rtHA2',
    created: 1737057302713,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tilstrækkeligt',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H0n4J',
    created: 1737057321872,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'permanent, varig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gA-JF',
    created: 1737057331524,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inkluderende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8R15U',
    created: 1737057359664,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: '',
      example: '',
      definition: '',
      translation: 'behagelig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5mgQJ',
    created: 1737057377947,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omhyggelig',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1hNJm',
    created: 1737057406644,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sZQuW',
    created: 1737057426115,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vigtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
