import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'vNFTa',
    created: 1737056250149,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: 'helhet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'K8cnq',
    created: 1737056261170,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hållfasthet, motståndskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NrNuy',
    created: 1737056280541,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tröskel, startpunkt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'x7OFL',
    created: 1737056290904,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tendens',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Dx6K4',
    created: 1737056310475,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ekon, respons',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jlcUa',
    created: 1737056329598,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat, utfall, slut',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VweI_',
    created: 1737056339198,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'acceptera, erkänna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'U_lrS',
    created: 1737056357319,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ta hänsyn till',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'B1hPV',
    created: 1737056367053,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ägnar, offra',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UbOd_',
    created: 1737056376660,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försvara',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'D_gG_',
    created: 1737056377564,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försummar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5Rwot',
    created: 1737056387309,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LZLkc',
    created: 1737056406295,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: '',
      example: '',
      definition: '',
      translation: 'allt mer',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0uGfd',
    created: 1737056416112,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indirekt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6QxFu',
    created: 1737056444091,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: '',
      example: '',
      definition: '',
      translation: 'särskilt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hhZOl',
    created: 1737056455279,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omedelbart',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0PMYj',
    created: 1737056483904,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'grovt, ungefär, stort',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4JVvN',
    created: 1737056520881,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräckligt',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dH2Xw',
    created: 1737056540655,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'permanent, bestående',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'S9PBD',
    created: 1737056541681,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inkluderande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'r-98Q',
    created: 1737056569610,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: '',
      example: '',
      definition: '',
      translation: 'trevlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '34JK7',
    created: 1737056579365,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försiktig, uppmärksam',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2Eo1B',
    created: 1737056607583,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cv4Po',
    created: 1737056626737,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'viktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
