import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'il1tS',
    created: 1737052738303,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: '完整, 整體',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'T2cMa',
    created: 1737052748000,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: '耐久性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nT_xU',
    created: 1737052758503,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: '',
      example: '',
      definition: '',
      translation: '門檻, 起點',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tqQry',
    created: 1737052777576,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: '',
      example: '',
      definition: '',
      translation: '傾向',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'skA96',
    created: 1737052796625,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: '',
      example: '',
      definition: '',
      translation: '回音, 反響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ft3x6',
    created: 1737052816223,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: '',
      example: '',
      definition: '',
      translation: '結果, 成果, 結尾',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tw6UF',
    created: 1737052825947,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '接受, 認可',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BSvxb',
    created: 1737052827019,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮, 重視',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wK683',
    created: 1737052836630,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: '獻身, 奉獻',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'V_vQK',
    created: 1737052846870,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: '辯護, 防衛',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vrxON',
    created: 1737052856456,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽視, 疏忽',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lvjGn',
    created: 1737052866310,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-Hrzg',
    created: 1737052893982,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐漸',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-1W1M',
    created: 1737052903764,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: '間接地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '099MT',
    created: 1737052923096,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: '',
      example: '',
      definition: '',
      translation: '特別地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pBTap',
    created: 1737052942140,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'clMgn',
    created: 1737052970096,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '',
      definition: '',
      translation: '粗略地, 大致, 粗大',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'c5KCK',
    created: 1737052998151,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: '',
      example: '',
      definition: '',
      translation: '足夠',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Am-1_',
    created: 1737053008516,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: '持久的, 永久的, 常駐的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KuB1T',
    created: 1737053023704,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: '包容的, 涵蓋的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UPU8G',
    created: 1737053052690,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'X7nFH',
    created: 1737053062555,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: '小心, 謹慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'W1egt',
    created: 1737053090720,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情願',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uZJjo',
    created: 1737053110275,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
