import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'R6oBp',
    created: 1736963839544,
    data: {
      language: 'zh',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'صادق',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'msviN',
    created: 1736963841003,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مرونة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_ZCqB',
    created: 1736963842022,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نقطة حرجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pL4Tu',
    created: 1736963843538,
    data: {
      language: 'zh',
      source: '处置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إدارة, تدبير',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jVQl3',
    created: 1736963846559,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'صدى, رد فعل',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Nw4Fx',
    created: 1736963848145,
    data: {
      language: 'zh',
      source: '结果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نتيجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AEiaz',
    created: 1736963849784,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'اعترف',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd7yrB',
    created: 1736963851724,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: '',
      example: '',
      definition: '',
      translation: 'يفكر',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eV7J9',
    created: 1736963852657,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تضحية, إخلاص',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TA6r6',
    created: 1736963854004,
    data: {
      language: 'zh',
      source: '合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'قانوني',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rue6E',
    created: 1736963855629,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تجاهل',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LIMtN',
    created: 1736963857187,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إقناع',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vFanu',
    created: 1736963859034,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تدريجياً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8XRJt',
    created: 1736963860646,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'في كل مكان',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0s688',
    created: 1736963862178,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصاً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oPQbI',
    created: 1736963864145,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'في الوقت المناسب',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r2nKb',
    created: 1736963865122,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقريباً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5Fr95',
    created: 1736963866417,
    data: {
      language: 'zh',
      source: '足够',
      ipa: '',
      example: '',
      definition: '',
      translation: 'كافٍ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Nj9vi',
    created: 1736963868808,
    data: {
      language: 'zh',
      source: '执着',
      ipa: '',
      example: '',
      definition: '',
      translation: 'متمسك, مصرّ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dDG5A',
    created: 1736963871193,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تدريب',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5npOC',
    created: 1736963872714,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ممتع, سعيد',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Lpjpg',
    created: 1736963873645,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حذر',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jLB03',
    created: 1736963875590,
    data: {
      language: 'zh',
      source: '不等',
      ipa: '',
      example: '',
      definition: '',
      translation: 'غير متساوي',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VFLDP',
    created: 1736963877179,
    data: {
      language: 'zh',
      source: '重要',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مهم',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
