import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'wZY2O',
    created: 1736963526409,
    data: {
      language: 'zh',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'honesto, justo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZR0oF',
    created: 1736963528451,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elasticidad',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ysOJB',
    created: 1736963529354,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'punto crítico',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZTH9n',
    created: 1736963531271,
    data: {
      language: 'zh',
      source: '处置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gestionar, disponer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WCamP',
    created: 1736963532125,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eco, respuesta',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xMVMq',
    created: 1736963533686,
    data: {
      language: 'zh',
      source: '结果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cu5F2',
    created: 1736963536442,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconocer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sKSeU',
    created: 1736963537807,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CvSRs',
    created: 1736963538623,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicación, ofrenda',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QXaCl',
    created: 1736963540910,
    data: {
      language: 'zh',
      source: '合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'legal',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nf2VH',
    created: 1736963542736,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ignorar, desatender',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3S5Hh',
    created: 1736963544136,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuasión',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YAEj1',
    created: 1736963545624,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qnkPi',
    created: 1736963548783,
    data: {
      language: 'zh',
      source: '地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tierra, suelo',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LNWCh',
    created: 1736963554641,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'especialmente, particularmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'em5CE',
    created: 1736963556007,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'a tiempo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O2QA3',
    created: 1736963560439,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente, más o menos',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3k99R',
    created: 1736963561770,
    data: {
      language: 'zh',
      source: '足够',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rNNVo',
    created: 1736963564200,
    data: {
      language: 'zh',
      source: '执着',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente, tenaz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_9GUU',
    created: 1736963565932,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'práctica',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NGn53',
    created: 1736963566787,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'agradable, feliz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zbKmA',
    created: 1736963567690,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cautela, precaución',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lEsw5',
    created: 1736963570341,
    data: {
      language: 'zh',
      source: '不等',
      ipa: '',
      example: '',
      definition: '',
      translation: 'desigual, diferente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ly5Ra',
    created: 1736963576786,
    data: {
      language: 'zh',
      source: '重要',
      ipa: '',
      example: '',
      definition: '',
      translation: 'importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
