import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'OXdbp',
    created: 1736964604533,
    data: {
      language: 'zh',
      source: 'zhen zhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'нағыз',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7-NfQ',
    created: 1736964605487,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'серпімділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sbt5H',
    created: 1736964606478,
    data: {
      language: 'zh',
      source: 'limjiet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'лимит',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rHBII',
    created: 1736964607584,
    data: {
      language: 'zh',
      source: 'chuzhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'белгілеу, тағайындау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IaafS',
    created: 1736964608477,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'реакция, жауап',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9owE5',
    created: 1736964609472,
    data: {
      language: 'zh',
      source: 'нәтиже',
      ipa: '',
      example: '',
      definition: '',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ADXqt',
    created: 1736964611027,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'мойындау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D-UjJ',
    created: 1736964611765,
    data: {
      language: 'zh',
      source: 'қарастыру',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қарастыру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SCnJU',
    created: 1736964612855,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'арнау, құрбандық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oik13',
    created: 1736964614156,
    data: {
      language: 'zh',
      source: 'дәлелдеу заңды',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дәлелдеу, заңды',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YJ9s4',
    created: 1736964615032,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ескерме',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A0-kG',
    created: 1736964615947,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сендіру',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PQH0G',
    created: 1736964620095,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'біртіндеп',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sYzE3',
    created: 1736964622181,
    data: {
      language: 'zh',
      source: 'yinhande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жасырын',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lNFZh',
    created: 1736964623233,
    data: {
      language: 'zh',
      source: '尤为',
      ipa: '',
      example: '',
      definition: '',
      translation: 'әсіресе',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SWhb1',
    created: 1736964623998,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'уақытында',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '13A-L',
    created: 1736964624856,
    data: {
      language: 'zh',
      source: 'dazhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дәл, нақты',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AQFxl',
    created: 1736964626838,
    data: {
      language: 'zh',
      source: '勃勃',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жанды, белсенді',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JDpgz',
    created: 1736964628258,
    data: {
      language: 'zh',
      source: 'zharqyn',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жарқын',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RNAYQ',
    created: 1736964629572,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'стажировка',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hITWR',
    created: 1736964630514,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қуанышты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OxRKG',
    created: 1736964631637,
    data: {
      language: 'zh',
      source: '基金',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қор',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gPxAw',
    created: 1736964633687,
    data: {
      language: 'zh',
      source: '必备',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қажет, міндетті',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n825G',
    created: 1736964634652,
    data: {
      language: 'zh',
      source: '吗',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ма',
      partOfSpeech: 'particle',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
