import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'uR89U',
    created: 1736963796554,
    data: {
      language: 'zh',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justo, honesto',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aJx7w',
    created: 1736963798180,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elasticidade',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tMQDZ',
    created: 1736963799173,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ponto crítico, ponto de transição',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '74oec',
    created: 1736963800840,
    data: {
      language: 'zh',
      source: '处置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gerir, dispor',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1pWul',
    created: 1736963801840,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eco, resposta',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3nusu',
    created: 1736963806572,
    data: {
      language: 'zh',
      source: '结果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultado, consequência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yj7Pr',
    created: 1736963808012,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconhecer, admitir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0WBHJ',
    created: 1736963809753,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: '',
      example: '',
      definition: '',
      translation: 'considerar, pensar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LL5l1',
    created: 1736963810531,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicação, oferta',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iwUpg',
    created: 1736963814565,
    data: {
      language: 'zh',
      source: '合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'legal, licit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sN-cv',
    created: 1736963815911,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ignorar, desconsiderar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ml0rX',
    created: 1736963817522,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuasão, convencimento',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '91ywY',
    created: 1736963819466,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente, passo a passo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0G7w7',
    created: 1736963821371,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'por toda parte, em toda parte',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G3o0z',
    created: 1736963822860,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'especialmente, particularmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Obfgj',
    created: 1736963824312,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'oportunamente, a tempo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i-jI-',
    created: 1736963826657,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente, mais ou menos',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7QLCI',
    created: 1736963828259,
    data: {
      language: 'zh',
      source: '足够',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suficiente, adequado',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OpjsH',
    created: 1736963830084,
    data: {
      language: 'zh',
      source: '执着',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persistente, teimoso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SUYX5',
    created: 1736963831738,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'estágio',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9WbH2',
    created: 1736963832535,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'alegre, divertido',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LKRWG',
    created: 1736963833383,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cautela, prudência',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oq42u',
    created: 1736963835609,
    data: {
      language: 'zh',
      source: '不等',
      ipa: '',
      example: '',
      definition: '',
      translation: 'diferente, desigual',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3pxwt',
    created: 1736963837992,
    data: {
      language: 'zh',
      source: '重要',
      ipa: '',
      example: '',
      definition: '',
      translation: 'importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
