import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ieJiD',
    created: 1736964220579,
    data: {
      language: 'zh',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uczciwy',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nXpfY',
    created: 1736964222087,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elastyczność',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_sulh',
    created: 1736964223158,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'punkt krytyczny',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6h5Y6',
    created: 1736964224796,
    data: {
      language: 'zh',
      source: '处置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zarządzać, ustawiać',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sjgnl',
    created: 1736964226034,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'odzew, reakcja',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0HrE5',
    created: 1736964227708,
    data: {
      language: 'zh',
      source: '结果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'wynik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PQs4g',
    created: 1736964228911,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uznać',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'L6GJ0',
    created: 1736964230453,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rozważać',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CEo8x',
    created: 1736964231661,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ofiarowanie, poświęcenie',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jgatQ',
    created: 1736964233254,
    data: {
      language: 'zh',
      source: '证明',
      ipa: '',
      example: '',
      definition: '',
      translation: 'udowodnić',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GnKp3',
    created: 1736964234738,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ignorować, zaniedbywać',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4Ja9b',
    created: 1736964236251,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perswazja',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'au2gJ',
    created: 1736964238137,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'stopniowo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AdSJ6',
    created: 1736964239967,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'wszędzie',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tDlID',
    created: 1736964243125,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'szczególnie',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M7waW',
    created: 1736964244694,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'na czas',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1_a3s',
    created: 1736964245597,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ogólnie, w przybliżeniu',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VNyBX',
    created: 1736964247117,
    data: {
      language: 'zh',
      source: '足够',
      ipa: '',
      example: '',
      definition: '',
      translation: 'wystarczająco',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JC1dx',
    created: 1736964249471,
    data: {
      language: 'zh',
      source: '执着',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uparty, wytrwały',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aW18j',
    created: 1736964250976,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'staż',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4eR2L',
    created: 1736964252079,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'przyjemny, wesoły',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6uM65',
    created: 1736964253218,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ostrożność',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4XPu8',
    created: 1736964255709,
    data: {
      language: 'zh',
      source: '不等',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nierówny',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TV5HE',
    created: 1736964257379,
    data: {
      language: 'zh',
      source: '重要',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ważny',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
