import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '5vbxu',
    created: 1736964024288,
    data: {
      language: 'zh',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ärlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bZjJY',
    created: 1736964026388,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elasticitet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XOzlq',
    created: 1736964027316,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gränspunkt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pe4TP',
    created: 1736964029549,
    data: {
      language: 'zh',
      source: '处置',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hantera, behandla',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'g5fxY',
    created: 1736964030367,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'återklang, respons',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HFiIm',
    created: 1736964031852,
    data: {
      language: 'zh',
      source: '结果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4F4aY',
    created: 1736964033788,
    data: {
      language: 'zh',
      source: '承认',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkänna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Bq-rJ',
    created: 1736964035256,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: '',
      example: '',
      definition: '',
      translation: 'överväga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jEuta',
    created: 1736964036476,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'offra, dedikera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ytF7j',
    created: 1736964038000,
    data: {
      language: 'zh',
      source: '证明',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bevisa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'es0nP',
    created: 1736964039345,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: '',
      example: '',
      definition: '',
      translation: 'förbise, ignorera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jzxq4',
    created: 1736964040620,
    data: {
      language: 'zh',
      source: '说服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övertalning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'palbb',
    created: 1736964042310,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '09-ZK',
    created: 1736964043860,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'överallt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's5Omv',
    created: 1736964045461,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'särskilt, framförallt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'x7GHg',
    created: 1736964046997,
    data: {
      language: 'zh',
      source: '及时',
      ipa: '',
      example: '',
      definition: '',
      translation: 'i tid',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lEiAR',
    created: 1736964047826,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefär, cirka',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DBm3T',
    created: 1736964049683,
    data: {
      language: 'zh',
      source: '足够',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräcklig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eKIAq',
    created: 1736964052548,
    data: {
      language: 'zh',
      source: '执着',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ihärdig, enveten',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jXUMv',
    created: 1736964053835,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: '',
      example: '',
      definition: '',
      translation: 'praktik',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ElaSp',
    created: 1736964054715,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'glad, trevlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U2NT6',
    created: 1736964058966,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försiktighet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WGvI5',
    created: 1736964061244,
    data: {
      language: 'zh',
      source: '不等',
      ipa: '',
      example: '',
      definition: '',
      translation: 'olik',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wVnNj',
    created: 1736964062771,
    data: {
      language: 'zh',
      source: '重要',
      ipa: '',
      example: '',
      definition: '',
      translation: 'viktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
