import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZO8Yv',
    created: 1736965639557,
    data: {
      language: 'zh-TW',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'чесність, правдивість',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UllFx',
    created: 1736965641009,
    data: {
      language: 'zh-TW',
      source: '彈性',
      ipa: '',
      example: '',
      definition: '',
      translation: 'еластичність, гнучкість',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oBoQo',
    created: 1736965642041,
    data: {
      language: 'zh-TW',
      source: '臨界點',
      ipa: '',
      example: '',
      definition: '',
      translation: 'критична точка',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JMtkj',
    created: 1736965642968,
    data: {
      language: 'zh-TW',
      source: '性格',
      ipa: '',
      example: '',
      definition: '',
      translation: 'характер',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jotwt',
    created: 1736965643847,
    data: {
      language: 'zh-TW',
      source: '迴響',
      ipa: '',
      example: '',
      definition: '',
      translation: 'відлуння',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '41QAj',
    created: 1736965645267,
    data: {
      language: 'zh-TW',
      source: '結果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'результат, наслідок',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f5vA6',
    created: 1736965646930,
    data: {
      language: 'zh-TW',
      source: '承認',
      ipa: '',
      example: '',
      definition: '',
      translation: 'визнання',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm_YbW',
    created: 1736965648328,
    data: {
      language: 'zh-TW',
      source: '考慮',
      ipa: '',
      example: '',
      definition: '',
      translation: 'розгляд, обдумування',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RaKCO',
    created: 1736965651866,
    data: {
      language: 'zh-TW',
      source: '奉獻',
      ipa: '',
      example: '',
      definition: '',
      translation: 'пожертва, внесок',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 't9wsV',
    created: 1736965653309,
    data: {
      language: 'zh-TW',
      source: '證明合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'легалізувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tQUfe',
    created: 1736965654989,
    data: {
      language: 'zh-TW',
      source: '忽視',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ігнорування, неувага',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JK9n-',
    created: 1736965656574,
    data: {
      language: 'zh-TW',
      source: '說服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'переконання',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KupnH',
    created: 1736965658027,
    data: {
      language: 'zh-TW',
      source: '逐步地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'поступово',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZL5g9',
    created: 1736965659684,
    data: {
      language: 'zh-TW',
      source: '隱含地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неявно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Un8af',
    created: 1736965661215,
    data: {
      language: 'zh-TW',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'особливо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VFGg6',
    created: 1736965662478,
    data: {
      language: 'zh-TW',
      source: '及時',
      ipa: '',
      example: '',
      definition: '',
      translation: 'вчасно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Dxq6V',
    created: 1736965663308,
    data: {
      language: 'zh-TW',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приблизно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9E0V3',
    created: 1736965665663,
    data: {
      language: 'zh-TW',
      source: '充分地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достатньо, повністю',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qMV57',
    created: 1736965667125,
    data: {
      language: 'zh-TW',
      source: '執著的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'пристрасний, упертий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KwRz0',
    created: 1736965667921,
    data: {
      language: 'zh-TW',
      source: '綜合的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'комплексний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hUM41',
    created: 1736965668821,
    data: {
      language: 'zh-TW',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приємний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k7SSY',
    created: 1736965669744,
    data: {
      language: 'zh-TW',
      source: '謹慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обережність',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AcDfh',
    created: 1736965671397,
    data: {
      language: 'zh-TW',
      source: '不情願的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неохочий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lRwKL',
    created: 1736965674710,
    data: {
      language: 'zh-TW',
      source: '重要的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'важливий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
