import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'dRqWa',
    created: 1736964994111,
    data: {
      language: 'zh-TW',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'استقامة, نزاهة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aaYvJ',
    created: 1736964995826,
    data: {
      language: 'zh-TW',
      source: '彈性',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مرونة, تكيّف',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lIDhn',
    created: 1736964997272,
    data: {
      language: 'zh-TW',
      source: '臨界點',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نقطة حرجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DBWM2',
    created: 1736964998133,
    data: {
      language: 'zh-TW',
      source: '性格',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شخصية',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9tJa9',
    created: 1736964999119,
    data: {
      language: 'zh-TW',
      source: '迴響',
      ipa: '',
      example: '',
      definition: '',
      translation: 'صدى',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i6VM5',
    created: 1736965002081,
    data: {
      language: 'zh-TW',
      source: '結果',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نتيجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TszGg',
    created: 1736965011482,
    data: {
      language: 'zh-TW',
      source: '承認',
      ipa: '',
      example: '',
      definition: '',
      translation: 'اعتراف',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nYtKN',
    created: 1736965013875,
    data: {
      language: 'zh-TW',
      source: '考慮',
      ipa: '',
      example: '',
      definition: '',
      translation: 'اعتبار, تفكير',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9ZZRm',
    created: 1736965014965,
    data: {
      language: 'zh-TW',
      source: '奉獻',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تضحية, إهداء',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qx5XH',
    created: 1736965016692,
    data: {
      language: 'zh-TW',
      source: '證明合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إثبات قانوني',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rBi2Y',
    created: 1736965018777,
    data: {
      language: 'zh-TW',
      source: '忽視',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تجاهل',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wR-61',
    created: 1736965020394,
    data: {
      language: 'zh-TW',
      source: '說服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إقناع',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'isCyh',
    created: 1736965022112,
    data: {
      language: 'zh-TW',
      source: '逐步地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بالتدريج',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GATUf',
    created: 1736965023117,
    data: {
      language: 'zh-TW',
      source: '隱含地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ضمنًا',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2GfjI',
    created: 1736965024649,
    data: {
      language: 'zh-TW',
      source: '尤其',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصاً, بشكل خاص',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '48mfm',
    created: 1736965026356,
    data: {
      language: 'zh-TW',
      source: '及時',
      ipa: '',
      example: '',
      definition: '',
      translation: 'في الوقت المناسب',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9qI7c',
    created: 1736965027235,
    data: {
      language: 'zh-TW',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقريباً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'adT2L',
    created: 1736965028929,
    data: {
      language: 'zh-TW',
      source: '充分地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بشكل كافٍ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f3MJb',
    created: 1736965030790,
    data: {
      language: 'zh-TW',
      source: '執著的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مخلص, متمسك',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8Zxw9',
    created: 1736965031709,
    data: {
      language: 'zh-TW',
      source: '綜合的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شامل, متكامل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tl20X',
    created: 1736965033309,
    data: {
      language: 'zh-TW',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ممتع, سعيد',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p9GpH',
    created: 1736965034216,
    data: {
      language: 'zh-TW',
      source: '謹慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حذر, متحفظ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8--nz',
    created: 1736965036267,
    data: {
      language: 'zh-TW',
      source: '不情願的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مُتَجَاهِل, مُرَاجِع',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2wto2',
    created: 1736965037692,
    data: {
      language: 'zh-TW',
      source: '重要的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مهم, ذو أهمية',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
