import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'oiZ_r',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛɡrɪti',
      example:
        "* She is known for her integrity.\n* The building's integrity was compromised.",
      definition:
        '* adherence to moral and ethical principles; soundness of moral character\n* the state of being whole, entire, or undiminished',
      translation: 'integritas, kejujuran',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'sUEjy',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪliəns',
      example:
        "* She showed great resilience in the face of adversity.\n* The material's resilience makes it ideal for shock absorption.",
      definition:
        '* The capacity to recover quickly from difficulties; toughness.\n* The ability of a substance or object to spring back into shape; elasticity.',
      translation: 'ketahanan, daya lenting',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'rBfEs',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃˌhoʊld',
      example:
        '* He stood on the threshold of his career.\n* She paused on the threshold.',
      definition:
        '* The point or level at which something begins or changes\n* A strip of wood, metal, or stone forming the bottom of a doorway and crossed in entering a house or room',
      translation: 'ambang, batas',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3Uu0D',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example:
        '* She has a cheerful disposition.\n* A disposition to avoid conflicts.\n* The disposition of troops.',
      definition:
        "* a person's inherent qualities of mind and character\n* an inclination or tendency of a particular kind\n* the action of arranging or ordering",
      translation: 'sikap, perilaku, watak, kecenderungan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'nHqHy',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpərˈkʌʃən',
      example:
        '* The decision had serious repercussions.\n* Economic repercussions were felt worldwide.',
      definition:
        'an unintended consequence occurring some time after an event or action',
      translation: 'dampak, akibat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Fmg7T',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example:
        '* The outcome was unexpected.\n* A positive outcome is desired.',
      definition: 'a result or effect of an action, situation, or event',
      translation: 'hasil, keluaran',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'X8egw',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'əkˈnɒl.ɪdʒ',
      example:
        "* She acknowledged her team's effort.\n* He acknowledged the mistake.\n* I acknowledge this receipt.",
      definition:
        'to accept, admit, or recognize something, or the truth or existence of something',
      translation: 'mengakui, menerima, menyadari',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '466IQ',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example: '* She considered the offer.\n* They considered him a friend.',
      definition:
        '* to think carefully about something, typically before making a decision\n* to regard someone or something in a particular way',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'riCcI',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example:
        '* She devotes her time to charity.\n* He devotes effort to research.',
      definition:
        "to give one's time, effort, or attention earnestly to a particular activity or purpose",
      translation: 'mendedikasikan, mengabdikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'IbxJ7',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstɪfaɪ',
      example: '* Justify your decision.\n* Can you justify the expense?',
      definition:
        '* show or prove to be right or reasonable\n* give a good reason for',
      translation: 'membenarkan, mempertanggungjawabkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'YAvBS',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈɡlɛkt',
      example:
        '* Child neglect is a serious issue.\n* Building fell into neglect.',
      definition:
        'Failure to care for or give attention to something or someone.',
      translation: 'pengabaian, kelalaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '9i2sZ',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example:
        '* She persuaded him to join\n* They persuaded me with their argument',
      definition:
        '* To cause someone to do something through reasoning or argument\n* To convince someone to believe something',
      translation: 'membujuk, meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'HAaR-',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈɡrædʒ.u.ə.li',
      example:
        '* The plant grew gradually\n* He spoke more confidently gradually',
      definition: '* In a gradual manner\n* Little by little',
      translation: 'perlahan-lahan, berangsur-angsur, sedikit demi sedikit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'i7YoE',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'implicitly',
      ipa: 'ɪmˈplɪsɪtli',
      example: '* She implicitly agreed.\n* He trusted her implicitly.',
      definition: 'in a way that is not directly expressed; tacitly',
      translation: 'secara implisit, dengan implisit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Yo-QC',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: '* He is notably absent.\n* The event was notably successful.',
      definition:
        '* in a way that is striking or remarkable\n* especially or particularly',
      translation: 'terutama, khususnya, secara khusus',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'my8z6',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'ˈprɒmptli',
      example:
        '* he arrived promptly at 9 am\n* reply promptly to the invitation',
      definition:
        '* with little or no delay\n* immediately or without hesitation',
      translation: 'segera, dengan cepat, tepat waktu',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'diLYw',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* The population increased roughly by 20,000.\n* He pushed the chair roughly aside.\n* Roughly speaking, it's a two-hour drive.",
      definition:
        '* approximately but not exactly\n* without being gentle or careful\n* in a manner lacking precision or detail',
      translation: 'kira-kira, sekitar, kurang lebih',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jB1Vy',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example:
        '* He was sufficiently prepared.\n* The work was sufficiently detailed.',
      definition: 'to an adequate degree; enough',
      translation: 'cukup, secukupnya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'juY1i',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example: '* persistent effort\n* persistent rain',
      definition:
        '* continuing firmly or obstinately despite difficulty or opposition\n* lasting for a long time or longer than expected',
      translation: 'gigih, tekun, ulet',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'QV1U2',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example:
        '* A comprehensive review was conducted.\n* They made a comprehensive list.',
      definition:
        'Thoroughly covering all or nearly all elements or aspects of something.',
      translation: 'komprehensif, lengkap',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'D_IYo',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfʊl',
      example: '* a delightful book\n* delightful weather',
      definition: 'Causing great pleasure or delight.',
      translation: 'menyenangkan, menggembirakan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Zz2c8',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔːʃəs',
      example: '* cautious driver\n* cautious approach',
      definition:
        '* careful to avoid potential problems or dangers\n* prudent in action or decision',
      translation: 'berhati-hati, waspada',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'tmygf',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: '* Reluctant to answer.\n* She was reluctant to agree.',
      definition: 'Unwilling and hesitant; disinclined.',
      translation: 'enggan, ragu-ragu, segan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'rPoIV',
    created: 1764155574873,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪɡˈnɪf.ɪ.kənt',
      example: '* significant improvement\n* significant impact',
      definition:
        '* important and meaningful\n* notable or large enough to make a difference',
      translation: 'signifikan, penting',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
