import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'noxye',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛɡrɪti',
      example:
        "* She is known for her integrity.\n* The building's integrity was compromised.",
      definition:
        '* adherence to moral and ethical principles; soundness of moral character\n* the state of being whole, entire, or undiminished',
      translation: 'ಅಖಂಡತೆ, ಪ್ರಾಮಾಣಿಕತೆ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'q6fpk',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪliəns',
      example:
        "* She showed great resilience in the face of adversity.\n* The material's resilience makes it ideal for shock absorption.",
      definition:
        '* The capacity to recover quickly from difficulties; toughness.\n* The ability of a substance or object to spring back into shape; elasticity.',
      translation: 'ಸ್ಥೈರ್ಯ, ತಾಳ್ಮೆ, ಮರುಸ್ಥಾಪನೆ, ಪುನಶ್ಚೇತನ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'gw-ZX',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃˌhoʊld',
      example:
        '* He stood on the threshold of his career.\n* She paused on the threshold.',
      definition:
        '* The point or level at which something begins or changes\n* A strip of wood, metal, or stone forming the bottom of a doorway and crossed in entering a house or room',
      translation: 'ಮರಳಿ, ದ್ವಾರ, ಅಂಚು',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'WuGjh',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example:
        '* She has a cheerful disposition.\n* A disposition to avoid conflicts.\n* The disposition of troops.',
      definition:
        "* a person's inherent qualities of mind and character\n* an inclination or tendency of a particular kind\n* the action of arranging or ordering",
      translation: 'ಸ್ವಭಾವ, ಪ್ರವೃತ್ತಿ, ಮನೋಭಾವ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'R72HI',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpərˈkʌʃən',
      example:
        '* The decision had serious repercussions.\n* Economic repercussions were felt worldwide.',
      definition:
        'an unintended consequence occurring some time after an event or action',
      translation: 'ಪರಿಣಾಮ, ಪ್ರತಿಫಲ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'E79iy',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example:
        '* The outcome was unexpected.\n* A positive outcome is desired.',
      definition: 'a result or effect of an action, situation, or event',
      translation: 'ಫಲಿತಾಂಶ, ಫಲ, ನಿಷ್ಕರ್ಷ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Fxkrv',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'əkˈnɒl.ɪdʒ',
      example:
        "* She acknowledged her team's effort.\n* He acknowledged the mistake.\n* I acknowledge this receipt.",
      definition:
        'to accept, admit, or recognize something, or the truth or existence of something',
      translation: 'ಒಪ್ಪಿಕೊಳ್ಳು, ಗುರುತಿಸು',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'HeUKL',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example: '* She considered the offer.\n* They considered him a friend.',
      definition:
        '* to think carefully about something, typically before making a decision\n* to regard someone or something in a particular way',
      translation: 'ಪರಿಗಣಿಸು, ವಿಚಾರಿಸು',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'fV7tD',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example:
        '* She devotes her time to charity.\n* He devotes effort to research.',
      definition:
        "to give one's time, effort, or attention earnestly to a particular activity or purpose",
      translation: 'ಮರುಳು, ಅರ್ಪಿಸು, ವ್ಯಯಿಸು',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'd8Q_u',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstɪfaɪ',
      example: '* Justify your decision.\n* Can you justify the expense?',
      definition:
        '* show or prove to be right or reasonable\n* give a good reason for',
      translation: 'ನ್ಯಾಯೀಕರಿಸು, ಸಮರ್ಥಿಸು',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'dvtNj',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈɡlɛkt',
      example:
        '* Child neglect is a serious issue.\n* Building fell into neglect.',
      definition:
        'Failure to care for or give attention to something or someone.',
      translation: 'ಅವಗಣನೆ, ನಿರ್ಲಕ್ಷ್ಯ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'IYWzr',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example:
        '* She persuaded him to join\n* They persuaded me with their argument',
      definition:
        '* To cause someone to do something through reasoning or argument\n* To convince someone to believe something',
      translation: 'ಮನೆ ಮಾಡು, ಪ್ರೇರೇಪಿಸು, ಬಲವಂತಪಡಿಸು',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'eAAp4',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈɡrædʒ.u.ə.li',
      example:
        '* The plant grew gradually\n* He spoke more confidently gradually',
      definition: '* In a gradual manner\n* Little by little',
      translation: 'ಹೆಚ್ಚುಹೆಚ್ಚಾಗಿ, ಕ್ರಮೇಣ, ನಿಧಾನವಾಗಿ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'vsiOg',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'implicitly',
      ipa: 'ɪmˈplɪsɪtli',
      example: '* She implicitly agreed.\n* He trusted her implicitly.',
      definition: 'in a way that is not directly expressed; tacitly',
      translation: 'ಅವ್ಯಕ್ತವಾಗಿ, ಅಪ್ರತ್ಯಕ್ಷವಾಗಿ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'kzj3v',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: '* He is notably absent.\n* The event was notably successful.',
      definition:
        '* in a way that is striking or remarkable\n* especially or particularly',
      translation: 'ಗಮನಾರ್ಹವಾಗಿ, ಪ್ರಮುಖವಾಗಿ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'osuEA',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'ˈprɒmptli',
      example:
        '* he arrived promptly at 9 am\n* reply promptly to the invitation',
      definition:
        '* with little or no delay\n* immediately or without hesitation',
      translation: 'ತಕ್ಷಣ, ಬೇಗ, ಕ್ಷಿಪ್ರವಾಗಿ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'XTGPJ',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* The population increased roughly by 20,000.\n* He pushed the chair roughly aside.\n* Roughly speaking, it's a two-hour drive.",
      definition:
        '* approximately but not exactly\n* without being gentle or careful\n* in a manner lacking precision or detail',
      translation: 'ಸುಮಾರು, ಅಂದಾಜು, ಹೆಚ್ಚು ಕಡಿಮೆ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3JieY',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example:
        '* He was sufficiently prepared.\n* The work was sufficiently detailed.',
      definition: 'to an adequate degree; enough',
      translation: 'ತಕ್ಕಮಟ್ಟಿಗೆ, ಸಾಕಷ್ಟು, ಸಮರ್ಪಕವಾಗಿ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'R8C1I',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example: '* persistent effort\n* persistent rain',
      definition:
        '* continuing firmly or obstinately despite difficulty or opposition\n* lasting for a long time or longer than expected',
      translation: 'ಹಠದ, ನಿರಂತರ, ಅವಿರತ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'gi3el',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example:
        '* A comprehensive review was conducted.\n* They made a comprehensive list.',
      definition:
        'Thoroughly covering all or nearly all elements or aspects of something.',
      translation: 'ವ್ಯಾಪಕ, ಸಮಗ್ರ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'MDlnp',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfʊl',
      example: '* a delightful book\n* delightful weather',
      definition: 'Causing great pleasure or delight.',
      translation: 'ಆನಂದಕರ, ಸುಖಕರ, ಹರ್ಷಕರ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'VSpzw',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔːʃəs',
      example: '* cautious driver\n* cautious approach',
      definition:
        '* careful to avoid potential problems or dangers\n* prudent in action or decision',
      translation: 'ಎಚ್ಚರಿಕೆಯಿಂದಿರುವ, ಜಾಗರೂಕ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'GrFQR',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: '* Reluctant to answer.\n* She was reluctant to agree.',
      definition: 'Unwilling and hesitant; disinclined.',
      translation: 'ಮಂದಹಾಸ, ಇಚ್ಛೆಯಿಲ್ಲದ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Obk92',
    created: 1764155596860,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪɡˈnɪf.ɪ.kənt',
      example: '* significant improvement\n* significant impact',
      definition:
        '* important and meaningful\n* notable or large enough to make a difference',
      translation: 'ಪ್ರಮುಖ, ಅರ್ಥಪೂರ್ಣ, ಗಮನಾರ್ಹ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
