import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '-xAZ5',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛɡrɪti',
      example:
        "* She is known for her integrity.\n* The building's integrity was compromised.",
      definition:
        '* adherence to moral and ethical principles; soundness of moral character\n* the state of being whole, entire, or undiminished',
      translation: '誠信, 正直, 完整性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'v0a30',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪliəns',
      example:
        "* She showed great resilience in the face of adversity.\n* The material's resilience makes it ideal for shock absorption.",
      definition:
        '* The capacity to recover quickly from difficulties; toughness.\n* The ability of a substance or object to spring back into shape; elasticity.',
      translation: '韌性, 彈性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'DaFXK',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃˌhoʊld',
      example:
        '* He stood on the threshold of his career.\n* She paused on the threshold.',
      definition:
        '* The point or level at which something begins or changes\n* A strip of wood, metal, or stone forming the bottom of a doorway and crossed in entering a house or room',
      translation: '門檻, 閾值',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'ip2Vg',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example:
        '* She has a cheerful disposition.\n* A disposition to avoid conflicts.\n* The disposition of troops.',
      definition:
        "* a person's inherent qualities of mind and character\n* an inclination or tendency of a particular kind\n* the action of arranging or ordering",
      translation: '性情, 性格, 傾向, 處置',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'SnupV',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpərˈkʌʃən',
      example:
        '* The decision had serious repercussions.\n* Economic repercussions were felt worldwide.',
      definition:
        'an unintended consequence occurring some time after an event or action',
      translation: '後果, 影響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'wF6p-',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example:
        '* The outcome was unexpected.\n* A positive outcome is desired.',
      definition: 'a result or effect of an action, situation, or event',
      translation: '結果, 後果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'FJu-E',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'əkˈnɒl.ɪdʒ',
      example:
        "* She acknowledged her team's effort.\n* He acknowledged the mistake.\n* I acknowledge this receipt.",
      definition:
        'to accept, admit, or recognize something, or the truth or existence of something',
      translation: '承認, 確認, 認可',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'r4lrH',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example: '* She considered the offer.\n* They considered him a friend.',
      definition:
        '* to think carefully about something, typically before making a decision\n* to regard someone or something in a particular way',
      translation: '考慮, 認為, 斟酌',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '8IuhN',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example:
        '* She devotes her time to charity.\n* He devotes effort to research.',
      definition:
        "to give one's time, effort, or attention earnestly to a particular activity or purpose",
      translation: '奉獻, 投入, 致力於',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'G63zW',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstɪfaɪ',
      example: '* Justify your decision.\n* Can you justify the expense?',
      definition:
        '* show or prove to be right or reasonable\n* give a good reason for',
      translation: '證明, 辯護, 合理化',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'IoSJI',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈɡlɛkt',
      example: '* neglected the garden\n* neglect your duties',
      definition:
        '* fail to care for properly\n* omit or disregard intentionally',
      translation: '忽視, 疏忽',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'wLlMr',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example:
        '* She persuaded him to join\n* They persuaded me with their argument',
      definition:
        '* To cause someone to do something through reasoning or argument\n* To convince someone to believe something',
      translation: '說服, 勸說',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'grODv',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈɡrædʒ.u.ə.li',
      example:
        '* The plant grew gradually\n* He spoke more confidently gradually',
      definition: '* In a gradual manner\n* Little by little',
      translation: '逐漸地, 漸漸地, 慢慢地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'f_QH0',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'implicitly',
      ipa: 'ɪmˈplɪsɪtli',
      example: '* She implicitly agreed.\n* He trusted her implicitly.',
      definition: 'in a way that is not directly expressed; tacitly',
      translation: '隱含地, 暗示地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'GpHxk',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: '* He is notably absent.\n* The event was notably successful.',
      definition:
        '* in a way that is striking or remarkable\n* especially or particularly',
      translation: '尤其, 顯著地, 特別地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'IVHuZ',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'ˈprɒmptli',
      example:
        '* he arrived promptly at 9 am\n* reply promptly to the invitation',
      definition:
        '* with little or no delay\n* immediately or without hesitation',
      translation: '立即, 馬上, 迅速地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Dnz8W',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* The population increased roughly by 20,000.\n* He pushed the chair roughly aside.\n* Roughly speaking, it's a two-hour drive.",
      definition:
        '* approximately but not exactly\n* without being gentle or careful\n* in a manner lacking precision or detail',
      translation: '大約, 大概, 約摸, 粗略地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'GItWY',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example:
        '* He was sufficiently prepared.\n* The work was sufficiently detailed.',
      definition: 'to an adequate degree; enough',
      translation: '足夠地, 充分地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'i0FTZ',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example: '* persistent effort\n* persistent rain',
      definition:
        '* continuing firmly or obstinately despite difficulty or opposition\n* lasting for a long time or longer than expected',
      translation: '持續的, 堅持的, 不屈不撓的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '2LDh6',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example:
        '* A comprehensive review was conducted.\n* They made a comprehensive list.',
      definition:
        'Thoroughly covering all or nearly all elements or aspects of something.',
      translation: '全面的, 綜合的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'uuNUF',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfʊl',
      example: '* a delightful book\n* delightful weather',
      definition: 'Causing great pleasure or delight.',
      translation: '愉快的, 令人愉快的, 可喜的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '75_Z8',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔːʃəs',
      example: '* cautious driver\n* cautious approach',
      definition:
        '* careful to avoid potential problems or dangers\n* prudent in action or decision',
      translation: '謹慎, 小心',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'pI7fU',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: '* Reluctant to answer.\n* She was reluctant to agree.',
      definition: 'Unwilling and hesitant; disinclined.',
      translation: '不情願的, 勉強的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3Fa4-',
    created: 1764155849133,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪɡˈnɪf.ɪ.kənt',
      example: '* significant improvement\n* significant impact',
      definition:
        '* important and meaningful\n* notable or large enough to make a difference',
      translation: '重要, 顯著, 重大',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
