import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Vh6vB',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: 'inteɣɾiˈðað',
      example: '* Actuar con integridad\n* Mantener la integridad del sistema',
      definition:
        '* Cualidad de íntegro\n* Estado de lo que está completo o no ha sido alterado',
      translation: 'eheys, rehellisyys, kokonaisuus',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'qNqMC',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'la resiliencia',
      ipa: 'resiˈljenθja',
      example:
        '* La resiliencia es clave en tiempos de crisis.\n* El acero tiene alta resiliencia.',
      definition:
        '* Capacidad de adaptación de un ser vivo frente a un agente perturbador o un estado o situación adversos.\n* Capacidad de un material elástico para absorber y almacenar energía de deformación.',
      translation: 'resilienssi, sinnikkyys',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jWxv-',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: 'ˈlimite',
      example:
        '* El límite de velocidad es 80 km/h.\n* Cruzó el límite de la propiedad.\n* Alcanzó su límite de paciencia.',
      definition:
        '* Línea real o imaginaria que marca el fin de una superficie o cuerpo.\n* Extremo que no se debe o no se puede sobrepasar.\n* Cantidad máxima o mínima que se permite.',
      translation: 'raja, rajoitus',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'xHXya',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: 'dispoˈθjon',
      example:
        '* Tiene buena disposición para aprender.\n* La disposición de los muebles es importante.\n* Está a disposición del público.',
      definition:
        '* Acción y efecto de disponer.\n* Inclinación natural hacia algo.\n* Ordenación de las cosas en un lugar.\n* Facultad o capacidad para hacer algo.',
      translation: 'järjestely, valmius, mieliala, asenne',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'fSbPR',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: 'repeɾkuˈsjon',
      example:
        '* La noticia tuvo gran repercusión\n* Las repercusiones del evento fueron significativas',
      definition:
        '* Consecuencia o efecto de un hecho o acción\n* Resonancia o impacto que algo tiene en un contexto determinado',
      translation: 'vaikutus, seuraus',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Mky2A',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: 'resulˈtado',
      example:
        '* El resultado fue inesperado.\n* Calcula el resultado de la suma.',
      definition:
        '* Efecto o consecuencia de un hecho, operación o deliberación.\n* Lo que se obtiene al resolver un problema matemático.',
      translation: 'tulos, lopputulos',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jUeDf',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: 'rekonoˈθeɾ',
      example:
        '* Reconoció su error.\n* No lo pude reconocer.\n* Reconocieron su esfuerzo.',
      definition:
        '* Distinguir o identificar a una persona o cosa entre varias por una serie de características propias.\n* Aceptar o admitir la verdad o existencia de algo.\n* Agradecer o mostrar gratitud por un favor o servicio recibido.',
      translation: 'tunnistaa, myöntää, tunnustaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'uY3_l',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: 'kon.si.ðeˈɾaɾ',
      example:
        '* Considerar una propuesta\n* Considerar las consecuencias\n* Considerar necesario',
      definition:
        '* Pensar detenidamente sobre algo\n* Tener en cuenta\n* Juzgar o estimar',
      translation: 'harkita, miettiä, pohtia',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'pVyWP',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: 'deðiˈkaɾ',
      example: '* Dedico este libro a mis padres.\n* Se dedica a la enseñanza.',
      definition:
        '* Consagrar o destinar algo a un fin determinado\n* Ofrecer una obra o acción a alguien como muestra de respeto o afecto',
      translation: 'omistaa, uhrata, pyhittää',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '7Iwq5',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: 'xus.ti.fiˈkaɾ',
      example:
        '* No pudo justificar su ausencia\n* Justificó su decisión con argumentos sólidos',
      definition:
        '* Probar algo con razones convincentes\n* Demostrar la inocencia de alguien\n* Dar razones para explicar un comportamiento',
      translation: 'perustella, oikeuttaa, puolustaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '2F2EX',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: 'desˈkwiðo',
      example: '* Cometió un descuido\n* Fue un descuido involuntario',
      definition:
        '* Falta de atención o cuidado\n* Negligencia en el cumplimiento de una obligación',
      translation: 'huolimattomuus, laiminlyönti',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'T3GKt',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: 'peɾswaˈðiɾ',
      example: '* Persuadir a un amigo\n* Persuadir con argumentos',
      definition: 'Inducir a alguien con razones a hacer o creer algo',
      translation: 'suostutella, vakuuttaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'dhYi-',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: 'ɡɾaðwaˈmente',
      example: '* El clima cambia gradualmente.\n* Mejoró gradualmente.',
      definition: '* De manera gradual\n* Poco a poco',
      translation: 'vähitellen, asteittain',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'KAR4t',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: 'imˈplisitamente',
      example: '* Aceptó implícitamente\n* Entendió implícitamente',
      definition: '* De manera implícita\n* Sin expresarlo directamente',
      translation: 'implisiittisesti, epäsuorasti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'LBb3X',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: 'notaˈβlemen̪te',
      example: '* Mejoró notablemente\n* Se destacó notablemente',
      definition:
        '* De manera notable o destacada\n* Con distinción o relevancia',
      translation: 'huomattavasti, merkittävästi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'PDqm3',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: 'inmeðjaˈtamen̪te',
      example: '* Llegó inmediatamente\n* Responde inmediatamente',
      definition: '* Sin demora\n* En el acto',
      translation: 'välittömästi, heti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'm8WP5',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* Apenas llegué, comenzó a llover.\n* Apenas se ve en la oscuridad.',
      definition: '* Casi no\n* Con dificultad\n* Tan pronto como',
      translation: 'juuri ja juuri, tuskin, heti kun',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'coESL',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: 'su.fi.θjen.teˈmen.te',
      example: '* Está suficientemente claro.\n* Habló suficientemente alto.',
      definition: 'En cantidad o grado suficiente',
      translation: 'riittävästi, tarpeeksi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'y4Ld_',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: 'peɾ.siˈsten.te',
      example: '* Es un trabajador persistente.\n* La lluvia fue persistente.',
      definition:
        '* Que persiste o se mantiene firme en algo.\n* Que dura mucho tiempo.',
      translation: 'pysyvä, itsepintainen, sinnikäs',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'PvHdb',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'integral',
      ipa: 'inteˈɡɾal',
      example: '* parte integral\n* visión integral',
      definition: '* Que forma parte de un todo\n* Completo, total',
      translation: 'kokonaisvaltainen, erottamaton, täydellinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'oKGf7',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: 'enkanˈtadoɾ',
      example: '* Un paisaje encantador\n* Una sonrisa encantadora',
      definition: '* Que causa encanto o deleite\n* Agradable o atractivo',
      translation: 'ihastuttava, viehättävä, hurmaava',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'vMUjg',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: 'pɾekaˈβiðo',
      example:
        '* Es muy precavido al cruzar la calle.\n* Siempre es precavido con sus inversiones.',
      definition:
        'Que actúa con precaución y anticipación para evitar posibles problemas o peligros.',
      translation: 'varovainen, huolellinen',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'vhx2A',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: 'reˈaθjo',
      example:
        '* Es reacio a cambiar de opinión\n* Se mostró reacio a participar',
      definition:
        '* Que muestra resistencia a hacer algo\n* Poco dispuesto a aceptar o admitir algo',
      translation: 'haluton, vastahakoinen',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'NInJi',
    created: 1764156019139,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: 'siɣnifikaˈtiβo',
      example: '* Un cambio significativo\n* Un gesto significativo',
      definition:
        '* Que tiene significado o importancia\n* Que expresa o manifiesta algo',
      translation: 'merkittävä, merkityksellinen',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
