import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'TMOBp',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: 'inteɣɾiˈðað',
      example: '* Actuar con integridad\n* Mantener la integridad del sistema',
      definition:
        '* Cualidad de íntegro\n* Estado de lo que está completo o no ha sido alterado',
      translation: 'integritas, kejujuran',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'u0jHt',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'la resiliencia',
      ipa: 'resiˈljenθja',
      example:
        '* La resiliencia es clave en tiempos de crisis.\n* El acero tiene alta resiliencia.',
      definition:
        '* Capacidad de adaptación de un ser vivo frente a un agente perturbador o un estado o situación adversos.\n* Capacidad de un material elástico para absorber y almacenar energía de deformación.',
      translation: 'ketahanan, daya lenting',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'hW7ag',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: 'ˈlimite',
      example:
        '* El límite de velocidad es 80 km/h.\n* Cruzó el límite de la propiedad.\n* Alcanzó su límite de paciencia.',
      definition:
        '* Línea real o imaginaria que marca el fin de una superficie o cuerpo.\n* Extremo que no se debe o no se puede sobrepasar.\n* Cantidad máxima o mínima que se permite.',
      translation: 'batas, limit',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'dx87h',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: 'dispoˈθjon',
      example:
        '* Tiene buena disposición para aprender.\n* La disposición de los muebles es importante.\n* Está a disposición del público.',
      definition:
        '* Acción y efecto de disponer.\n* Inclinación natural hacia algo.\n* Ordenación de las cosas en un lugar.\n* Facultad o capacidad para hacer algo.',
      translation: 'pengaturan, kesiapan, disposisi, penyediaan',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3Yb5t',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: 'repeɾkuˈsjon',
      example:
        '* La noticia tuvo gran repercusión\n* Las repercusiones del evento fueron significativas',
      definition:
        '* Consecuencia o efecto de un hecho o acción\n* Resonancia o impacto que algo tiene en un contexto determinado',
      translation: 'dampak, pengaruh',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'UIeCk',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: 'resulˈtado',
      example:
        '* El resultado fue inesperado.\n* Calcula el resultado de la suma.',
      definition:
        '* Efecto o consecuencia de un hecho, operación o deliberación.\n* Lo que se obtiene al resolver un problema matemático.',
      translation: 'hasil, keputusan',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '-zWib',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: 'rekonoˈθeɾ',
      example:
        '* Reconoció su error.\n* No lo pude reconocer.\n* Reconocieron su esfuerzo.',
      definition:
        '* Distinguir o identificar a una persona o cosa entre varias por una serie de características propias.\n* Aceptar o admitir la verdad o existencia de algo.\n* Agradecer o mostrar gratitud por un favor o servicio recibido.',
      translation: 'mengenali, mengakui',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'LljSX',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: 'kon.si.ðeˈɾaɾ',
      example:
        '* Considerar una propuesta\n* Considerar las consecuencias\n* Considerar necesario',
      definition:
        '* Pensar detenidamente sobre algo\n* Tener en cuenta\n* Juzgar o estimar',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'iwu3L',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: 'deðiˈkaɾ',
      example: '* Dedico este libro a mis padres.\n* Se dedica a la enseñanza.',
      definition:
        '* Consagrar o destinar algo a un fin determinado\n* Ofrecer una obra o acción a alguien como muestra de respeto o afecto',
      translation: 'mendedikasikan, mengabdikan, mempersembahkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '_bMG8',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: 'xus.ti.fiˈkaɾ',
      example:
        '* No pudo justificar su ausencia\n* Justificó su decisión con argumentos sólidos',
      definition:
        '* Probar algo con razones convincentes\n* Demostrar la inocencia de alguien\n* Dar razones para explicar un comportamiento',
      translation: 'membenarkan, membuktikan, membela',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'ZFQul',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: 'desˈkwiðo',
      example: '* Cometió un descuido\n* Fue un descuido involuntario',
      definition:
        '* Falta de atención o cuidado\n* Negligencia en el cumplimiento de una obligación',
      translation: 'kelalaian, keteledoran, pengabaian',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'j7UBC',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: 'peɾswaˈðiɾ',
      example: '* Persuadir a un amigo\n* Persuadir con argumentos',
      definition: 'Inducir a alguien con razones a hacer o creer algo',
      translation: 'membujuk, meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'qtBol',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: 'ɡɾaðwaˈmente',
      example: '* El clima cambia gradualmente.\n* Mejoró gradualmente.',
      definition: '* De manera gradual\n* Poco a poco',
      translation: 'secara bertahap, perlahan-lahan',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'bTy_5',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: 'imˈplisitamente',
      example: '* Aceptó implícitamente\n* Entendió implícitamente',
      definition: '* De manera implícita\n* Sin expresarlo directamente',
      translation: 'secara implisit, implisit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'eeqIF',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: 'notaˈβlemen̪te',
      example: '* Mejoró notablemente\n* Se destacó notablemente',
      definition:
        '* De manera notable o destacada\n* Con distinción o relevancia',
      translation: 'secara mencolok, secara nyata, secara signifikan',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'e3PpU',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: 'inmeðjaˈtamen̪te',
      example: '* Llegó inmediatamente\n* Responde inmediatamente',
      definition: '* Sin demora\n* En el acto',
      translation: 'segera, langsung, dengan segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '5txgV',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* Apenas llegué, comenzó a llover.\n* Apenas se ve en la oscuridad.',
      definition: '* Casi no\n* Con dificultad\n* Tan pronto como',
      translation: 'hampir tidak, baru saja, nyaris tidak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'MxVMH',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: 'su.fi.θjen.teˈmen.te',
      example: '* Está suficientemente claro.\n* Habló suficientemente alto.',
      definition: 'En cantidad o grado suficiente',
      translation: 'cukup, secukupnya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'BW3_9',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: 'peɾ.siˈsten.te',
      example: '* Es un trabajador persistente.\n* La lluvia fue persistente.',
      definition:
        '* Que persiste o se mantiene firme en algo.\n* Que dura mucho tiempo.',
      translation: 'gigih, tekun',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '9LXR3',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'la integral',
      ipa: 'inteˈɡɾal',
      example: '* La integral de la función\n* Parte integral del equipo',
      definition:
        '* Parte esencial de un todo\n* Función matemática que representa el área bajo una curva',
      translation: 'integral, menyeluruh',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'tyNZN',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: 'enkanˈtadoɾ',
      example: '* Un paisaje encantador\n* Una sonrisa encantadora',
      definition: '* Que causa encanto o deleite\n* Agradable o atractivo',
      translation: 'menawan, memikat, menarik',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'aPogQ',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: 'pɾekaˈβiðo',
      example:
        '* Es muy precavido al cruzar la calle.\n* Siempre es precavido con sus inversiones.',
      definition:
        'Que actúa con precaución y anticipación para evitar posibles problemas o peligros.',
      translation: 'berhati-hati, waspada, cermat',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'sTEBd',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: 'reˈaθjo',
      example:
        '* Es reacio a cambiar de opinión\n* Se mostró reacio a participar',
      definition:
        '* Que muestra resistencia a hacer algo\n* Poco dispuesto a aceptar o admitir algo',
      translation: 'enggan, menolak, tidak mau',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'M2uI5',
    created: 1764156109406,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: 'siɣnifikaˈtiβo',
      example: '* Un cambio significativo\n* Un gesto significativo',
      definition:
        '* Que tiene significado o importancia\n* Que expresa o manifiesta algo',
      translation: 'signifikan, berarti, penting',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
