import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'E-Qpr',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: 'ĩteɡɾiˈdadʒi',
      example:
        '* A integridade do documento foi verificada.\n* Ele é conhecido por sua integridade.',
      definition:
        '* qualidade de íntegro\n* estado de algo que não foi alterado ou corrompido\n* honestidade e retidão de caráter',
      translation: 'integrita, celistvost',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'MsvzI',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: 'ʁe.ziˈljẽ.si.a',
      example:
        '* A resiliência é essencial em tempos difíceis.\n* Ela mostrou resiliência após a crise.',
      definition:
        '* capacidade de se recuperar de adversidades\n* habilidade de voltar ao estado original após deformação',
      translation: 'odolnost, pružnost',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'O1iNu',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: 'liˈmitʃi',
      example:
        '* O limite da cidade.\n* Ultrapassou o limite de velocidade.\n* O limite do orçamento.',
      definition:
        '* Linha ou ponto que marca o final de uma área ou superfície.\n* Restrição ou condição que não deve ser ultrapassada.\n* Extensão máxima de algo.',
      translation: 'hranice, mez, limit',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'RiHzq',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: 'dʒispoziˈsɐ̃w̃',
      example:
        '* A disposição dos móveis na sala.\n* Estou com boa disposição hoje.\n* Ele tem disposição para ajudar.',
      definition:
        '* arranjo ou organização de algo\n* estado de ânimo ou saúde\n* tendência ou inclinação para algo',
      translation: 'dispozice, ochota, nálada',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'ES1tk',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: 'ʁɛpɛʁkuˈsɐ̃w̃',
      example:
        '* A notícia teve grande repercussão.\n* A repercussão do evento foi inesperada.',
      definition:
        '* resultado de um evento ou ação\n* efeito ou consequência que algo provoca\n* eco ou ressonância de um som',
      translation: 'dopad, ozvěna, následek',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'sXJ4g',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: 'ʁezulˈtadu',
      example:
        '* O resultado foi positivo.\n* Aguardo o resultado do exame.\n* O resultado do jogo foi surpreendente.',
      definition:
        '* Efeito ou consequência de uma ação, operação ou processo.\n* Aquilo que se obtém como resposta ou solução de um problema.\n* Desfecho de uma competição ou evento.',
      translation: 'výsledek, důsledek',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'qnvww',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: 'ʁekõˈɲesɛʁ',
      example:
        '* Ele reconheceu o amigo de infância.\n* Ela reconheceu o erro.\n* A empresa reconheceu o esforço dos funcionários.',
      definition:
        '* Identificar algo ou alguém previamente conhecido.\n* Admitir ou aceitar a verdade de algo.\n* Agradecer ou valorizar um feito ou qualidade.',
      translation: 'rozpoznat, uznat, poznat',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'g6AeP',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: 'kõsideraɾ',
      example:
        '* Considerar uma proposta\n* Considerar as consequências\n* Considerar alguém como amigo',
      definition:
        '* Pensar sobre algo com atenção\n* Levar em conta\n* Julgar ou avaliar',
      translation: 'zvážit, považovat',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'vubOw',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: 'de.d͡ʒiˈkaɾ',
      example:
        '* Ela decidiu dedicar sua vida à ciência.\n* Ele dedicou o livro aos pais.',
      definition:
        '* consagrar algo a um propósito\n* destinar tempo ou esforço a uma atividade\n* oferecer algo a alguém como homenagem',
      translation: 'věnovat, zasvětit, dedikovat',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'F_fbg',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: 'ʒus.tʃi.fiˈkaɾ',
      example:
        '* Ele tentou justificar sua ausência.\n* Ela justificou suas ações com documentos.\n* O aluno justificou o erro na prova.',
      definition:
        '* Apresentar razões ou argumentos para demonstrar a validade de algo\n* Provar a inocência ou a correção de alguém ou de algo\n* Dar motivo ou causa a algo',
      translation: 'ospravedlnit, zdůvodnit',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'ppFOP',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: 'neɡliˈʒẽsjɐ',
      example:
        '* A negligência no trabalho causou problemas.\n* Foi acusado de negligência médica.',
      definition:
        '* Falta de cuidado ou atenção\n* Desleixo ou descuido em realizar uma tarefa',
      translation: 'nedbalost, zanedbání',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jUnbd',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: 'peʁswaˈd͡ʒiʁ',
      example:
        '* Ele tentou persuadir o amigo.\n* Ela conseguiu persuadir o chefe.',
      definition:
        '* Convencer alguém a fazer ou acreditar em algo\n* Induzir alguém a aceitar uma ideia ou opinião',
      translation: 'přesvědčit, přemluvit',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'OoQjA',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: 'ɡɾɐdʒwaˈmẽtʃi',
      example:
        '* A temperatura aumentou gradualmente.\n* Ele foi se adaptando gradualmente.',
      definition: '* De maneira gradual\n* Progressivamente',
      translation: 'postupně, gradualně',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'iSZZ8',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: 'ĩ.pli.si.taˈmẽ.tʃi',
      example:
        '* Ele concordou implicitamente.\n* A mensagem foi transmitida implicitamente.',
      definition: '* de maneira implícita\n* sem ser declarado diretamente',
      translation: 'implicitně, nepřímo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Vxlex',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: 'no.taˈvel.mẽj',
      example:
        '* Ele se destacou notavelmente.\n* Notavelmente, ela venceu a competição.',
      definition: '* de maneira notável\n* de forma destacada',
      translation: 'pozoruhodně, výrazně, nápadně',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'IlZs8',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'prontamente',
      ipa: 'pɾõ.tɐˈmẽ.tʃi',
      example: '* Ele respondeu prontamente.\n* A ajuda chegou prontamente.',
      definition: '* de maneira pronta\n* rapidamente\n* sem demora',
      translation: 'okamžitě, ihned, promptně',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '88bqS',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: 'apɾɔksimadɐˈmẽtʃi',
      example:
        '* Aproximadamente cem pessoas\n* Chegaremos aproximadamente às 10h',
      definition: '* De modo aproximado\n* Cerca de\n* Quase',
      translation: 'přibližně, asi, zhruba, okolo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '8rja7',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'suficientemente',
      ipa: 'su.fi.si.en.teˈmen.t͡ʃi',
      example:
        '* Ele estudou suficientemente.\n* A casa é suficientemente grande.',
      definition: '* de maneira suficiente\n* em quantidade ou grau adequado',
      translation: 'dostatečně, dostatečným způsobem',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'mwvS6',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: 'peʁ.sisˈtẽ.t͡ʃi',
      example: '* Chuva persistente.\n* Atitude persistente.',
      definition:
        '* Que persiste; que continua a existir ou a ocorrer.\n* Que demonstra perseverança; insistente.',
      translation: 'vytrvalý, houževnatý, neústupný',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Ny3z3',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: 'a.bɾɐ̃.ˈʒẽ.tʃi',
      example:
        '* um estudo abrangente\n* uma análise abrangente\n* um relatório abrangente',
      definition:
        '* que abrange ou cobre uma grande área\n* extenso ou amplo em escopo\n* inclusivo ou compreensivo',
      translation: 'komplexní, obsáhlý, rozsáhlý',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '4Du3v',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: 'de.liˈsjo.zu',
      example: '* bolo delicioso\n* perfume delicioso',
      definition: '* que tem sabor agradável\n* encantador, agradável',
      translation: 'lahodný, chutný, delikátní',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'OZHI6',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'cauteloso',
      ipa: 'kaw.teˈlo.zu',
      example:
        '* Ele é cauteloso ao investir.\n* Adotou uma abordagem cautelosa.',
      definition:
        '* Que age com cautela; prudente.\n* Que demonstra precaução.',
      translation: 'opatrný, obezřetný',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'M3mtj',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: 'ʁe.luˈtɐ̃.tʃi',
      example:
        '* Ele estava relutante em aceitar a oferta.\n* Ela ficou relutante em falar sobre o assunto.',
      definition:
        '* que hesita em tomar uma decisão\n* que demonstra resistência ou falta de vontade',
      translation: 'váhavý, neochotný',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'M9vju',
    created: 1764163613212,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: 'siɡnifiˈkativu',
      example:
        '* um avanço significativo\n* resultado significativo\n* mudança significativa',
      definition:
        '* que tem significado\n* importante ou relevante\n* que expressa algo de forma clara',
      translation: 'významný, podstatný, důležitý',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
