import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '-nF6y',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: 'ĩteɡɾiˈdadʒi',
      example:
        '* A integridade do documento foi verificada.\n* Ele é conhecido por sua integridade.',
      definition:
        '* qualidade de íntegro\n* estado de algo que não foi alterado ou corrompido\n* honestidade e retidão de caráter',
      translation: 'integritat',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'jQ-FI',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: 'ʁe.ziˈljẽ.si.a',
      example:
        '* A resiliência é essencial em tempos difíceis.\n* Ela mostrou resiliência após a crise.',
      definition:
        '* capacidade de se recuperar de adversidades\n* habilidade de voltar ao estado original após deformação',
      translation: 'resiliència',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'hnQpn',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: 'liˈmitʃi',
      example:
        '* O limite da cidade.\n* Ultrapassou o limite de velocidade.\n* O limite do orçamento.',
      definition:
        '* Linha ou ponto que marca o final de uma área ou superfície.\n* Restrição ou condição que não deve ser ultrapassada.\n* Extensão máxima de algo.',
      translation: 'límit, frontera',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'FICww',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: 'dʒispoziˈsɐ̃w̃',
      example:
        '* A disposição dos móveis na sala.\n* Estou com boa disposição hoje.\n* Ele tem disposição para ajudar.',
      definition:
        '* arranjo ou organização de algo\n* estado de ânimo ou saúde\n* tendência ou inclinação para algo',
      translation: "disposició, ganes, estat d'ànim",
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'RS3FS',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: 'ʁɛpɛʁkuˈsɐ̃w̃',
      example:
        '* A notícia teve grande repercussão.\n* A repercussão do evento foi inesperada.',
      definition:
        '* resultado de um evento ou ação\n* efeito ou consequência que algo provoca\n* eco ou ressonância de um som',
      translation: 'repercussió, ressò',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'uvreN',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: 'ʁezulˈtadu',
      example:
        '* O resultado foi positivo.\n* Aguardo o resultado do exame.\n* O resultado do jogo foi surpreendente.',
      definition:
        '* Efeito ou consequência de uma ação, operação ou processo.\n* Aquilo que se obtém como resposta ou solução de um problema.\n* Desfecho de uma competição ou evento.',
      translation: 'resultat',
      partOfSpeech: 'noun',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'UcYVk',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: 'ʁekõˈɲesɛʁ',
      example:
        '* Ele reconheceu o amigo de infância.\n* Ela reconheceu o erro.\n* A empresa reconheceu o esforço dos funcionários.',
      definition:
        '* Identificar algo ou alguém previamente conhecido.\n* Admitir ou aceitar a verdade de algo.\n* Agradecer ou valorizar um feito ou qualidade.',
      translation: 'reconèixer, identificar, admetre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'S0k6h',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: 'kõsideraɾ',
      example:
        '* Considerar uma proposta\n* Considerar as consequências\n* Considerar alguém como amigo',
      definition:
        '* Pensar sobre algo com atenção\n* Levar em conta\n* Julgar ou avaliar',
      translation: 'considerar, tenir en compte',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'iaO6p',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: 'de.d͡ʒiˈkaɾ',
      example:
        '* Ela decidiu dedicar sua vida à ciência.\n* Ele dedicou o livro aos pais.',
      definition:
        '* consagrar algo a um propósito\n* destinar tempo ou esforço a uma atividade\n* oferecer algo a alguém como homenagem',
      translation: 'dedicar, consagrar, destinar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'to_Rr',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: 'ʒus.tʃi.fiˈkaɾ',
      example:
        '* Ele tentou justificar sua ausência.\n* Ela justificou suas ações com documentos.\n* O aluno justificou o erro na prova.',
      definition:
        '* Apresentar razões ou argumentos para demonstrar a validade de algo\n* Provar a inocência ou a correção de alguém ou de algo\n* Dar motivo ou causa a algo',
      translation:
        'justificar, justifiqui, justifiques, justifiquem, justifiqueu, justifiquen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'sB8cS',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: 'neɡliˈʒẽsjɐ',
      example:
        '* A negligência no trabalho causou problemas.\n* Foi acusado de negligência médica.',
      definition:
        '* Falta de cuidado ou atenção\n* Desleixo ou descuido em realizar uma tarefa',
      translation: 'negligència, descurança',
      partOfSpeech: 'noun',
      g: 'feminine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Il1xO',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: 'peʁswaˈd͡ʒiʁ',
      example:
        '* Ele tentou persuadir o amigo.\n* Ela conseguiu persuadir o chefe.',
      definition:
        '* Convencer alguém a fazer ou acreditar em algo\n* Induzir alguém a aceitar uma ideia ou opinião',
      translation: 'persuadir, convèncer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'sPYNB',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: 'ɡɾɐdʒwaˈmẽtʃi',
      example:
        '* A temperatura aumentou gradualmente.\n* Ele foi se adaptando gradualmente.',
      definition: '* De maneira gradual\n* Progressivamente',
      translation: 'gradualment, a poc a poc',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'tb_F5',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: 'ĩ.pli.si.taˈmẽ.tʃi',
      example:
        '* Ele concordou implicitamente.\n* A mensagem foi transmitida implicitamente.',
      definition: '* de maneira implícita\n* sem ser declarado diretamente',
      translation: 'implícitament',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '-OCVQ',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: 'no.taˈvel.mẽj',
      example:
        '* Ele se destacou notavelmente.\n* Notavelmente, ela venceu a competição.',
      definition: '* de maneira notável\n* de forma destacada',
      translation: 'notablement, notòriament',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '7rqg3',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'prontamente',
      ipa: 'pɾõ.tɐˈmẽ.tʃi',
      example: '* Ele respondeu prontamente.\n* A ajuda chegou prontamente.',
      definition: '* de maneira pronta\n* rapidamente\n* sem demora',
      translation: 'ràpidament, immediatament, prontament',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'loBou',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: 'apɾɔksimadɐˈmẽtʃi',
      example:
        '* Aproximadamente cem pessoas\n* Chegaremos aproximadamente às 10h',
      definition: '* De modo aproximado\n* Cerca de\n* Quase',
      translation: 'aproximadament, aprox',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: '3lmx0',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'suficientemente',
      ipa: 'su.fi.si.en.teˈmen.t͡ʃi',
      example:
        '* Ele estudou suficientemente.\n* A casa é suficientemente grande.',
      definition: '* de maneira suficiente\n* em quantidade ou grau adequado',
      translation: 'suficientment, prou',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'EDzAW',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: 'peʁ.sisˈtẽ.t͡ʃi',
      example: '* Chuva persistente.\n* Atitude persistente.',
      definition:
        '* Que persiste; que continua a existir ou a ocorrer.\n* Que demonstra perseverança; insistente.',
      translation: 'persistent, perseverant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Gq4f2',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: 'a.bɾɐ̃.ˈʒẽ.tʃi',
      example:
        '* um estudo abrangente\n* uma análise abrangente\n* um relatório abrangente',
      definition:
        '* que abrange ou cobre uma grande área\n* extenso ou amplo em escopo\n* inclusivo ou compreensivo',
      translation: 'ampli, extens, global, integral',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'cuRV6',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: 'de.liˈsjo.zu',
      example: '* bolo delicioso\n* perfume delicioso',
      definition: '* que tem sabor agradável\n* encantador, agradável',
      translation: 'deliciós, deliciosa',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Yd_aw',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'cauteloso',
      ipa: 'kaw.teˈlo.zu',
      example:
        '* Ele é cauteloso ao investir.\n* Adotou uma abordagem cautelosa.',
      definition:
        '* Que age com cautela; prudente.\n* Que demonstra precaução.',
      translation: 'cautelós, prudent',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'D8afA',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: 'ʁe.luˈtɐ̃.tʃi',
      example:
        '* Ele estava relutante em aceitar a oferta.\n* Ela ficou relutante em falar sobre o assunto.',
      definition:
        '* que hesita em tomar uma decisão\n* que demonstra resistência ou falta de vontade',
      translation: 'reticent, indecís, vacil·lant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
  {
    id: 'Ggym4',
    created: 1764163590343,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: 'siɡnifiˈkativu',
      example:
        '* um avanço significativo\n* resultado significativo\n* mudança significativa',
      definition:
        '* que tem significado\n* importante ou relevante\n* que expressa algo de forma clara',
      translation: 'significatiu, rellevant',
      partOfSpeech: 'adjective',
      g: 'masculine',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1764115200000,
    },
  },
];
