import { GoogleLanguage } from '@vocably/model';
import { get } from 'lodash-es';
import { getDeviceLanguage } from '../getDeviceLanguage';

const cards: { en: string[] } & Partial<Record<GoogleLanguage, string[]>> = {
  en: [
    `Vocably is built for people who **use** a foreign language in real life and want to **reach fluency**.`,
    `If you're still learning the basics and not ready to use your new language, Vocably isn't for you yet. **Come back when you're ready.**`,
    `If you've decided to start using a foreign language in real life, **Vocably will support you** in the following situations:`,
    `**Hear or see a word in real life**: translate with the mobile app → save → learn.`,
    `**Need to say something but don't know the word?** Search for the right word or phrase in your native language → save → learn. Vocably provides an **AI-powered dictionary** that gets slang, idioms, and real-life language.`,
    `**Found a new word on any website**: select → translate → save → learn (works in Desktop Chrome, Desktop Safari, iOS Safari, Android).`,
    `**Watching YouTube on your computer**: click a word in the subtitles → translate → save → learn (works in Desktop Chrome, Desktop Safari).`,
    `**Reading an e-book on Android**: long-press a word → translate → save → learn (works with most Android e-book readers).`,
    `Learning a language is mostly about **discovering and remembering new words**. Vocably is the only tool designed entirely for this.`,
  ],
  ru: [
    'Vocably создан для людей, которые **используют** иностранный язык в реальной жизни и хотят **достичь свободного владения языком**.',
    'Если вы все еще изучаете основы и не готовы использовать новый язык, Vocably пока не для вас. **Возвращайтесь, когда будете готовы.**',
    'Если вы решили начать использовать иностранный язык в реальной жизни, **Vocably поддержит вас** в следующих ситуациях:',
    '**Услышали или увидели слово в реальной жизни**: переведите его в мобильном приложении → сохраните → выучите.',
    '**Нужно что-то сказать, но не знаете слово?** Найдите нужное слово или фразу на своем родном языке → сохраните → выучите. Vocably предоставляет **словарь на базе AI**, который понимает сленг, идиомы и живой язык.',
    '**Нашли новое слово на любом сайте**: выделите → переведите → сохраните → выучите (работает в Chrome для ПК, Safari для ПК, Safari на iOS, Android).',
    '**Смотрите YouTube на компьютере**: нажмите на слово в субтитрах → переведите → сохраните → выучите (работает в Chrome для ПК, Safari для ПК).',
    '**Читаете электронную книгу на Android**: зажмите слово → переведите → сохраните → выучите (работает в большинстве читалок для Android).',
    'Изучение языка в основном связано с **обнаружением и запоминанием новых слов**. Vocably — единственный инструмент, полностью созданный для этого.',
    'Остальная часть приложения **полностью на английском языке**.',
  ],
  uk: [
    'Vocably створений для людей, які **використовують** іноземну мову в реальному житті та хочуть **досягти вільного володіння мовою**.',
    'Якщо ви ще вивчаєте основи і не готові використовувати нову мову, Vocably поки не для вас. **Поверніться, коли будете готові.**',
    'Якщо ви вирішили почати використовувати іноземну мову в реальному житті, **Vocably підтримає вас** у таких ситуаціях:',
    '**Почули або побачили слово в реальному житті**: перекладіть у мобільному додатку → збережіть → вивчіть.',
    '**Потрібно щось сказати, але не знаєте слова?** Знайдіть потрібне слово або фразу рідною мовою → збережіть → вивчіть. Vocably надає **словник на базі ШІ**, який розуміє сленг, ідіоми та живу мову.',
    '**Знайшли нове слово на будь-якому сайті**: виділіть → перекладіть → збережіть → вивчіть (працює в Chrome для ПК, Safari для ПК, Safari на iOS, Android).',
    '**Дивитеся YouTube на комп’ютері**: натисніть на слово в субтитрах → перекладіть → збережіть → вивчіть (працює в Chrome для ПК, Safari для ПК).',
    '**Читаєте електронну книгу на Android**: затисніть слово → перекладіть → збережіть → вивчіть (працює в більшості читалок для Android).',
    "Вивчення мови здебільшого пов'язане з **виявленням і запам’ятовуванням нових слів**. Vocably — єдиний інструмент, створений саме для цього.",
    'Решта додатку **повністю англійською мовою**.',
  ],
  es: [
    'Vocably está hecho para personas que **usan** un idioma extranjero en la vida real y quieren **alcanzar un dominio fluido del idioma**.',
    'Si todavía estás aprendiendo lo básico y no estás listo para usar tu nuevo idioma, Vocably no es para ti todavía. **Vuelve cuando estés listo.**',
    'Si has decidido empezar a usar un idioma extranjero en la vida real, **Vocably te apoyará** en las siguientes situaciones:',
    '**Escuchas o ves una palabra en la vida real**: tradúcela con la aplicación móvil → guarda → apréndela.',
    '**¿Necesitas decir algo pero no sabes la palabra?** Busca la palabra o frase adecuada en tu idioma nativo → guarda → apréndela. Vocably ofrece un **diccionario con IA** que entiende jerga, modismos y lenguaje real.',
    '**Encontraste una palabra nueva en cualquier sitio web**: selecciona → traduce → guarda → apréndela (funciona en Chrome de escritorio, Safari de escritorio, Safari en iOS, Android).',
    '**Viendo YouTube en tu computadora**: haz clic en una palabra en los subtítulos → traduce → guarda → apréndela (funciona en Chrome de escritorio, Safari de escritorio).',
    '**Leyendo un libro electrónico en Android**: mantén presionada una palabra → traduce → guarda → apréndela (funciona con la mayoría de lectores de Android).',
    'Aprender un idioma se trata principalmente de **descubrir y memorizar nuevas palabras**. Vocably es la única herramienta diseñada completamente para esto.',
    'El resto de la aplicación está **totalmente en inglés**.',
  ],
  pt: [
    'O Vocably foi feito para pessoas que **usam** um idioma estrangeiro na vida real e querem **alcançar fluência**.',
    'Se você ainda está aprendendo o básico e não está pronto para usar seu novo idioma, o Vocably ainda não é para você. **Volte quando estiver pronto.**',
    'Se você decidiu começar a usar um idioma estrangeiro na vida real, **o Vocably vai te apoiar** nas seguintes situações:',
    '**Ouviu ou viu uma palavra na vida real**: traduza com o app → salve → aprenda.',
    '**Precisa dizer algo mas não sabe a palavra?** Procure a palavra ou frase certa no seu idioma nativo → salve → aprenda. O Vocably oferece um **dicionário com IA** que entende gírias, expressões e linguagem real.',
    '**Encontrou uma nova palavra em qualquer site**: selecione → traduza → salve → aprenda (funciona no Chrome de desktop, Safari de desktop, Safari no iOS, Android).',
    '**Assistindo YouTube no computador**: clique em uma palavra nas legendas → traduza → salve → aprenda (funciona no Chrome de desktop, Safari de desktop).',
    '**Lendo um e-book no Android**: pressione e segure uma palavra → traduza → salve → aprenda (funciona com a maioria dos leitores de e-book no Android).',
    'Aprender um idioma é principalmente sobre **descobrir e memorizar novas palavras**. O Vocably é a única ferramenta criada totalmente para isso.',
    'O restante do aplicativo está **inteiramente em inglês**.',
  ],
  it: [
    'Vocably è pensato per persone che **usano** una lingua straniera nella vita reale e vogliono **raggiungere una padronanza fluente della lingua**.',
    'Se stai ancora imparando le basi e non sei pronto a usare la tua nuova lingua, Vocably non è ancora per te. **Torna quando sei pronto.**',
    'Se hai deciso di iniziare a usare una lingua straniera nella vita reale, **Vocably ti supporterà** nelle seguenti situazioni:',
    '**Senti o vedi una parola nella vita reale**: traducila con l’app → salva → imparala.',
    '**Hai bisogno di dire qualcosa ma non conosci la parola?** Cerca la parola o frase giusta nella tua lingua madre → salva → imparala. Vocably offre un **dizionario basato su IA** che comprende slang, modi di dire e linguaggio reale.',
    '**Hai trovato una nuova parola su un sito web**: seleziona → traduci → salva → imparala (funziona su Chrome desktop, Safari desktop, Safari iOS, Android).',
    '**Guardando YouTube sul tuo computer**: clicca su una parola nei sottotitoli → traduci → salva → imparala (funziona su Chrome desktop, Safari desktop).',
    '**Leggendo un e-book su Android**: tieni premuta una parola → traduci → salva → imparala (funziona con la maggior parte dei lettori Android).',
    'Imparare una lingua significa soprattutto **scoprire e memorizzare nuove parole**. Vocably è l’unico strumento creato interamente per questo.',
    'Il resto dell’app è **completamente in inglese**.',
  ],
  fr: [
    'Vocably est conçu pour les personnes qui **utilisent** une langue étrangère dans la vie réelle et veulent **atteindre une maîtrise courante de la langue**.',
    'Si vous apprenez encore les bases et n’êtes pas prêt à utiliser votre nouvelle langue, Vocably n’est pas encore pour vous. **Revenez quand vous serez prêt.**',
    'Si vous avez décidé de commencer à utiliser une langue étrangère dans la vie réelle, **Vocably vous soutiendra** dans les situations suivantes :',
    '**Vous entendez ou voyez un mot dans la vie réelle** : traduisez-le avec l’appli → enregistrez → apprenez-le.',
    '**Besoin de dire quelque chose mais vous ne connaissez pas le mot ?** Cherchez le bon mot ou la bonne phrase dans votre langue maternelle → enregistrez → apprenez-le. Vocably propose un **dictionnaire basé sur l’IA** qui comprend l’argot, les idiomes et la langue réelle.',
    '**Vous avez trouvé un nouveau mot sur un site web** : sélectionnez → traduisez → enregistrez → apprenez-le (fonctionne sur Chrome de bureau, Safari de bureau, Safari iOS, Android).',
    '**Regardez YouTube sur votre ordinateur** : cliquez sur un mot dans les sous-titres → traduisez → enregistrez → apprenez-le (fonctionne sur Chrome de bureau, Safari de bureau).',
    '**Lire un e-book sur Android** : appuyez longuement sur un mot → traduisez → enregistrez → apprenez-le (fonctionne avec la plupart des liseuses Android).',
    'Apprendre une langue consiste surtout à **découvrir et mémoriser de nouveaux mots**. Vocably est le seul outil conçu entièrement pour cela.',
    'Le reste de l’application est **entièrement en anglais**.',
  ],
  ar: [
    'تم تصميم Vocably للأشخاص الذين **يستخدمون** لغة أجنبية في الحياة الواقعية ويريدون **الوصول إلى إتقان اللغة بطلاقة**.',
    'إذا كنت لا تزال تتعلم الأساسيات ولست مستعدًا لاستخدام لغتك الجديدة، فإن Vocably ليس لك بعد. **عد عندما تكون مستعدًا.**',
    'إذا قررت البدء في استخدام لغة أجنبية في الحياة الواقعية، فإن **Vocably سيدعمك** في المواقف التالية:',
    '**سمعت أو رأيت كلمة في الحياة الواقعية**: ترجمها باستخدام التطبيق → احفظها → تعلمها.',
    '**تحتاج لقول شيء ولكن لا تعرف الكلمة؟** ابحث عن الكلمة أو العبارة المناسبة بلغتك الأم → احفظها → تعلمها. يوفر Vocably **قاموسًا مدعومًا بالذكاء الاصطناعي** يفهم العامية والتعابير واللغة الواقعية.',
    '**وجدت كلمة جديدة على أي موقع**: حدد → ترجم → احفظها → تعلمها (يعمل على Chrome لسطح المكتب، Safari لسطح المكتب، Safari على iOS، Android).',
    '**تشاهد YouTube على الكمبيوتر**: انقر على كلمة في الترجمة → ترجم → احفظها → تعلمها (يعمل على Chrome لسطح المكتب، Safari لسطح المكتب).',
    '**قراءة كتاب إلكتروني على Android**: اضغط مطولاً على كلمة → ترجم → احفظها → تعلمها (يعمل مع معظم قارئات Android).',
    'تعلم اللغة يدور في الغالب حول **اكتشاف وحفظ كلمات جديدة**. Vocably هو الأداة الوحيدة المصممة بالكامل لهذا.',
    'بقية التطبيق **باللغة الإنجليزية بالكامل**.',
  ],
  vi: [
    'Vocably được tạo ra cho những người **sử dụng** ngoại ngữ trong đời thực và muốn **đạt được khả năng sử dụng thành thạo**.',
    'Nếu bạn vẫn đang học những điều cơ bản và chưa sẵn sàng sử dụng ngôn ngữ mới của mình, Vocably chưa dành cho bạn. **Hãy quay lại khi bạn đã sẵn sàng.**',
    'Nếu bạn đã quyết định bắt đầu sử dụng ngoại ngữ trong đời thực, **Vocably sẽ hỗ trợ bạn** trong các tình huống sau:',
    '**Nghe hoặc thấy một từ trong đời thực**: dịch bằng ứng dụng di động → lưu → học thuộc.',
    '**Cần nói điều gì đó nhưng không biết từ?** Tìm từ hoặc cụm từ phù hợp bằng tiếng mẹ đẻ → lưu → học thuộc. Vocably cung cấp **từ điển hỗ trợ AI** hiểu tiếng lóng, thành ngữ và ngôn ngữ đời thực.',
    '**Tìm thấy từ mới trên bất kỳ trang web nào**: chọn → dịch → lưu → học thuộc (hoạt động trên Chrome máy tính, Safari máy tính, Safari iOS, Android).',
    '**Xem YouTube trên máy tính**: nhấp vào từ trong phụ đề → dịch → lưu → học thuộc (hoạt động trên Chrome máy tính, Safari máy tính).',
    '**Đọc sách điện tử trên Android**: nhấn giữ từ → dịch → lưu → học thuộc (hoạt động với hầu hết các trình đọc sách Android).',
    'Học ngôn ngữ chủ yếu là **khám phá và ghi nhớ từ mới**. Vocably là công cụ duy nhất được thiết kế hoàn toàn cho việc này.',
    'Phần còn lại của ứng dụng **hoàn toàn bằng tiếng Anh**.',
  ],
  tr: [
    'Vocably, gerçek hayatta yabancı dil **kullanan** ve **akıcı bir şekilde konuşmak isteyen** kişiler için tasarlandı.',
    'Eğer hâlâ temelleri öğreniyor ve yeni dilinizi kullanmaya hazır değilseniz, Vocably şimdilik size göre değil. **Hazır olduğunuzda geri dönün.**',
    'Gerçek hayatta yabancı bir dil kullanmaya karar verdiyseniz, **Vocably sizi şu durumlarda destekler**:',
    '**Gerçek hayatta bir kelime duydunuz veya gördünüz**: mobil uygulama ile çevirin → kaydedin → öğrenin.',
    '**Bir şey söylemeniz gerekiyor ama kelimeyi bilmiyor musunuz?** Ana dilinizde doğru kelimeyi veya ifadeyi arayın → kaydedin → öğrenin. Vocably, argo, deyimler ve günlük dili anlayan **yapay zekâ destekli bir sözlük** sunar.',
    '**Herhangi bir web sitesinde yeni bir kelime buldunuz**: seçin → çevirin → kaydedin → öğrenin (Masaüstü Chrome, Masaüstü Safari, iOS Safari, Android’de çalışır).',
    '**Bilgisayarınızda YouTube izlerken**: altyazılardaki bir kelimeye tıklayın → çevirin → kaydedin → öğrenin (Masaüstü Chrome ve Safari’de çalışır).',
    '**Android’de e-kitap okurken**: bir kelimeye uzun basın → çevirin → kaydedin → öğrenin (çoğu Android e-kitap okuyucusunda çalışır).',
    'Dil öğrenmek çoğunlukla **yeni kelimeleri keşfetmek ve ezberlemekle** ilgilidir. Vocably, tamamen bunun için tasarlanmış tek araçtır.',
    'Uygulamanın geri kalanı **tamamen İngilizcedir**.',
  ],
  pl: [
    'Vocably zostało stworzone dla osób, które **używają** języka obcego w prawdziwym życiu i chcą **osiągnąć biegłą znajomość języka**.',
    'Jeśli wciąż uczysz się podstaw i nie jesteś gotowy używać nowego języka, Vocably nie jest jeszcze dla ciebie. **Wróć, gdy będziesz gotowy.**',
    'Jeśli zdecydowałeś się zacząć używać języka obcego w prawdziwym życiu, **Vocably wesprze cię** w następujących sytuacjach:',
    '**Usłyszałeś lub zobaczyłeś słowo w prawdziwym życiu**: przetłumacz je w aplikacji mobilnej → zapisz → naucz się.',
    '**Musisz coś powiedzieć, ale nie znasz słowa?** Wyszukaj odpowiednie słowo lub frazę w swoim ojczystym języku → zapisz → naucz się. Vocably oferuje **słownik wspierany przez AI**, który rozumie slang, idiomy i język codzienny.',
    '**Znalazłeś nowe słowo na dowolnej stronie internetowej**: zaznacz → przetłumacz → zapisz → naucz się (działa w Chrome i Safari na komputerze, Safari na iOS i na Androidzie).',
    '**Oglądasz YouTube na komputerze**: kliknij słowo w napisach → przetłumacz → zapisz → naucz się (działa w Chrome i Safari na komputerze).',
    '**Czytasz e-booka na Androidzie**: przytrzymaj słowo → przetłumacz → zapisz → naucz się (działa w większości czytników e-booków na Androidzie).',
    'Nauka języka polega głównie na **odkrywaniu i zapamiętywaniu nowych słów**. Vocably to jedyne narzędzie stworzone całkowicie w tym celu.',
    'Reszta aplikacji jest **w całości po angielsku**.',
  ],
  ko: [
    'Vocably는 실제 생활에서 외국어를 **사용**하고 **유창하게 말하고 싶은** 사람들을 위해 만들어졌습니다.',
    '아직 기초를 배우는 중이고 새로운 언어를 사용할 준비가 되지 않았다면, Vocably는 아직 당신을 위한 것이 아닙니다. **준비가 되면 다시 오세요.**',
    '실제 생활에서 외국어를 사용하기로 결정했다면, **Vocably는 다음 상황에서 당신을 지원합니다:**',
    '**실제 생활에서 단어를 듣거나 봤을 때**: 모바일 앱으로 번역 → 저장 → 외우기.',
    '**뭔가 말하고 싶은데 단어를 모를 때?** 모국어로 적절한 단어 또는 구를 검색 → 저장 → 외우기. Vocably는 속어, 관용구 및 실제 언어를 이해하는 **AI 기반 사전**을 제공합니다.',
    '**웹사이트에서 새로운 단어를 발견했을 때**: 선택 → 번역 → 저장 → 외우기 (데스크톱 Chrome, 데스크톱 Safari, iOS Safari, Android에서 작동).',
    '**컴퓨터에서 YouTube를 볼 때**: 자막의 단어를 클릭 → 번역 → 저장 → 외우기 (데스크톱 Chrome 및 Safari에서 작동).',
    '**Android에서 전자책을 읽을 때**: 단어를 길게 누르기 → 번역 → 저장 → 외우기 (대부분의 Android 전자책 리더에서 작동).',
    '언어 학습은 주로 **새로운 단어를 발견하고 기억하는 것**에 관한 것입니다. Vocably는 이를 위해 완전히 설계된 유일한 도구입니다.',
    '앱의 나머지 부분은 **완전히 영어로 되어 있습니다**.',
  ],
  ja: [
    'Vocablyは、実生活で外国語を**使い**、**流暢に話せるようになりたい**人のために作られました。',
    'まだ基礎を学んでいて新しい言語を使う準備ができていないなら、Vocablyはまだあなたには向いていません。**準備ができたら戻ってきてください。**',
    '実生活で外国語を使うことに決めたなら、**Vocablyは次のような状況であなたをサポートします:**',
    '**実生活で単語を聞いたり見たりしたとき**: モバイルアプリで翻訳 → 保存 → 覚える。',
    '**何かを言いたいけど単語がわからないとき?** 母国語で適切な単語やフレーズを検索 → 保存 → 覚える。Vocablyはスラング、慣用句、実際の言葉を理解する**AI搭載辞書**を提供します。',
    '**ウェブサイトで新しい単語を見つけたとき**: 選択 → 翻訳 → 保存 → 覚える (デスクトップ版Chrome、Safari、iOS Safari、Androidで動作)。',
    '**パソコンでYouTubeを見ているとき**: 字幕の単語をクリック → 翻訳 → 保存 → 覚える (デスクトップ版ChromeとSafariで動作)。',
    '**Androidで電子書籍を読むとき**: 単語を長押し → 翻訳 → 保存 → 覚える (ほとんどのAndroid電子書籍リーダーで動作)。',
    '言語学習は主に**新しい単語を発見して記憶すること**が中心です。Vocablyはこのためだけに完全に設計された唯一のツールです。',
    'アプリの残りの部分は**すべて英語です**。',
  ],
};

export const getCards = (): string[] => {
  const deviceLanguage = getDeviceLanguage();

  if (deviceLanguage === undefined) {
    return cards['en'];
  }

  return get(cards, deviceLanguage, cards['en']);
};
